Repository open-telemetry/opentelemetry-collector, pull requests merged in 2021-12, with the labels that each got.

#4500 Include SchemaURL in OTLP text
  internal/otlptext/logs.go
  internal/otlptext/metrics.go
  internal/otlptext/traces.go
Labels: Skip Changelog

#4486 `docs`: update release documentation to use push-tag
  docs/release.md
Labels: ready-to-merge, Skip Changelog

#4504 Small nit in collector tests, same config already available in testdata
  service/collector_test.go
Labels: Skip Changelog

#3970 feat: informative user-agent for otlp exporters
  CHANGELOG.md
  exporter/otlpexporter/factory.go
  exporter/otlpexporter/otlp.go
  exporter/otlpexporter/otlp_test.go
  exporter/otlphttpexporter/factory.go
  exporter/otlphttpexporter/otlp.go
  exporter/otlphttpexporter/otlp_test.go
Labels: ready-to-merge

#4519 Add a warning message for legacy OTLP HTTP endpoint usage
  receiver/otlpreceiver/otlp.go
Labels: Skip Changelog

#4087 Remove reference to `defaultcomponents` in core and deprecate `include_core` flag
  CHANGELOG.md
  cmd/builder/README.md
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/builder/config_test.go
  cmd/builder/internal/command.go
  cmd/builder/test/nocore.builder.yaml
  cmd/builder/test/replaces.builder.yaml
  internal/testcomponents/example_factories.go
  service/collector_test.go
  service/collector_windows_test.go
  service/command_test.go
  service/configcheck_test.go
  service/defaultcomponents/default_exporters_test.go
  service/defaultcomponents/default_extensions_test.go
  service/defaultcomponents/default_processors_test.go
  service/defaultcomponents/default_receivers_test.go
Labels: ready-to-merge

#4531 Credit grpc-ecosystem/go-grpc-middleware for WrappedServerStream
  internal/middleware/wrappedstream.go
Labels: Skip Changelog

#4441 Support Snappy and Zstd for confighttp.go
  CHANGELOG.md
  config/confighttp/README.md
  config/confighttp/confighttp.go
  config/confighttp/confighttp_test.go
  exporter/otlphttpexporter/README.md
  exporter/otlphttpexporter/config.go
  exporter/otlphttpexporter/config_test.go
  exporter/otlphttpexporter/otlp.go
  exporter/otlphttpexporter/otlp_test.go
  go.mod
  internal/middleware/compression.go
  internal/middleware/compression_test.go
Labels: ready-to-merge

#4536 Use action/checkout fetch-depth instead of manually fetch
  .github/workflows/changelog.yml
Labels: Skip Changelog

#4491 An initial draft of updating recomendations
  CHANGELOG.md
  CONTRIBUTING.md
Labels: Skip Changelog

#4069 Enable configuring telemetry through service config file
  CHANGELOG.md
  component/componenttest/nop_telemetry.go
  component/telemetry.go
  config/config_test.go
  config/configtelemetry/configtelemetry.go
  config/configtelemetry/configtelemetry_test.go
  config/configunmarshaler/defaultunmarshaler.go
  config/configunmarshaler/defaultunmarshaler_test.go
  config/configunmarshaler/testdata/invalid-metrics-level.yaml
  config/configunmarshaler/testdata/valid-config.yaml
  config/service.go
  exporter/exporterhelper/common.go
  processor/batchprocessor/factory.go
  processor/memorylimiterprocessor/memorylimiter.go
  service/collector.go
  service/collector_test.go
  service/flags.go
  service/internal/builder/exporters_builder.go
  service/internal/builder/pipelines_builder.go
  service/internal/builder/receivers_builder.go
  service/internal/extensions/extensions.go
  service/telemetry.go
Labels: ready-to-merge

#4560 Revert "Use action/checkout fetch-depth instead of manually fetch (#4535)"
  .github/workflows/changelog.yml
Labels: ready-to-merge, Skip Changelog

#4561 Small nits in service package
  service/collector.go
  service/config_watcher.go
  service/config_watcher_test.go
  service/service.go
Labels: Skip Changelog

#4572 Remove error test map provider from merge tests, use the mock
  config/configmapprovider/merge_test.go
Labels: Skip Changelog

#4574 Add env config map provider, read from environment variable
  config/configmapprovider/env.go
  config/configmapprovider/env_test.go
  config/configmapprovider/testdata/invalid-yaml.yaml
Labels: Skip Changelog

#4575 Add tests for file config map provider
  config/configmapprovider/file_test.go
Labels: Skip Changelog

#4576 Remove resolved TODO from the merge config map provider
  config/configmapprovider/merge.go
Labels: Skip Changelog

#4578 bump staleness to 14 days
  .github/workflows/stale-pr.yaml
Labels: Skip Changelog

#4564 config provider: remove the need to call the onChange with close error
  config/configmapprovider/provider.go
  config/configmapprovider/retrieved.go
Labels: Skip Changelog

#4586 Upgrade cobra, viper, grpc to latest
  cmd/builder/go.mod
  cmd/builder/go.sum
  config/configgrpc/configgrpc.go
  go.mod
  go.sum
  receiver/otlpreceiver/internal/logs/otlp_test.go
  receiver/otlpreceiver/internal/metrics/otlp_test.go
  receiver/otlpreceiver/internal/trace/otlp_test.go
  receiver/otlpreceiver/otlp_test.go
Labels: Skip Changelog

#4589 Fix local otelcol core build for testing
  Makefile
  internal/buildscripts/builder-config.yaml
Labels: Skip Changelog

#4588 Expose a new public interface service.ConfigProvider
  service/collector.go
  service/config_provider.go
  service/config_provider_test.go
Labels: Skip Changelog

#4591 Add new default service config provider, remove map default provider
  service/collector_test.go
  service/collector_windows.go
  service/command.go
  service/config_provider.go
  service/config_provider_test.go
  service/internal/configprovider/default.go
  service/internal/configprovider/default_test.go
  service/internal/configprovider/testdata/default-config.yaml
Labels: Skip Changelog

#4598 fix nil error introduced in SetColGRPCLogger
  service/internal/telemetrylogs/logger.go
Labels: Skip Changelog

#4594 [Builder]: Generate test file for config struct check
  cmd/builder/internal/builder/main.go
  cmd/builder/internal/builder/templates.go
  cmd/builder/internal/builder/templates/components_test.go.tmpl
  cmd/otelcorecol/components_test.go
  cmd/otelcorecol/go.mod
Labels: Skip Changelog

#4607 Remove configtest dependency from collector, generate tests in builder
  service/collector.go
  service/command_test.go
  service/configcheck.go
  service/configcheck_test.go
Labels: Skip Changelog

#4609 Avoid using config.ID() when possible, understand if can be removed
  service/internal/builder/receivers_builder.go
Labels: Skip Changelog

#4610 Fix security issue with github.com/gin-gonic/gin
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: Skip Changelog
