Repository open-telemetry/opentelemetry-collector, pull requests merged in 2022-11, with the labels that each got.

#6473 tests: move obsreport tests fixture to file
  obsreport/obsreporttest/otelprometheuschecker_test.go
  obsreport/obsreporttest/testdata/prometheus_response
Labels: Skip Changelog

#6488 Change component.DataType enum value names to be consistent with other in the repo
  .chloggen/deprecateallconfig.yaml
  component/config.go
  config/moved_config.go
  exporter/exporterhelper/internal/persistent_queue_test.go
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/queued_retry_test.go
  exporter/exporterhelper/traces.go
  obsreport/obsreport_exporter.go
  obsreport/obsreport_receiver.go
  obsreport/obsreport_scraper.go
  service/config.go
  service/internal/pipelines/pipelines.go
  service/internal/pipelines/pipelines_test.go
  service/service_test.go
Labels: Skip Changelog

#6485 Remove get from newly added funcs on Gate that don't conflict
  featuregate/gates.go
  featuregate/gates_test.go
  service/zpages.go
Labels: Skip Changelog

#6487 Change featuregate.Stage enum value names to be consistent with other in the repo
  confmap/resolver.go
  featuregate/gates.go
  featuregate/gates_test.go
  internal/obsreportconfig/obsreportconfig.go
Labels: Skip Changelog

#6484 Fix Reference drive-letter specification link invalid #6374
  confmap/resolver.go
Labels: Skip Changelog

#6503 Prepare v0.64.0
  .chloggen/allowsampling.yaml
  .chloggen/cgroup-subsys-line-parse.yaml
  .chloggen/cgroup-v1-int64.yaml
  .chloggen/deprecateallconfig.yaml
  .chloggen/msg_add-issue-link-feature-gate.yaml
  .chloggen/mvunmarshaler.yaml
  .chloggen/mx-psi_add-logging-0.0.0.0.yaml
  .chloggen/obsreport-exporter.yaml
  .chloggen/obsreport_new_methods.yaml
  .chloggen/providehelpers.yaml
  .chloggen/rename-severy-numer-and-state-string-output.yaml
  .chloggen/rmconfigconfig.yaml
  .chloggen/rmdeprecated.yaml
  .chloggen/split-extension.yaml
  .chloggen/split-processor.yaml
  .chloggen/split-receiver.yaml
  .chloggen/valiation-for-empty-metric-address.yaml
  CHANGELOG.md
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/config/default.yaml
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/main.go
  examples/k8s/otel-config.yaml
  exporter/loggingexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/ballastextension/go.mod
  extension/zpagesextension/go.mod
  go.mod
  processor/batchprocessor/go.mod
  processor/memorylimiterprocessor/go.mod
  receiver/otlpreceiver/go.mod
  versions.yaml
Labels: Skip Changelog

#6512 Update changelog, race condition with the prepare PR
  .chloggen/confmapmu.yaml
  CHANGELOG.md
Labels: Skip Changelog

#6519 Update changelog for v0.64.1
  .chloggen/fixlogging.yaml
  CHANGELOG.md
Labels: Skip Changelog

#6000 Support SIGHUP configuration reloading
  .chloggen/sighup-configuration-reloading.yaml
  service/collector.go
  service/collector_test.go
Labels: Stale

#6358 [docs] Add a doc for scraping receivers
  docs/scraping-receivers.md
Labels: Skip Changelog

#6535 [component] clarifying lifecycle expectation
  component/component.go
Labels: Skip Changelog

#6567 Make dmitryax a maintainer
  README.md
Labels: Skip Changelog

#6568 [chore] update dep to make update-otel easier
  .chloggen/split-consumer.yaml
  cmd/otelcorecol/go.mod
  component/go.mod
  exporter/loggingexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/ballastextension/go.mod
  extension/zpagesextension/go.mod
  go.mod
  processor/batchprocessor/go.mod
  processor/memorylimiterprocessor/go.mod
  receiver/otlpreceiver/go.mod
Labels: Skip Changelog

#6570 [release] Update release schedule
  docs/release.md
Labels: Skip Changelog

#6502 [docs] add documentation around patch release
  docs/release.md
Labels: Skip Changelog

#6587 Update the usage of set-output command in GH actions
  .github/workflows/check-links.yaml
  .github/workflows/scripts/set_release_tag.sh
  .github/workflows/scripts/verify-dist-files-exist.sh
Labels: Skip Changelog

#6590 Update CHANGELOG.md file for 0.65.0 release
  .chloggen/deprecate_hexstring.yaml
  .chloggen/deprecate_obsreport_must_new_functions.yaml
  .chloggen/deprecatecomp.yaml
  .chloggen/deprecateget.yaml
  .chloggen/deprecatevalidate.yaml
  .chloggen/draftminhost.yaml
  .chloggen/featuregatestage.yaml
  .chloggen/fromrawerror.yaml
  .chloggen/instrument-batch-processor-with-otel-go.yaml
  .chloggen/level-update-string.yaml
  .chloggen/obsreport-scraper.yaml
  .chloggen/processor-duplication-per-pipeline.yaml
  .chloggen/registeroption.yaml
  .chloggen/remove_units_suffix_otel_go_prometheus_exporter.yaml
  .chloggen/rename-dev-stability-level.yaml
  .chloggen/return_error_for_obsreport_new_functions.yaml
  .chloggen/rmdepcfggrpc.yaml
  .chloggen/rmdepcfgtest.yaml
  .chloggen/rmdepconfig.yaml
  .chloggen/rmdeprecatedgates.yaml
  .chloggen/rmexperimental.yaml
  .chloggen/sighup-configuration-reloading.yaml
  .chloggen/split-components.yaml
  .chloggen/split-consumer.yaml
  .chloggen/split-featuregate.yaml
  .chloggen/statenames.yaml
  .chloggen/update-stability-level-string.yaml
  CHANGELOG.md
Labels: Skip Changelog

#6598 Remove tigrannajaryan as Maintainer
  README.md
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests

#6618 Remove verbose flag and limitation to run one process from unit tests
  Makefile.Common
Labels: Skip Changelog

#6612 Run builder tests with local collector module
  cmd/builder/internal/builder/main_test.go
  cmd/builder/test/core.builder.yaml
  cmd/builder/test/test.sh
  docs/release.md
Labels: Skip Changelog

#6620 Document organization of Makefile, Makefile.Common
  CONTRIBUTING.md
Labels: Skip Changelog

#6603 Don't escape go error output in builder
  cmd/builder/internal/builder/main.go
Labels: Skip Changelog

#6634 Bump version for the tools
  internal/tools/go.mod
  internal/tools/go.sum
Labels: dependencies

#6636 Change dependencies to v0.66.0
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/main.go
  component/go.mod
  consumer/go.mod
  exporter/loggingexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/ballastextension/go.mod
  extension/zpagesextension/go.mod
  go.mod
  processor/batchprocessor/go.mod
  processor/memorylimiterprocessor/go.mod
  receiver/otlpreceiver/go.mod
  versions.yaml
Labels: dependencies
