Repository open-telemetry/opentelemetry-collector, pull requests merged in 2022-12, with the labels that each got.

#6292 Replace manually adding tags with multimod
  Makefile
  docs/release.md
Labels: Skip Changelog

#6662 Revert github.com/shirou/gopsutil/v3 to previous version, tag removed
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  confmap/go.mod
  confmap/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  go.mod
  go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
Labels: dependencies

#6641 Prefix auth funcs/types with Client. Add *Func types
  .chloggen/move-configauth-to-extension-step-1.yaml
  config/configauth/deprecated.go
  extension/auth/default_clientauthenticator.go
  extension/auth/default_clientauthenticator_test.go
Labels: Skip Changelog

#6640 Prefix auth funcs/types with Server to be consistent with Client.
  .chloggen/move-configauth-to-extension-step-1.yaml
  config/configauth/deprecated.go
  config/configgrpc/configgrpc.go
  config/configgrpc/configgrpc_test.go
  config/confighttp/confighttp.go
  config/confighttp/confighttp_test.go
  extension/auth/default_serverauthenticator.go
  extension/auth/default_serverauthenticator_test.go
  extension/auth/serverauth.go
Labels: Skip Changelog

#6690 Prepare stable modules for version v1.0.0-rc1
  cmd/otelcorecol/go.mod
  component/go.mod
  consumer/go.mod
  exporter/loggingexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/ballastextension/go.mod
  extension/zpagesextension/go.mod
  go.mod
  processor/batchprocessor/go.mod
  processor/memorylimiterprocessor/go.mod
  receiver/otlpreceiver/go.mod
  versions.yaml
Labels: Skip Changelog

#6697 [chore] fix unintended public type settings when moved pipelines
  service/pipelines.go
  service/pipelines_test.go
  service/service.go
Labels: release:blocker

#6707 Mark as deprecated componenttest exporter related funcs
  .chloggen/deprecatecompexp.yaml
  component/componenttest/nop_exporter.go
  exporter/exporterhelper/common_test.go
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/traces_test.go
  exporter/exportertest/nop_exporter.go
  exporter/exportertest/nop_exporter_test.go
  exporter/loggingexporter/factory_test.go
  exporter/loggingexporter/logging_exporter_test.go
  exporter/otlpexporter/factory_test.go
  exporter/otlpexporter/otlp_test.go
  exporter/otlphttpexporter/factory_test.go
  exporter/otlphttpexporter/otlp_test.go
  obsreport/obsreporttest/obsreporttest.go
  otelcol/config_provider_test.go
  service/internal/configunmarshaler/exporters_test.go
  service/pipelines_test.go
Labels: Skip Changelog

#6685 Fix some pipeline tests and validate error messages
  service/pipelines_test.go
Labels: Skip Changelog

#6762 Add example connector to service/internal/testcomponents
  service/internal/testcomponents/example_connector.go
  service/internal/testcomponents/example_connector_test.go
Labels: Skip Changelog

#6773 Fix typo in configtls README.md
  config/configtls/README.md
Labels: Skip Changelog

#6795 [receiver/otlpreceiver] Fix README
  receiver/otlpreceiver/README.md
Labels: Skip Changelog

#6838 [docs] Update release schedule
  docs/release.md
Labels: area:documentation, Skip Changelog
