Repository open-telemetry/opentelemetry-collector, pull requests merged in 2022-10, with the labels that each got.

#6212 [docs/security] Add note about CWE-1327
  docs/security.md
Labels: Skip Changelog

#6227 [chore] more localhost configuration
  service/testdata/otelcol-invalid.yaml
  service/testdata/otelcol-invalidprop.yaml
  service/testdata/otelcol-nop.yaml
  service/testdata/otelcol-validprop.yaml
Labels: Skip Changelog

#6133 Move internal/testcomponents to service/internal/testcomponents, reduce scope
  service/internal/pipelines/pipelines_test.go
  service/internal/testcomponents/example_exporter.go
  service/internal/testcomponents/example_exporter_test.go
  service/internal/testcomponents/example_factories.go
  service/internal/testcomponents/example_processor.go
  service/internal/testcomponents/example_processor_test.go
  service/internal/testcomponents/example_receiver.go
  service/internal/testcomponents/example_receiver_test.go
Labels: Skip Changelog

#6117 Change AggregationTemporality.String to simpler, easier to read
  CHANGELOG.md
  pdata/pmetric/metrics.go
  pdata/pmetric/metrics_test.go
Labels: Stale

#6237 Add crosslink tool
  .github/workflows/build-and-test.yml
  CONTRIBUTING.md
  Makefile
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: Skip Changelog

#6248 Bump go tools to v0.1.0
  internal/tools/go.mod
  internal/tools/go.sum
Labels: dependencies

#6260 [chore] Remove unused wrappers for MetricDataPointFlags
  pdata/internal/wrapper_metrics.go
Labels: Skip Changelog

#6268 Disallow dollar sign in opaque value, allow recursive expansion to be implemented in the future
  confmap/README.md
  confmap/resolver.go
  confmap/resolver_test.go
Labels: Skip Changelog

#6277 Remove unused internal code, a new meachanism to embed external configs was added
  config/internal/configsource/README.md
  config/internal/configsource/doc.go
  config/internal/configsource/manager.go
  config/internal/configsource/manager_test.go
  config/internal/configsource/testdata/arrays_and_maps.yaml
  config/internal/configsource/testdata/arrays_and_maps_expected.yaml
  config/internal/configsource/testdata/envvar_cfgsrc_mix.yaml
  config/internal/configsource/testdata/envvar_cfgsrc_mix_expected.yaml
  config/internal/configsource/testdata/params_handling.yaml
  config/internal/configsource/testdata/params_handling_expected.yaml
  config/internal/configsource/testdata/yaml_injection.yaml
  config/internal/configsource/testdata/yaml_injection_expected.yaml
  go.mod
  go.sum
Labels: Skip Changelog

#6280 [changelog] Update list of the recent deprecations
  CHANGELOG.md
Labels: Skip Changelog

#6283 [pdata] Simplify pdatagen to rely more on the proto naming dependency
  pdata/internal/cmd/pdatagen/internal/base_fields.go
  pdata/internal/cmd/pdatagen/internal/common_structs.go
  pdata/internal/cmd/pdatagen/internal/log_structs.go
  pdata/internal/cmd/pdatagen/internal/metrics_structs.go
  pdata/internal/cmd/pdatagen/internal/resource_structs.go
  pdata/internal/cmd/pdatagen/internal/trace_structs.go
Labels: Skip Changelog

#6293 upgrade otel go to latest version v1.11.0/v0.32.3/v0.36.3
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: dependencies

#6305 [pdata] Clarify CopyTo and MoveTo behavior in godoc.
  pdata/internal/cmd/pdatagen/internal/base_slices.go
  pdata/internal/cmd/pdatagen/internal/base_structs.go
  pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
  pdata/pcommon/common.go
  pdata/pcommon/generated_common.go
  pdata/pcommon/generated_primitive_slice.go
  pdata/pcommon/generated_resource.go
  pdata/pcommon/trace_state.go
  pdata/plog/generated_logs.go
  pdata/plog/logs.go
  pdata/pmetric/generated_metrics.go
  pdata/pmetric/metrics.go
  pdata/ptrace/generated_traces.go
  pdata/ptrace/traces.go
Labels: Skip Changelog

#6313 Merge changes for 0.62.1
  CHANGELOG.md
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/config/default.yaml
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/main.go
  confmap/resolver.go
  confmap/resolver_test.go
  examples/k8s/otel-config.yaml
  go.mod
  service/config_provider_test.go
  versions.yaml
Labels: Skip Changelog

#6302 [docs] rename security doc
  README.md
  docs/security-best-practices.md
Labels: Skip Changelog

#6333 [Makefile] Add `.yaml` to changelog filename for `chlog-new`
  Makefile
Labels: Skip Changelog

#6255 [pdata] Add documentation defining naming conventions
  pdata/README.md
Labels: Skip Changelog

#6364 Change to non-nullable PartialSuccess
  pdata/internal/data/protogen/collector/logs/v1/logs_service.pb.go
  pdata/internal/data/protogen/collector/metrics/v1/metrics_service.pb.go
  pdata/internal/data/protogen/collector/trace/v1/trace_service.pb.go
  pdata/plog/internal/plogjson/json.go
  pdata/plog/internal/plogjson/json_test.go
  pdata/pmetric/internal/pmetricjson/json.go
  pdata/pmetric/internal/pmetricjson/json_test.go
  pdata/ptrace/internal/ptracejson/json.go
  pdata/ptrace/internal/ptracejson/json_test.go
  proto_patch.sed
Labels: Skip Changelog

#6284 Remove impossible conditions from Unmarshaler, and validation from Unmarshal
  receiver/otlpreceiver/config.go
  receiver/otlpreceiver/config_test.go
Labels: Skip Changelog

#6359 [docs] update design.md doc
  docs/design.md
Labels: Skip Changelog

#6370 [pdata] Rename p[trace|metric|log]otlp.ExportPartialSuccess
  .chloggen/generatepartialresponse.yaml
  pdata/internal/cmd/pdatagen/internal/base_structs.go
  pdata/internal/cmd/pdatagen/internal/plogotlp_structs.go
  pdata/internal/cmd/pdatagen/internal/pmetricotlp_structs.go
  pdata/internal/cmd/pdatagen/internal/ptraceotlp_structs.go
  pdata/internal/generated_wrapper_logs_otlp.go
  pdata/internal/generated_wrapper_metrics_otlp.go
  pdata/internal/generated_wrapper_traces_otlp.go
  pdata/plog/plogotlp/generated_logs_otlp.go
  pdata/plog/plogotlp/generated_logs_otlp_test.go
  pdata/plog/plogotlp/response.go
  pdata/pmetric/pmetricotlp/generated_metrics_otlp.go
  pdata/pmetric/pmetricotlp/generated_metrics_otlp_test.go
  pdata/pmetric/pmetricotlp/response.go
  pdata/ptrace/ptraceotlp/generated_traces_otlp.go
  pdata/ptrace/ptraceotlp/generated_traces_otlp_test.go
  pdata/ptrace/ptraceotlp/response.go
Labels: Skip Changelog

#6391 [changelog] Update changelog entry for adding partial success fields
  .chloggen/generatepartialresponse.yaml
Labels: Skip Changelog

#6390 Split config unmarshaler per config section
  service/config_provider.go
  service/internal/configunmarshaler/defaultunmarshaler.go
  service/internal/configunmarshaler/defaultunmarshaler_test.go
  service/internal/configunmarshaler/exporters.go
  service/internal/configunmarshaler/exporters_test.go
  service/internal/configunmarshaler/extensions.go
  service/internal/configunmarshaler/extensions_test.go
  service/internal/configunmarshaler/processors.go
  service/internal/configunmarshaler/processors_test.go
  service/internal/configunmarshaler/receivers.go
  service/internal/configunmarshaler/receivers_test.go
  service/internal/configunmarshaler/testdata/duplicate-exporter.yaml
  service/internal/configunmarshaler/testdata/duplicate-extension.yaml
  service/internal/configunmarshaler/testdata/duplicate-processor.yaml
  service/internal/configunmarshaler/testdata/duplicate-receiver.yaml
  service/internal/configunmarshaler/testdata/empty-all-sections.yaml
  service/internal/configunmarshaler/testdata/empty-config.yaml
  service/internal/configunmarshaler/testdata/invalid-exporter-name-after-slash.yaml
  service/internal/configunmarshaler/testdata/invalid-exporter-section.yaml
  service/internal/configunmarshaler/testdata/invalid-exporter-sub-config.yaml
  service/internal/configunmarshaler/testdata/invalid-exporter-type.yaml
  service/internal/configunmarshaler/testdata/invalid-extension-name-after-slash.yaml
  service/internal/configunmarshaler/testdata/invalid-extension-section.yaml
  service/internal/configunmarshaler/testdata/invalid-extension-sub-config.yaml
  service/internal/configunmarshaler/testdata/invalid-extension-type.yaml
  service/internal/configunmarshaler/testdata/invalid-processor-name-after-slash.yaml
  service/internal/configunmarshaler/testdata/invalid-processor-section.yaml
  service/internal/configunmarshaler/testdata/invalid-processor-sub-config.yaml
  service/internal/configunmarshaler/testdata/invalid-processor-type.yaml
  service/internal/configunmarshaler/testdata/invalid-receiver-name-after-slash.yaml
  service/internal/configunmarshaler/testdata/invalid-receiver-section.yaml
  service/internal/configunmarshaler/testdata/invalid-receiver-sub-config.yaml
  service/internal/configunmarshaler/testdata/invalid-receiver-type.yaml
  service/internal/configunmarshaler/testdata/unknown-exporter-type.yaml
  service/internal/configunmarshaler/testdata/unknown-extension-type.yaml
  service/internal/configunmarshaler/testdata/unknown-processor-type.yaml
  service/internal/configunmarshaler/testdata/unknown-receiver-type.yaml
  service/internal/configunmarshaler/testdata/valid-config.yaml
  service/service_test.go
  service/servicetest/configprovider.go
  service/servicetest/configprovider_test.go
Labels: Skip Changelog

#6324 [test] fix flaky telemetry zpages test
  service/collector_test.go
Labels: Skip Changelog

#6393 Avoid using deprecated config.Config in servicetest
  service/collector.go
  service/collector_test.go
  service/config_provider.go
  service/config_provider_test.go
  service/internal/pipelines/pipelines_test.go
  service/service_test.go
  service/servicetest/configprovider.go
Labels: Skip Changelog

#6405 Revert "[config{grpc,http}] Add warning when using unspecified address (#6267)"
  .chloggen/mx-psi_add-logging-0.0.0.0.yaml
  config/configgrpc/configgrpc.go
  config/configgrpc/configgrpc_test.go
  config/confighttp/confighttp.go
  config/confighttp/confighttp_test.go
  config/internal/warning.go
  config/internal/warning_test.go
Labels: Skip Changelog

#6371 Add tests to the obsreport.Receiver component helper when using otel instrumentation
  obsreport/obsreport_receiver.go
  obsreport/obsreport_test.go
  obsreport/obsreporttest/obsreporttest.go
  obsreport/obsreporttest/otelprometheuschecker.go
  obsreport/obsreporttest/otelprometheuschecker_test.go
Labels: Skip Changelog

#6412 Bump dependency for tools to v0.2.0
  internal/tools/go.mod
  internal/tools/go.sum
Labels: dependencies

#6424 [docs] update roadmap document
  docs/roadmap.md
Labels: Skip Changelog
