Repository open-telemetry/opentelemetry-collector, pull requests merged in 2022-02, with the labels that each got.

#4778 Update all deps on 01/31/2022
  cmd/builder/internal/builder/main.go
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/go.sum
  model/go.mod
  model/go.sum
Labels: Skip Changelog

#4780 Replace usage of path.Join with filepath.Join, better windows support
  config/configmap_test.go
  config/configmapprovider/env_test.go
  config/configmapprovider/expand_test.go
  config/configmapprovider/file.go
  config/configtls/configtls_test.go
  config/internal/configsource/manager_test.go
  exporter/otlpexporter/factory_test.go
  exporter/otlpexporter/otlp_test.go
  exporter/otlphttpexporter/factory_test.go
  internal/cgroups/cgroups.go
  service/collector_test.go
  service/collector_windows_test.go
  service/config_provider_test.go
  service/internal/builder/exporters_builder_test.go
  service/internal/builder/pipelines_builder_test.go
  service/internal/builder/receivers_builder_test.go
  service/servicetest/configprovider_test.go
Labels: Skip Changelog

#4771 Update builder integration tests, enable daily/manual builds
  .github/workflows/builder-integration-test.yaml
  cmd/builder/test/core.builder.yaml
  cmd/builder/test/replaces.builder.yaml
Labels: Skip Changelog

#4784 [pdata] Update Metric Sum and Gauge structs comments
  model/internal/cmd/pdatagen/internal/metrics_structs.go
  model/pdata/generated_metrics.go
Labels: Skip Changelog

#4785 [pdatage] Update numeric value struct names
  model/internal/cmd/pdatagen/internal/metrics_structs.go
Labels: Skip Changelog

#4790 Mark some roadmap items as done
  docs/roadmap.md
Labels: Skip Changelog

#4712 Add guidelines for breaking changes
  CONTRIBUTING.md
Labels: Skip Changelog

#4773 [pdatagen] Generate oneOf field
  model/internal/cmd/pdatagen/internal/base_fields.go
  model/internal/cmd/pdatagen/internal/metrics_structs.go
  model/pdata/generated_metrics.go
  model/pdata/generated_metrics_test.go
  model/pdata/metrics.go
  model/pdata/metrics_test.go
Labels: Skip Changelog

#4791 Fix build broken due to merge conflict
  model/internal/cmd/pdatagen/internal/metrics_structs.go
Labels: Skip Changelog

#4792 [pdatagen] Remove deprecated field from messageValueStruct
  model/internal/cmd/pdatagen/internal/base_structs.go
  model/pdata/generated_common.go
  model/pdata/generated_log.go
  model/pdata/generated_metrics.go
  model/pdata/generated_resource.go
  model/pdata/generated_trace.go
Labels: Skip Changelog

#4797 don't run changelog check if pr comes from dependabot
  .github/workflows/changelog.yml
Labels: Skip Changelog

#4801 [pdatagen] Nit: correct anonymous func signature
  model/internal/cmd/pdatagen/internal/base_slices.go
Labels: Skip Changelog

#4802 Small improvements in componenttest
  component/componenttest/nop_component.go
  component/componenttest/nop_exporter.go
  component/componenttest/nop_extension.go
  component/componenttest/nop_processor.go
  component/componenttest/nop_receiver.go
Labels: Skip Changelog

#4622 Deprecate service/defaultcomponents go package
  CHANGELOG.md
  service/defaultcomponents/defaults.go
Labels: Stale

#4816 [cicd] disable mott the tidier
  .github/workflows/dependabot.yml
Labels: Skip Changelog

#4810 Use go mod compat, drops support for reproducibility with go 1.16
  Makefile
  cmd/builder/go.mod
  cmd/builder/go.sum
  cmd/otelcorecol/go.sum
  go.sum
  model/go.mod
  model/go.sum
Labels: Skip Changelog

#4807 adding missing expo histo test
  model/pdata/metrics_test.go
Labels: Skip Changelog

#4811 [pdatagen] Generate Metric type accessors
  model/internal/cmd/pdatagen/internal/base_fields.go
  model/pdata/generated_metrics.go
  model/pdata/generated_metrics_test.go
  model/pdata/metrics.go
  model/pdata/metrics_test.go
Labels: Skip Changelog

#4799 Freakynoblegas/reject invalid queue size exporterhelper
  exporter/exporterhelper/queued_retry_experimental.go
  exporter/exporterhelper/queued_retry_inmemory.go
  exporter/exporterhelper/queued_retry_test.go
  exporter/otlpexporter/config.go
Labels: Skip Changelog

#4823 Remove reference to 'new-metrics' flag in docs
  docs/monitoring.md
Labels: Skip Changelog

#4822 Update Contributing guideline to include version in deprecation notice
  CONTRIBUTING.md
  config/configmapprovider/provider.go
  config/configmapprovider/retrieved.go
  model/pdata/logs.go
  service/config_provider.go
  service/defaultcomponents/defaults.go
Labels: Skip Changelog

#4830 Mark more parts as stable
  README.md
Labels: Skip Changelog

#4828 Bump github.com/shirou/gopsutil/v3 from 3.21.12 to 3.22.1
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: dependencies

#4844 Remove unused code from internal/testdata
  internal/testdata/log.go
  internal/testdata/metric.go
  internal/testdata/trace.go
Labels: Skip Changelog

#4847 Fix typo in OTLP text
  internal/otlptext/logs.go
  internal/otlptext/traces.go
Labels: Skip Changelog

#4848 nit: fix small comment inconsistency in genotelcorecol check
  .github/workflows/build-and-test.yml
Labels: Skip Changelog

#4846 builder: bump otelColVersion version to 0.44.0
  cmd/builder/internal/builder/config.go
  cmd/builder/test/core.builder.yaml
  cmd/builder/test/replaces.builder.yaml
Labels: Skip Changelog

#4862 dependabot updates Mon 14 Feb 2022 08:30:52 PST
  cmd/builder/go.sum
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
  service/telemetry.go
Labels: Skip Changelog

#4864 Update status to be reported by GA not by circle CI
  README.md
Labels: Skip Changelog

#4880 Add tests for expandNilStructPointersFunc, left TODO to investigate
  config/configmap_test.go
Labels: Skip Changelog

#4845 Fix small nits in testutil, handle errors, initialize slices
  internal/testutil/testutil.go
  internal/testutil/testutil_test.go
Labels: Skip Changelog

#4892 make gotidy
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: Skip Changelog

#4900 Dependabot updates, Monday Feb 21
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: dependencies, Skip Changelog

#4888 Create a new github job, extract all non lint checks
  .github/workflows/build-and-test.yml
  Makefile
  Makefile.Common
Labels: Skip Changelog

#4904 Add tests for component.Factories constructor helpers
  component/factories_test.go
Labels: Skip Changelog

#4905 Upgrade to github.com/klauspost/compress v1.14.4
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: dependencies, Skip Changelog

#4881 Improve release doc
  Makefile
  docs/release.md
Labels: Skip Changelog

#4908 Tune Makefile, allow running targets in parallel across modules
  Makefile
  Makefile.Common
Labels: Skip Changelog

#4757 Replace viper with koanf in builder
  cmd/builder/go.mod
  cmd/builder/go.sum
  cmd/builder/internal/command.go
Labels: Skip Changelog

#4903 [README] Add section about Go compatibility
  README.md
Labels: Skip Changelog

#4920 Remove use of unnecessary internal interface in factory
  component/component.go
  component/component_test.go
  component/exporter.go
  component/extension.go
  component/processor.go
  component/receiver.go
  internal/internalinterface/internalinterface_test.go
Labels: Skip Changelog

#4921 Fix deprecation notice version for extensionheleper and componenhelper
  component/componenthelper/component.go
  extension/extensionhelper/factory.go
Labels: Skip Changelog

#4787 [Builder]: Remove test that depends on the contrib
  cmd/builder/test/README.md
  cmd/builder/test/replaces.builder.yaml
  cmd/builder/test/replaces.otel.yaml
  cmd/builder/test/test.sh
Labels: Skip Changelog

#4928 Assign release managers to future releases
  docs/release.md
Labels: Skip Changelog
