Repository open-telemetry/opentelemetry-collector, pull requests merged in 2022-04, with the labels that each got.

#5135 Add otel propagators to the grpc client options
  config/configgrpc/configgrpc.go
Labels: Skip Changelog

#5145 Bump all deps to latest
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: dependencies

#5148 [model/semconv] Add `generated_` prefix to generated files
  Makefile
  model/semconv/README.md
  model/semconv/semconv_test.go
  model/semconv/v1.5.0/generated_resource.go
  model/semconv/v1.5.0/generated_trace.go
  model/semconv/v1.6.1/generated_resource.go
  model/semconv/v1.6.1/generated_trace.go
  model/semconv/v1.7.0/generated_resource.go
  model/semconv/v1.7.0/generated_trace.go
  model/semconv/v1.8.0/generated_resource.go
  model/semconv/v1.8.0/generated_trace.go
  model/semconv/v1.9.0/generated_resource.go
  model/semconv/v1.9.0/generated_trace.go
Labels: Skip Changelog

#5142 [ci] Cross build for architectures
  .github/workflows/build-and-test.yml
Labels: Skip Changelog

#5150 nit: fix some comments in config
  config/config.go
Labels: Skip Changelog

#5152 Remove dependabot config to upgrade docker
  .github/dependabot.yml
  Makefile
Labels: dependencies

#5162 [pdata] Extract model/internal/pdata package into model/internal
  model/internal/cmd/pdatagen/internal/base_slices.go
  model/internal/cmd/pdatagen/internal/base_structs.go
  model/internal/cmd/pdatagen/internal/files.go
  model/internal/cmd/pdatagen/main.go
  model/internal/common.go
  model/internal/common_test.go
  model/internal/generated_common.go
  model/internal/generated_common_test.go
  model/internal/generated_log.go
  model/internal/generated_log_test.go
  model/internal/generated_metrics.go
  model/internal/generated_metrics_test.go
  model/internal/generated_resource.go
  model/internal/generated_resource_test.go
  model/internal/generated_trace.go
  model/internal/generated_trace_test.go
  model/internal/logs.go
  model/internal/logs_test.go
  model/internal/metrics.go
  model/internal/metrics_test.go
  model/internal/otlp_wrapper.go
  model/internal/spanid.go
  model/internal/spanid_test.go
  model/internal/timestamp.go
  model/internal/timestamp_test.go
  model/internal/traceid.go
  model/internal/traceid_test.go
  model/internal/traces.go
  model/internal/traces_test.go
  model/otlp/json_marshaler.go
  model/otlp/json_unmarshaler.go
  model/otlp/pb_marshaler.go
  model/otlp/pb_unmarshaler.go
  model/otlpgrpc/logs.go
  model/otlpgrpc/logs_test.go
  model/otlpgrpc/metrics.go
  model/otlpgrpc/traces.go
  model/pdata/common_alias.go
  model/pdata/doc.go
  model/pdata/generated_common_alias.go
  model/pdata/generated_log_alias.go
  model/pdata/generated_metrics_alias.go
  model/pdata/generated_resource_alias.go
  model/pdata/generated_trace_alias.go
  model/pdata/logs_alias.go
  model/pdata/metrics_alias.go
  model/pdata/spanid_alias.go
  model/pdata/timestamp_alias.go
  model/pdata/traceid_alias.go
  model/pdata/traces_alias.go
Labels: Skip Changelog

#5070 doc: add document for HTTP Header
  config/confighttp/README.md
Labels: Skip Changelog

#5180 Dependabot updates, 04/11/2022
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: dependencies

#5182 Small nits in config.Map, avoid unnecessary deps
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  config/configmap.go
Labels: Skip Changelog

#5185 Followup after #4936, remove some duplicate code
  service/collector_test.go
  service/collector_windows.go
  service/command.go
  service/config_provider.go
  service/config_provider_test.go
Labels: Skip Changelog

#5186 reverted link check action to 1.0.13
  .github/workflows/check-links.yaml
Labels: Skip Changelog

#5184 Remove unnecessary dependency on gorrila mux
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
  receiver/otlpreceiver/otlp.go
Labels: Skip Changelog

#5191 Remove unnecessary aliases for Marshaler/Unmarshaler/Sizer in pdata
  pdata/internal/logs.go
  pdata/internal/metrics.go
  pdata/internal/traces.go
  pdata/plog/alias.go
  pdata/plog/encoding.go
  pdata/pmetric/alias.go
  pdata/pmetric/encoding.go
  pdata/ptrace/alias.go
  pdata/ptrace/encoding.go
Labels: Skip Changelog

#5192 Small nits in struct comments in otlp package
  pdata/plog/plogotlp/logs.go
  pdata/pmetric/pmetricotlp/metrics.go
  pdata/ptrace/ptraceotlp/traces.go
Labels: Skip Changelog

#5193 Bump go.opentelemetry.io/otel/metric to 0.29.0
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: Skip Changelog

#5199 Fix check links errors, use latest version of the tool
  .github/workflows/check-links.yaml
  CONTRIBUTING.md
Labels: Skip Changelog

#5181 Small nits in bounded memory, unnecessary atomics and pointers
  exporter/exporterhelper/internal/bounded_memory_queue.go
Labels: Skip Changelog

#5215 Use `go.uber.org/atomic` everywhere
  .golangci.yml
  exporter/exporterhelper/internal/bounded_memory_queue_test.go
  exporter/exporterhelper/internal/persistent_queue_test.go
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/queued_retry_test.go
  exporter/otlpexporter/otlp_test.go
  internal/obsreportconfig/obsreportconfig.go
  processor/memorylimiterprocessor/memorylimiter.go
  processor/memorylimiterprocessor/memorylimiter_test.go
  service/collector.go
Labels: Skip Changelog

#5218 Use atomic.Bool when int was used as a bool variable
  exporter/exporterhelper/internal/bounded_memory_queue.go
  exporter/exporterhelper/internal/bounded_memory_queue_test.go
  processor/memorylimiterprocessor/memorylimiter.go
  processor/memorylimiterprocessor/memorylimiter_test.go
Labels: Skip Changelog

#5224 [pdata] Fix InstrumentationScope godoc string
  pdata/internal/cmd/pdatagen/internal/common_structs.go
  pdata/internal/generated_common.go
Labels: Skip Changelog

#5222 [docs] fix headings in godoc
  component/receiver.go
Labels: Skip Changelog

#5226 Update pdata godoc strings
  pdata/internal/cmd/pdatagen/internal/base_slices.go
  pdata/internal/cmd/pdatagen/internal/base_structs.go
  pdata/internal/cmd/pdatagen/internal/files.go
  pdata/internal/cmd/pdatagen/main.go
  pdata/internal/common.go
  pdata/internal/logs.go
  pdata/internal/metrics.go
  pdata/internal/spanid.go
  pdata/internal/traceid.go
  pdata/internal/traces.go
  pdata/pcommon/alias.go
  pdata/pcommon/generated_common_alias.go
  pdata/pcommon/generated_resource_alias.go
  pdata/pcommon/spanid_alias.go
  pdata/pcommon/timestamp_alias.go
  pdata/pcommon/traceid_alias.go
  pdata/plog/alias.go
  pdata/plog/generated_alias.go
  pdata/pmetric/alias.go
  pdata/pmetric/generated_alias.go
  pdata/ptrace/alias.go
  pdata/ptrace/generated_alias.go
Labels: Skip Changelog

#5221 Update release instructions
  docs/release.md
Labels: Skip Changelog

#5229 Remove duplicate code between configtest and expand_test
  config/mapconverter/expandmapconverter/expand_test.go
Labels: Skip Changelog

#5147 [exporter/otlp] Retry RESOURCE_EXHAUSTED only if the server returns RetryInfo
  CHANGELOG.md
  exporter/otlpexporter/otlp.go
  exporter/otlpexporter/otlp_test.go
Labels: ready-to-merge

#5236 [receiver/otlp] Add tests for YAML edge cases
  receiver/otlpreceiver/config_test.go
  receiver/otlpreceiver/testdata/config.yaml
Labels: Skip Changelog

#5243 Add version to the deprecated message
  config/mapprovider.go
Labels: Skip Changelog

#5245 Fix nil pointer exception in service.NewConfigProvider
  service/config_provider.go
  service/config_provider_test.go
Labels: Skip Changelog

#5256 Remove usage of unnecessary omitempty
  config/configgrpc/configgrpc.go
  config/confighttp/confighttp.go
  processor/batchprocessor/config.go
Labels: Skip Changelog

#5262 Fix typo in extensions.go
  service/internal/extensions/extensions.go
Labels: Skip Changelog

#5265 Refactor collector tests, improve names, localize functionality tests
  service/collector_test.go
Labels: Skip Changelog

#5274 cleanup exporterhelper readme
  exporter/exporterhelper/README.md
Labels: Skip Changelog

#5275 Remove GetAvailablePort, change GetAvailableLocalAddress to handle windows reserved ports
  internal/testutil/testutil.go
  internal/testutil/testutil_test.go
Labels: Skip Changelog

#5276 Try to clarify the suggestion in the export failures when retry_on_failure is disabled
  exporter/exporterhelper/queued_retry.go
Labels: Skip Changelog

#5272 [bugfix] temporary fix around grpclogger
  service/collector.go
  service/settings.go
Labels: Skip Changelog

#5289 [docs] update to release documentation
  docs/release.md
Labels: Skip Changelog

#5273 Address feedback about existing code from 5248
  service/mapresolver.go
  service/mapresolver_test.go
Labels: Skip Changelog

#5290 Upgrade otel deps to latest
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: dependencies

#5292 [service] Split `component.Host` functionality into separate `serviceHost` struct
  service/collector_test.go
  service/host.go
  service/service.go
  service/service_test.go
  service/telemetry.go
  service/zpages.go
Labels: Skip Changelog
