Repository open-telemetry/opentelemetry-collector, pull requests merged in 2022-09, with the labels that each got.

#6011 Update Release Manager schedule
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests

#5989 Fix lint error due to the usage of deprecated method
  service/internal/telemetry/process_telemetry.go
Labels: Skip Changelog

#6036 Remove duplicate tests, already covered in internal/json/resource_test
  pdata/pmetric/json_test.go
  pdata/ptrace/json_test.go
Labels: Skip Changelog

#6038 Correctly skip unkown value types
  CHANGELOG.md
  pdata/internal/json/attribute.go
  pdata/internal/json/attribute_test.go
  pdata/plog/json.go
Labels: bug

#6042 Fix failing unmarshalerHookFunc
  confmap/confmap.go
Labels: Skip Changelog

#6043 [pdata] Use copy instead of manual copying slices.
  pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
  pdata/pcommon/generated_primitive_slice.go
Labels: Skip Changelog

#6047 [chore] Update service readme with HTTP provider
  service/README.md
Labels: Skip Changelog

#5949 builder: move config module validation during Validate
  cmd/builder/go.mod
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/builder/config_test.go
Labels: Skip Changelog

#6049 [Makefile] Clean up check-contrib target
  .github/workflows/contrib-tests.yml
  Makefile
Labels: Skip Changelog

#6066 [changelog] Cleanup uncategorized items
  CHANGELOG.md
Labels: Skip Changelog

#6064 [pdata] Rename Map.Upsert* methods to Map.Put*
  CHANGELOG.md
  exporter/exporterhelper/internal/persistent_queue_test.go
  exporter/loggingexporter/internal/otlptext/databuffer_test.go
  exporter/otlphttpexporter/otlp_test.go
  internal/testdata/common.go
  internal/testdata/log.go
  pdata/pcommon/common.go
  pdata/pcommon/common_test.go
  pdata/plog/json_test.go
  pdata/pmetric/json_test.go
  pdata/pmetric/metrics_test.go
  pdata/ptrace/json_test.go
  receiver/otlpreceiver/otlp_test.go
Labels: release:blocker

#6079 Prepare collector-core for version v0.60.0
  cmd/otelcorecol/go.mod
  go.mod
Labels: Skip Changelog

#6088 Remove deprecated funcs from pcommon.[Map|Value|Slice]
  CHANGELOG.md
  pdata/pcommon/common.go
  pdata/pcommon/common_test.go
Labels: Skip Changelog

#6104 [docs] Remove link to itself
  config/configtls/README.md
Labels: Skip Changelog

#6103 [docs] Update release rotation
  docs/release.md
Labels: Skip Changelog

#6068 [docs] Update release instructions
  docs/release.md
Labels: Skip Changelog

#6101 Add log severity number to logging exporter
  exporter/loggingexporter/internal/otlptext/logs.go
Labels: Skip Changelog

#6116 docs(featuregate): fix code example
  featuregate/README.md
Labels: Skip Changelog

#6118 Fix github dependabot-pr workflow
  .github/workflows/scripts/dependabot-pr.sh
Labels: Skip Changelog

#6126 Upgrdate to latest otel metrics api/sdk
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
  service/telemetry.go
Labels: dependencies

#6143 Bump to otelgo metrics v0.32.1
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: Skip Changelog

#6139 [docs] rename query language to tranformation language
  docs/processing.md
Labels: Skip Changelog

#6150 [pdata] Add more documentation to primitive slice methods
  pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
  pdata/pcommon/generated_primitive_slice.go
Labels: Skip Changelog

#6159 [pdata] Add comment to to Value.SetStr about its naming.
  pdata/pcommon/common.go
Labels: Skip Changelog

#6160 [chore] Add language to CONTRIBUTING re: pre-release spec features
  CONTRIBUTING.md
Labels: Skip Changelog, Skip Contrib Tests

#6170 Remove usages of deprecated pdata Clone methods
  exporter/otlpexporter/otlp_test.go
  pdata/pmetric/pmetricotlp/metrics.go
  processor/batchprocessor/batch_processor_test.go
  processor/batchprocessor/splitlogs_test.go
  processor/batchprocessor/splitmetrics_test.go
  processor/batchprocessor/splittraces_test.go
  receiver/otlpreceiver/internal/logs/otlp_test.go
  receiver/otlpreceiver/internal/metrics/otlp_test.go
  receiver/otlpreceiver/internal/trace/otlp_test.go
  service/internal/fanoutconsumer/logs.go
  service/internal/fanoutconsumer/metrics.go
  service/internal/fanoutconsumer/traces.go
Labels: Skip Changelog

#6206 [pdata] Update deprecation comments
  pdata/pcommon/common.go
Labels: Skip Changelog, area:pdata
