Repository open-telemetry/opentelemetry-collector, pull requests merged in 2022-03, with the labels that each got.

#4932 Try to add all previous triagers/approvers/maintainers as emeritus
  README.md
Labels: Skip Changelog

#4931 Fix small nits in pdata tests, add missing compatibility tests
  model/pdata/logs_test.go
  model/pdata/metrics_test.go
  model/pdata/traces_test.go
Labels: Skip Changelog

#4925 Reword exceptions section to be more general
  CONTRIBUTING.md
Labels: Skip Changelog

#4935 Bump github.com/magiconair/properties to v1.8.6
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: dependencies, Skip Changelog

#4930 Add MoveTo all the top pdata structs, consistency with other generated structs
  model/pdata/logs.go
  model/pdata/logs_test.go
  model/pdata/metrics.go
  model/pdata/metrics_test.go
  model/pdata/traces.go
  model/pdata/traces_test.go
Labels: Skip Changelog

#4938 Implement Stringer for service.State
  service/collector.go
  service/collector_test.go
Labels: Skip Changelog

#4949 Update release calendar
  docs/release.md
Labels: Skip Changelog

#4948 Small improvements in collector tests, and atomic usage
  service/collector.go
  service/collector_test.go
Labels: Skip Changelog

#4833 Move pdata into an internal package and use aliases in exported package
  model/internal/cmd/pdatagen/internal/base_slices.go
  model/internal/cmd/pdatagen/internal/base_structs.go
  model/internal/cmd/pdatagen/internal/files.go
  model/internal/cmd/pdatagen/main.go
  model/internal/pdata/common.go
  model/internal/pdata/common_test.go
  model/internal/pdata/doc.go
  model/internal/pdata/generated_common.go
  model/internal/pdata/generated_common_test.go
  model/internal/pdata/generated_log.go
  model/internal/pdata/generated_log_test.go
  model/internal/pdata/generated_metrics.go
  model/internal/pdata/generated_metrics_test.go
  model/internal/pdata/generated_resource.go
  model/internal/pdata/generated_resource_test.go
  model/internal/pdata/generated_trace.go
  model/internal/pdata/generated_trace_test.go
  model/internal/pdata/logs.go
  model/internal/pdata/logs_test.go
  model/internal/pdata/metrics.go
  model/internal/pdata/metrics_test.go
  model/internal/pdata/spanid.go
  model/internal/pdata/spanid_test.go
  model/internal/pdata/timestamp.go
  model/internal/pdata/timestamp_test.go
  model/internal/pdata/traceid.go
  model/internal/pdata/traceid_test.go
  model/internal/pdata/traces.go
  model/internal/pdata/traces_test.go
  model/pdata/common_alias.go
  model/pdata/generated_common_alias.go
  model/pdata/generated_log_alias.go
  model/pdata/generated_metrics_alias.go
  model/pdata/generated_resource_alias.go
  model/pdata/generated_trace_alias.go
  model/pdata/logs_alias.go
  model/pdata/metrics_alias.go
  model/pdata/spanid_alias.go
  model/pdata/timestamp_alias.go
  model/pdata/traceid_alias.go
  model/pdata/traces_alias.go
Labels: ready-to-merge, Skip Changelog

#4956 nit: fix small comment in pdata
  model/pdata/traceid_alias.go
Labels: Skip Changelog

#4966 [service/featuregate] Add test for multiple namespaced gates with `+` in flags
  service/featuregate/flags_test.go
Labels: Skip Changelog

#4975 dependabot updates Tue 8 Mar 2022 11:18:13 PST
  cmd/builder/go.mod
  cmd/builder/go.sum
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: Skip Changelog

#4955 [release process] add release template
  .github/ISSUE_TEMPLATE/release.md
Labels: Skip Changelog

#4940 Refactor some new factory func under component/componenttest
  component/componenttest/nop_exporter.go
  component/componenttest/nop_extension.go
  component/componenttest/nop_host.go
  component/componenttest/nop_processor.go
  component/componenttest/nop_receiver.go
  service/service_test.go
Labels: Skip Changelog

#4997 dependabot updates Mon Mar 14 08:56:33 PDT 2022
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/go.sum
  model/go.mod
  model/go.sum
Labels: Skip Changelog

#4999 Fix nit in convertor commnent
  config/configmapprovider/properties.go
Labels: Skip Changelog

#5005 Remove passed dates from GA roadmap
  docs/ga-roadmap.md
Labels: Skip Changelog

#4926 [docs] Update troubleshooting arguments
  docs/troubleshooting.md
Labels: Stale, Skip Changelog

#5016 [docs] Update README
  README.md
Labels: Skip Changelog

#5023 [pdata] Update deprecation comments
  model/pdata/common_alias.go
Labels: Skip Changelog

#5037 Run unit tests on go 1.18 in addition to 1.17
  .github/workflows/build-and-test.yml
Labels: Skip Changelog

#5052 Fix comment for service.NewCommand
  service/command.go
Labels: Skip Changelog

#5029 Fix small nit in configmap provider interface comment
  config/configmapprovider/provider.go
Labels: Skip Changelog

#5033 Add definition for release manager
  README.md
  docs/release.md
Labels: Skip Changelog

#5055 Add release step to update examples/k8s/otel-config.yaml
  docs/release.md
Labels: Skip Changelog

#5057 dependabot updates Mon Mar 21 15:02 PDT 2022
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
  internal/tools/go.sum
  model/go.mod
  model/go.sum
Labels: Skip Changelog

#5058 Change parameter 'location' to a more relevant name
  config/mapprovider.go
  config/mapprovider/envmapprovider/mapprovider.go
  config/mapprovider/filemapprovider/mapprovider.go
  config/mapprovider/yamlmapprovider/mapprovider.go
Labels: Skip Changelog

#5078 Simplify UnmarshalJSON implementation
  model/otlpgrpc/logs.go
  model/otlpgrpc/metrics.go
  model/otlpgrpc/traces.go
Labels: Skip Changelog

#5079 Fix JSON serialization tests
  model/otlpgrpc/logs_test.go
  model/otlpgrpc/metrics_test.go
  model/otlpgrpc/traces_test.go
Labels: Skip Changelog

#5081 Add unittests for grpc otlp client/server
  model/otlpgrpc/logs_test.go
  model/otlpgrpc/metrics_test.go
  model/otlpgrpc/traces_test.go
Labels: Skip Changelog

#5082 Simplify UnmarshalProto funcs in otlpgrpc
  model/otlpgrpc/logs.go
  model/otlpgrpc/metrics.go
  model/otlpgrpc/traces.go
Labels: Skip Changelog

#5092 Highlight documentation code blocks accurately
  docs/troubleshooting.md
Labels: Skip Changelog

#5103 Fix Semantic Convention Schema URL definition for 1.5.0 and 1.6.1
  CHANGELOG.md
  model/semconv/v1.5.0/schema.go
  model/semconv/v1.6.1/schema.go
Labels: ready-to-merge

#5105 dependabot updates Mon Mar 28 08:14:19 PDT 2022
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  component/componenttest/nop_telemetry.go
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/go.sum
  model/go.mod
  model/go.sum
  service/collector.go
Labels: Skip Changelog

#5106 Add a test to validate presence of all semconv files
  model/semconv/semconv_test.go
Labels: Skip Changelog

#5111 Fix checksum mismatch in github.com/blizzy78/varnamelen
  internal/tools/go.mod
  internal/tools/go.sum
Labels: Skip Changelog

#5114 Upgrade to latest build tools go.opentelemetry.io/build-tools
  internal/tools/go.mod
  internal/tools/go.sum
Labels: dependencies

#5115 fix bug with nil Sum
  model/internal/cmd/pdatagen/internal/base_fields.go
  model/internal/pdata/generated_metrics.go
  model/internal/pdata/metrics_test.go
Labels: Skip Changelog

#5116 Fix mismatch go.sum between `make gotidy` and `make genotelcorecol`
  cmd/builder/internal/builder/main.go
  cmd/otelcorecol/go.sum
Labels: Skip Changelog

#5128 Prerelease collector base v0.48.0
  cmd/otelcorecol/go.mod
  go.mod
  go.sum
  versions.yaml
Labels: Skip Changelog

#5129 Update builder version number to 0.48.0
  cmd/builder/internal/builder/config.go
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/main.go
  examples/k8s/otel-config.yaml
Labels: Skip Changelog

#5132 Update release.md after 0.48.0 release
  docs/release.md
Labels: Skip Changelog
