Repository open-telemetry/opentelemetry-collector, pull requests merged in 2022-08, with the labels that each got.

#5763 Small fixes in the new StabilityLevel feature
  component/component.go
  component/exporter_test.go
  component/processor_test.go
  component/receiver_test.go
Labels: Skip Changelog

#5786 Restore deprecated funcs still in use in third-party dependencies
  pdata/internal/metrics.go
Labels: Skip Changelog

#5789 Remove unused code in pdata generator
  pdata/internal/cmd/pdatagen/internal/base_fields.go
Labels: Skip Changelog

#5787 Add a new label Skip Contrib Tests that skips contrib tests requirement
  .github/workflows/changelog.yml
  .github/workflows/contrib-tests.yml
Labels: Skip Changelog, Skip Contrib Tests

#5797 Revert "Restore deprecated funcs still in use in third-party dependencies"
  pdata/internal/metrics.go
Labels: Skip Changelog, release:blocker

#5791 add go 1.19 to tests
  .github/workflows/build-and-test.yml
  client/client.go
  component/component.go
  component/receiver.go
  config/configgrpc/testdata/ca.crt
  config/configgrpc/testdata/client.crt
  config/configgrpc/testdata/client.key
  config/configgrpc/testdata/server.crt
  config/configgrpc/testdata/server.key
  config/confighttp/testdata/ca.crt
  config/confighttp/testdata/client.crt
  config/confighttp/testdata/client.key
  config/confighttp/testdata/server.crt
  config/confighttp/testdata/server.key
  config/configtls/testdata/ca-1.crt
  config/configtls/testdata/ca-2.crt
  config/configtls/testdata/client-1.crt
  config/configtls/testdata/client-1.key
  config/configtls/testdata/client-2.crt
  config/configtls/testdata/client-2.key
  config/configtls/testdata/server-1.crt
  config/configtls/testdata/server-1.key
  config/configtls/testdata/server-2.crt
  config/configtls/testdata/server-2.key
  config/internal/configsource/manager.go
  confmap/confmap.go
  confmap/converter/overwritepropertiesconverter/properties.go
  confmap/provider.go
  confmap/provider/fileprovider/provider.go
  confmap/provider/yamlprovider/provider.go
  confmap/resolver.go
  exporter/exporterhelper/common_test.go
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/traces_test.go
  exporter/loggingexporter/known_sync_error_windows.go
  exporter/loggingexporter/logging_exporter_test.go
  extension/experimental/storage/storage.go
  internal/buildscripts/gen-certs.sh
  obsreport/doc.go
  pdata/internal/common.go
  pdata/internal/data/protogen/metrics/v1/metrics.pb.go
  pdata/internal/generated_common.go
  pdata/internal/generated_plog.go
  pdata/internal/generated_pmetric.go
  pdata/internal/generated_ptrace.go
  pdata/internal/otlp/logs.go
  pdata/internal/otlp/metrics.go
  pdata/internal/otlp/traces.go
  pdata/pcommon/alias.go
  pdata/plog/generated_alias.go
  service/config_provider.go
  service/internal/fanoutconsumer/logs.go
  service/internal/fanoutconsumer/metrics.go
  service/internal/fanoutconsumer/traces.go
Labels: Skip Changelog

#5798 Improve pdata test coverage
  pdata/internal/common.go
  pdata/internal/common_test.go
Labels: Skip Changelog

#5812 [chore] Add missing dashes to descriptions of flags
  service/flags.go
Labels: Skip Changelog

#5820 Remove unnecessary internal package, used only in one place
  internal/internalconsumertest/err_or_sink_consumer.go
  receiver/otlpreceiver/otlp_test.go
Labels: Skip Changelog

#5825 Small nit in internal/obsreportconfig
  internal/obsreportconfig/obsreportconfig.go
  internal/obsreportconfig/obsreportconfig_test.go
Labels: Skip Changelog

#5831 Remove global metrics level, use level passed in create settings
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/traces_test.go
  internal/obsreportconfig/obsreportconfig.go
  obsreport/obsreport_exporter.go
  obsreport/obsreport_receiver.go
  obsreport/obsreport_scraper.go
  receiver/otlpreceiver/otlp_test.go
Labels: Skip Changelog

#5838 Use pointer for Retrieved.Close, consistency with all the other funcs
  confmap/provider.go
Labels: Skip Changelog

#5835 Clean up queued retry code after persistent queue merge
  exporter/exporterhelper/queued_retry.go
  exporter/exporterhelper/queued_retry_experimental_test.go
  exporter/exporterhelper/queued_retry_inmemory.go
  exporter/exporterhelper/queued_retry_test.go
Labels: Skip Changelog

#5799 Small nits in pdata
  pdata/internal/common.go
Labels: Skip Changelog

#5837 Fix deprecated message, forgot the version
  obsreport/obsreport_exporter.go
Labels: Skip Changelog

#5836 Remove unnecessary code from persistent queue implementation
  exporter/exporterhelper/internal/bounded_memory_queue.go
  exporter/exporterhelper/internal/persistent_queue.go
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/internal/producer_consumer_queue.go
Labels: Skip Changelog

#5785 Disallow usage of pkg/errors and otlp proto module
  .golangci.yml
Labels: Skip Changelog

#5821 Remove unnecessary slice for only one attribute value
  exporter/exporterhelper/queued_retry.go
Labels: Skip Changelog

#5860 exporterhelper: bounded memory queue, remove unused onDropItem func
  exporter/exporterhelper/internal/bounded_memory_queue.go
  exporter/exporterhelper/internal/bounded_memory_queue_test.go
  exporter/exporterhelper/queued_retry.go
Labels: Skip Changelog

#5841 Unify exporterhelper.request and internal.PersistentRequest
  exporter/exporterhelper/common.go
  exporter/exporterhelper/internal/persistent_queue.go
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/internal/persistent_storage_batch.go
  exporter/exporterhelper/internal/persistent_storage_test.go
  exporter/exporterhelper/internal/request.go
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/queued_retry.go
  exporter/exporterhelper/queued_retry_test.go
  exporter/exporterhelper/traces.go
  exporter/exporterhelper/traces_test.go
Labels: Skip Changelog

#5862 Use internal.Request in the ProducerConsumerQueue, avoid casting
  exporter/exporterhelper/internal/bounded_memory_queue.go
  exporter/exporterhelper/internal/bounded_memory_queue_test.go
  exporter/exporterhelper/internal/persistent_queue.go
  exporter/exporterhelper/internal/persistent_queue_test.go
  exporter/exporterhelper/internal/producer_consumer_queue.go
  exporter/exporterhelper/queued_retry.go
Labels: Skip Changelog

#5863 confmap.Resolver: Remove support for the old way of expanding env vars
  confmap/resolver.go
  confmap/resolver_test.go
  confmap/testdata/expand-with-all-env-with-source.yaml
  confmap/testdata/expand-with-all-env.yaml
  confmap/testdata/expand-with-partial-env.yaml
Labels: Skip Changelog

#5875 Fix build because of a race condition between merged PRs
  confmap/confmaptest/configtest_test.go
  confmap/resolver_test.go
Labels: Skip Changelog

#5869 Remove usage of deprecated ioutil package
  cmd/builder/internal/builder/config.go
  config/configgrpc/configgrpc_test.go
  config/confighttp/compression_test.go
  config/confighttp/confighttp_test.go
  config/configtls/configtls.go
  confmap/confmap_test.go
  confmap/provider/fileprovider/provider.go
  exporter/otlphttpexporter/otlp.go
  exporter/otlphttpexporter/otlp_test.go
  receiver/otlpreceiver/otlp_test.go
  receiver/otlpreceiver/otlphttp.go
Labels: Skip Changelog

#5877 Upgrade to go1.19 all workflows except testing on go1.18
  .github/workflows/api-compatibility.yml
  .github/workflows/build-and-test-windows.yaml
  .github/workflows/build-and-test.yml
  .github/workflows/builder-integration-test.yaml
  .github/workflows/builder-release.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contrib-tests.yml
  confmap/confmaptest/configtest.go
Labels: Skip Changelog

#5822 Use the config pointer as the key for the memorylimiter instances instead of the ID
  processor/memorylimiterprocessor/factory.go
Labels: Skip Changelog

#5892 [chore] fix wrong usage of yaml.v2 instead of yaml.v3
  confmap/confmaptest/configtest.go
Labels: release:blocker

#5908 Fix race condition in otlpexporter tests
  exporter/otlpexporter/otlp_test.go
Labels: Skip Changelog

#5909 Remove unnecessary pointer dereference in pdata
  pdata/internal/cmd/pdatagen/internal/base_fields.go
  pdata/internal/generated_common.go
  pdata/internal/generated_plog.go
  pdata/internal/generated_pmetric.go
  pdata/internal/generated_ptrace.go
  pdata/internal/generated_resource.go
Labels: Skip Changelog

#5910 Add tests for signal closing shutdown
  service/collector.go
  service/collector_test.go
  service/collector_windows.go
Labels: Skip Changelog

#5913 Move log statements to service when possible and cleaner
  service/collector.go
  service/service.go
Labels: Skip Changelog

#5923 Use common json parsing code for attributes
  pdata/ptrace/json.go
  pdata/ptrace/json_test.go
Labels: Skip Changelog

#5932 Fix deprecation version in deprecation message
  component/extension.go
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/traces.go
  processor/processorhelper/logs.go
  processor/processorhelper/metrics.go
  processor/processorhelper/traces.go
Labels: Skip Changelog

#5937 [processor/batch] Removed casts to Sizer interface in batch processor
  processor/batchprocessor/batch_processor.go
  processor/batchprocessor/batch_processor_test.go
Labels: Skip Changelog

#5957 Remove usage of deprecated LogRecord.Flags
  exporter/loggingexporter/internal/otlptext/logs.go
Labels: Skip Changelog

#5954 [chore] Cleanup pdata/internal/common_tests.go
  pdata/pcommon/common_test.go
Labels: Skip Changelog

#5951 Remove unnecessary posflag provider load
  cmd/builder/internal/command.go
Labels: Skip Changelog

#5967 [chore] Remove call of deprecated InsertNull
  pdata/pcommon/common_test.go
Labels: Skip Changelog

#5965 Upgrade zap and opencensus-prometheus
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
Labels: dependencies

#5977 [loggingexporter] Rename labels to attributes
  exporter/loggingexporter/internal/otlptext/databuffer.go
  exporter/loggingexporter/internal/otlptext/logs.go
  exporter/loggingexporter/internal/otlptext/metrics.go
  exporter/loggingexporter/internal/otlptext/traces.go
Labels: Skip Changelog

#5968 [chore] Simplify implementation for trace ids, no public API changes
  pdata/internal/cmd/pdatagen/internal/base_fields.go
  pdata/internal/data/bytesid.go
  pdata/internal/data/spanid.go
  pdata/internal/data/spanid_test.go
  pdata/internal/data/traceid.go
  pdata/internal/data/traceid_test.go
  pdata/internal/wrapper_span_id.go
  pdata/internal/wrapper_trace_id.go
  pdata/pcommon/spanid.go
  pdata/pcommon/spanid_test.go
  pdata/pcommon/traceid.go
  pdata/pcommon/traceid_test.go
  pdata/plog/generated_logs.go
  pdata/plog/generated_logs_test.go
  pdata/pmetric/generated_metrics.go
  pdata/pmetric/generated_metrics_test.go
  pdata/ptrace/generated_traces.go
  pdata/ptrace/generated_traces_test.go
Labels: Skip Changelog

#5987 docs(troubleshooting): put newer versions first
  docs/troubleshooting.md
Labels: Skip Changelog

#5994 [pdata] Update deprecation comment for InsertNull
  pdata/pcommon/common.go
Labels: Skip Changelog

#5995 Revert breaking change to [Trace|Span]ID.HexString()
  pdata/pcommon/spanid.go
  pdata/pcommon/spanid_test.go
  pdata/pcommon/traceid.go
  pdata/pcommon/traceid_test.go
Labels: Skip Changelog

#5996 New immutable type for LogRecordFlags structs
  CHANGELOG.md
  exporter/loggingexporter/internal/otlptext/logs.go
  pdata/internal/cmd/pdatagen/internal/log_structs.go
  pdata/internal/generated_wrapper_logs.go
  pdata/internal/wrapper_logs.go
  pdata/plog/generated_logs.go
  pdata/plog/generated_logs_test.go
  pdata/plog/log_record_flags.go
  pdata/plog/log_record_flags_test.go
  pdata/plog/logs.go
  pdata/plog/logs_test.go
Labels: Skip Contrib Tests

#6001 Add back deprecated funcs/types deleted by mistake.
  pdata/pmetric/metrics.go
Labels: Skip Changelog
