Repository open-telemetry/opentelemetry-collector, pull requests merged in 2023-04, with the labels that each got.

#7476 Clarify non-permanent error handling in receiver/doc.go
  receiver/doc.go
Labels: Skip Changelog, Skip Contrib Tests

#7475 Update release schedule
  docs/release.md
Labels: Skip Changelog

#7529 [chore] fix typo in documentation
  exporter/otlpexporter/config.go
Labels: Skip Changelog, Skip Contrib Tests

#7536 Add note about bugfix releases for security-relates issues
  docs/release.md
Labels: Skip Changelog

#7534 move prometheus init code
  service/telemetry.go
  service/telemetry_test.go
Labels: Skip Changelog

#7424 [docs] Correct the exporter README section on data mutation
  exporter/README.md
Labels: Stale, Skip Changelog

#7545 Clarify checkpointing order for receivers
  receiver/doc.go
Labels: Skip Changelog

#7539 Mark connectors as stable
  .chloggen/connectors-stable.yaml
  otelcol/config_test.go
  otelcol/internal/sharedgate/sharedgate.go
  otelcol/otelcoltest/config_test.go
Labels: area:connector

#7581 Update main with changes from v0.76.1
  CHANGELOG.md
  cmd/builder/go.mod
  cmd/builder/internal/builder/config.go
  cmd/builder/test/core.builder.yaml
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/main.go
  component/go.mod
  confmap/go.mod
  connector/forwardconnector/go.mod
  consumer/go.mod
  examples/k8s/otel-config.yaml
  exporter/go.mod
  exporter/loggingexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/ballastextension/go.mod
  extension/zpagesextension/go.mod
  featuregate/go.mod
  go.mod
  pdata/go.mod
  processor/batchprocessor/go.mod
  processor/memorylimiterprocessor/go.mod
  receiver/go.mod
  receiver/otlpreceiver/go.mod
  semconv/go.mod
  versions.yaml
Labels: Skip Changelog

#7580 [examples] Update k8s example to not use 0.0.0.0
  examples/k8s/otel-config.yaml
Labels: Skip Changelog
