Repository open-telemetry/opentelemetry-collector, pull requests merged in 2023-05, with the labels that each got.

#7588 [chore] update otel-go dep
  cmd/builder/go.mod
  cmd/builder/go.sum
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  component/componenttest/nop_telemetry.go
  component/go.mod
  component/go.sum
  confmap/go.mod
  confmap/go.sum
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  consumer/go.mod
  consumer/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  featuregate/go.mod
  featuregate/go.sum
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/go.sum
  obsreport/obsreport_exporter.go
  obsreport/obsreport_processor.go
  obsreport/obsreport_receiver.go
  obsreport/obsreport_scraper.go
  pdata/go.mod
  pdata/go.sum
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/batchprocessor/metrics.go
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/go.mod
  receiver/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
  semconv/go.mod
  semconv/go.sum
  service/internal/proctelemetry/process_telemetry.go
  service/internal/proctelemetry/process_telemetry_test.go
  service/service.go
  service/telemetry.go
  service/telemetry_test.go
Labels: Skip Contrib Tests

#7633 upgrade core version default to 0.76.1
  cmd/builder/internal/config/default.yaml
Labels: Skip Changelog

#7396 [exporterhelper] Fix persistent storage behaviour with no available space on device
  .chloggen/fix_persistentstorage_disk-full.yaml
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/internal/persistent_storage_test.go
Labels: Stale

#7700 document duration format
  config/configtls/README.md
  exporter/exporterhelper/README.md
Labels: Skip Changelog

#7701 Change JSON unmarshalling to be a func on pdata types
  pdata/internal/json/json.go
  pdata/plog/internal/plogjson/json.go
  pdata/plog/internal/plogjson/json_test.go
  pdata/plog/json.go
  pdata/plog/json_test.go
  pdata/plog/plogotlp/request.go
  pdata/plog/plogotlp/response.go
  pdata/plog/plogotlp/response_test.go
  pdata/pmetric/internal/pmetricjson/json.go
  pdata/pmetric/internal/pmetricjson/json_test.go
  pdata/pmetric/json.go
  pdata/pmetric/json_test.go
  pdata/pmetric/pmetricotlp/request.go
  pdata/pmetric/pmetricotlp/response.go
  pdata/pmetric/pmetricotlp/response_test.go
  pdata/ptrace/internal/ptracejson/json.go
  pdata/ptrace/internal/ptracejson/json_test.go
  pdata/ptrace/json.go
  pdata/ptrace/json_test.go
  pdata/ptrace/ptraceotlp/request.go
  pdata/ptrace/ptraceotlp/response.go
  pdata/ptrace/ptraceotlp/response_test.go
Labels: Skip Changelog

#7717 add benchmark test for multi batch processing
  processor/batchprocessor/batch_processor_test.go
Labels: Skip Changelog

#7766 [chore] mv renovate config & update fork config
  .github/workflows/tidy-dependencies.yml
  renovate.json
Labels: Skip Changelog, Skip Contrib Tests

#7770 Delete unnecessary file test.js
  test.js
Labels: Skip Changelog, Skip Contrib Tests

#7772 [chore] update otel-go deps
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  component/go.mod
  component/go.sum
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  consumer/go.mod
  consumer/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/go.mod
  receiver/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
Labels: Skip Contrib Tests

#7390 Deprecate component.Host.GetExporters
  .chloggen/deprecate-get-exporters.yaml
  component/componenttest/nop_host_test.go
  component/host.go
  service/host.go
  service/internal/graph/graph.go
Labels: ready-to-merge
