Repository open-telemetry/opentelemetry-collector, pull requests merged in 2023-11, with the labels that each got.

#8768 [service/extensions] extension lifecycle order
  .chloggen/extension-lifecycle-order.yaml
  docs/service-extensions.md
  extension/extension.go
  service/extensions/extensions.go
  service/extensions/extensions_test.go
  service/extensions/graph.go
  service/extensions/graph_test.go
Labels: discussion-needed

#8797 add docs on how to use feature gates to enable OTLP export
  docs/observability.md
Labels: area:documentation, Skip Changelog

#8816 Update @codeboten affiliation to reality
  README.md
Labels: Skip Changelog

#8831 Bump golang versions we use to fix vulnerabilities
  .github/workflows/api-compatibility.yml
  .github/workflows/build-and-test-windows.yaml
  .github/workflows/build-and-test.yml
  .github/workflows/builder-integration-test.yaml
  .github/workflows/builder-release.yaml
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contrib-tests.yml
  .github/workflows/create-dependabot-pr.yml
  .github/workflows/perf.yml
  .github/workflows/prepare-release.yml
  .github/workflows/tidy-dependencies.yml
Labels: Skip Changelog

#8838 Rename ProducerConsumerQueue to Queue
  exporter/exporterhelper/common.go
  exporter/exporterhelper/internal/bounded_memory_queue.go
  exporter/exporterhelper/internal/bounded_memory_queue_test.go
  exporter/exporterhelper/internal/mock_storage.go
  exporter/exporterhelper/internal/persistent_queue.go
  exporter/exporterhelper/internal/persistent_queue_test.go
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/internal/persistent_storage_test.go
  exporter/exporterhelper/internal/queue.go
  exporter/exporterhelper/queue_sender.go
  exporter/exporterhelper/queue_sender_test.go
  exporter/exporterhelper/retry_sender.go
  exporter/exporterhelper/retry_sender_test.go
Labels: Skip Changelog

#8841 [chore][exporter/debug] add description of verbosity levels
  exporter/debugexporter/README.md
Labels: area:documentation, Skip Changelog

#8861 Use standard component Start/Shutdown func in exporterhelper
  exporter/exporterhelper/common.go
  exporter/exporterhelper/internal/bounded_memory_queue_test.go
  exporter/exporterhelper/internal/persistent_queue.go
  exporter/exporterhelper/internal/persistent_queue_test.go
  exporter/exporterhelper/internal/queue.go
  exporter/exporterhelper/queue_sender.go
  exporter/exporterhelper/retry_sender.go
Labels: Skip Changelog

#8862 Avoid nil queue in queue_sender, consolidate implementation
  exporter/exporterhelper/common.go
  exporter/exporterhelper/common_test.go
  exporter/exporterhelper/queue_sender.go
  exporter/exporterhelper/queue_sender_test.go
  exporter/exporterhelper/retry_sender.go
  exporter/exporterhelper/retry_sender_test.go
Labels: Skip Changelog

#8856 Update logic to remove element from slice, avoid allocations
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/internal/persistent_storage_test.go
Labels: Skip Changelog

#8875 Remove Queue.IsPersistent, not needed
  exporter/exporterhelper/internal/bounded_memory_queue.go
  exporter/exporterhelper/internal/persistent_queue.go
  exporter/exporterhelper/internal/queue.go
  exporter/exporterhelper/queue_sender.go
Labels: Skip Changelog

#8869 Metric is deprecated in v2 kube-state-metrics. Fixes #8835.
  docs/monitoring.md
Labels: Skip Changelog, Skip Contrib Tests

#8880 Simplify toStorageClient logic, less checks, return faster
  exporter/exporterhelper/internal/persistent_queue.go
Labels: Skip Changelog

#8879 Do not add Logger field queue name, already configured
  exporter/exporterhelper/internal/persistent_queue.go
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/internal/persistent_storage_test.go
Labels: Skip Changelog

#8890 [docs] Remove service-extensions.md
  docs/images/design-service-lifecycle.png
  docs/service-extensions.md
  service/service.go
Labels: Skip Changelog

#8894 [docs] Remove performance.md
  README.md
  docs/performance.md
  docs/troubleshooting.md
Labels: Skip Changelog

#8888 [docs] Remove roadmap.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  docs/roadmap.md
  docs/vision.md
Labels: Skip Changelog

#8896 Change Queue to use generics, removes some unsafe conversions
  exporter/exporterhelper/internal/bounded_memory_queue.go
  exporter/exporterhelper/internal/bounded_memory_queue_test.go
  exporter/exporterhelper/internal/persistent_queue.go
  exporter/exporterhelper/internal/persistent_queue_test.go
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/internal/persistent_storage_test.go
  exporter/exporterhelper/internal/queue.go
  exporter/exporterhelper/internal/request.go
  exporter/exporterhelper/queue_sender.go
  exporter/exporterhelper/retry_sender_test.go
Labels: Skip Changelog

#8913 Update from binary funcs to avoid an extra copy to the byte buffer
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/internal/persistent_storage_test.go
Labels: Skip Changelog

#8846 [exporter/debug] change default verbosity from `normal` to `basic`
  .chloggen/debug-exporter-default-verbosity-basic.yaml
  exporter/debugexporter/README.md
  exporter/debugexporter/factory.go
Labels: exporter/debug

#8935 [docs, .github] Add new issue template for stabilizing a module
  .github/ISSUE_TEMPLATE/stabilization.md
  docs/release.md
Labels: Skip Changelog

#8974 [pdata] Document that Marshalers/Unmarshalers use OTLP/JSON format explicitly
  pdata/plog/json.go
  pdata/pmetric/json.go
  pdata/ptrace/json.go
Labels: Skip Changelog, area:pdata

#8975 Clarify our stance re: release candidates
  .github/ISSUE_TEMPLATE/stabilization.md
  docs/release.md
Labels: Skip Changelog

#8989 bug: fix flaky test TestQueuedRetry_RequeuingEnabled
  exporter/exporterhelper/queue_sender_test.go
Labels: Skip Changelog

#9014 [docs] Document max_request_body_size setting of HTTPServerSettings
  config/confighttp/README.md
Labels: Skip Changelog
