Repository open-telemetry/opentelemetry-collector, pull requests merged in 2023-03, with the labels that each got.

#7268 Remove code path to unused service implementation
  service/graph.go
  service/graph_test.go
  service/host.go
  service/pipelines.go
  service/pipelines_test.go
  service/service.go
  service/service_test.go
Labels: Skip Changelog

#7272 Remove builtPipelines and associated implementation
  service/pipelines.go
  service/pipelines_test.go
Labels: Skip Changelog

#7275 Consolidate zpages constants
  service/pipelines.go
  service/zpages.go
Labels: Skip Changelog

#7220 replacing go.uber.org/atomic by sync/atomic
  .chloggen/use-sync/atomic.yaml
  .golangci.yml
  confmap/resolver_test.go
  exporter/exporterhelper/internal/bounded_memory_queue.go
  exporter/exporterhelper/internal/bounded_memory_queue_test.go
  exporter/exporterhelper/internal/persistent_queue_test.go
  exporter/exporterhelper/internal/persistent_storage.go
  exporter/exporterhelper/queued_retry_test.go
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/otlp_test.go
  featuregate/gate.go
  featuregate/gate_test.go
  featuregate/go.mod
  featuregate/go.sum
  featuregate/registry.go
  go.mod
  otelcol/collector.go
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/memorylimiter.go
  processor/memorylimiterprocessor/memorylimiter_test.go
Labels: Skip Contrib Tests

#7322 Manually update some of the dependencies without breaking changes
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  component/go.mod
  component/go.sum
  confmap/go.mod
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  consumer/go.mod
  consumer/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/go.mod
  receiver/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
Labels: dependencies, Skip Changelog

#7324 [chore] Update otel go deps and resolve breaking changes
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  component/go.mod
  component/go.sum
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  obsreport/obsreport_exporter.go
  obsreport/obsreport_processor.go
  obsreport/obsreport_receiver.go
  obsreport/obsreport_scraper.go
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/batchprocessor/metrics.go
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/go.mod
  receiver/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
  service/internal/proctelemetry/process_telemetry.go
  service/telemetry_test.go
Labels: Skip Contrib Tests

#7327 [chore] Prepare release 0.73.0/1.0.0-rc7
  .chloggen/codeboten_split-exporter.yaml
  .chloggen/codeboten_split-receiver.yaml
  .chloggen/connectors-routing-v2.yaml
  .chloggen/issue-7048.yaml
  .chloggen/service-graph-stable.yaml
  .chloggen/stableexpandEnabled.yaml
  CHANGELOG.md
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/config/default.yaml
  cmd/builder/test/core.builder.yaml
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/main.go
  component/go.mod
  confmap/go.mod
  connector/forwardconnector/go.mod
  consumer/go.mod
  examples/k8s/otel-config.yaml
  exporter/go.mod
  exporter/loggingexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/ballastextension/go.mod
  extension/zpagesextension/go.mod
  go.mod
  processor/batchprocessor/go.mod
  processor/memorylimiterprocessor/go.mod
  receiver/go.mod
  receiver/otlpreceiver/go.mod
  versions.yaml
Labels: Skip Contrib Tests

#7354 Propose to shift release v0.76.0 and subsequent releases by one week
  docs/release.md
Labels: Skip Changelog

#7353 Remove 'service.graph' feature gate
  service/service.go
Labels: Skip Changelog

#7363 Update release schedule
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests

#7314 Added security recommendation to use configopaque.String for sensitive fields
  CONTRIBUTING.md
  docs/security-best-practices.md
Labels: Skip Changelog

#7419 [docs] document feature gate removal
  featuregate/README.md
Labels: Skip Changelog

#7420 [chore] update merged pull request w/ milestone (#293)
  .github/workflows/milestone-add-to-pr.yml
Labels: Skip Changelog
