Repository open-telemetry/opentelemetry-collector, pull requests merged in 2023-01, with the labels that each got.

#6839 [docs] Relax bugfix criteria
  docs/release.md
Labels: area:documentation, Skip Changelog

#6814 chore(readme): otlphttp endpoint
  exporter/otlphttpexporter/README.md
Labels: Skip Changelog

#6928 Add connector logger
  service/internal/components/loggers.go
Labels: Skip Changelog, area:connector

#6937 Merge `release/v0.69.x` into `main`
  CHANGELOG.md
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/config/default.yaml
  cmd/builder/test/core.builder.yaml
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/main.go
  component/go.mod
  confmap/go.mod
  connector/forwardconnector/go.mod
  consumer/go.mod
  examples/k8s/otel-config.yaml
  exporter/loggingexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/ballastextension/go.mod
  extension/zpagesextension/go.mod
  go.mod
  processor/batchprocessor/go.mod
  processor/memorylimiterprocessor/go.mod
  receiver/otlpreceiver/go.mod
  versions.yaml
Labels: Skip Changelog

#6939 Fix instructions for updating contrib repo in release docs
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests

#6944 ocb: Update README.md
  cmd/builder/README.md
Labels: Skip Changelog

#6959 Update security recommendation
  docs/security-best-practices.md
Labels: Skip Changelog

#6926 Parameterize connector data type errors
  connector/connector.go
  connector/connector_test.go
Labels: Skip Changelog, area:connector

#6148 add remote debug option for otel-collector to builder
  .chloggen/add-debug-option-to builder.yaml
  cmd/builder/README.md
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/builder/config_test.go
  cmd/builder/internal/builder/main.go
  cmd/builder/internal/builder/main_test.go
  cmd/builder/internal/command.go
  cmd/builder/internal/command_test.go
Labels: Stale

#6793 Add reason for nosec annotation on builder inputs
  cmd/builder/internal/builder/main.go
Labels: Skip Changelog

#6789 Add support for connector configurations
  .chloggen/connector-config.yaml
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/builder/templates/components.go.tmpl
  cmd/builder/internal/builder/templates/components_test.go.tmpl
  cmd/builder/internal/builder/templates/go.mod.tmpl
  cmd/builder/internal/command.go
  cmd/builder/internal/config/default.yaml
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/components.go
  cmd/otelcorecol/components_test.go
  cmd/otelcorecol/go.mod
  otelcol/factories.go
  otelcol/otelcoltest/nop_factories.go
  otelcol/otelcoltest/nop_factories_test.go
  service/host.go
  service/service.go
  service/service_test.go
Labels: Skip Changelog, area:connector

#6973 [featuregate] use map of pointer to the gates, avoid re-adding to the registry map
  featuregate/registry.go
  featuregate/registry_test.go
Labels: Skip Changelog

#6968 Generalize the plan9 build restriction to any other platform
  .chloggen/otelcol-plan9build.yaml
  exporter/loggingexporter/known_sync_error_other.go
Labels: Skip Changelog

#6876 Fix: Force usage of case-sensitive keys in configurations
  .chloggen/case-sensitive-configuration.yaml
  confmap/confmap.go
  exporter/loggingexporter/config_test.go
  exporter/loggingexporter/testdata/config_loglevel_typo.yaml
Labels: ready-to-merge

#6853 [configgrpc] Change Headers field type to have opaque values
  .chloggen/mx-psi_configgrpc-opaque.yaml
  config/configgrpc/configgrpc.go
  config/configgrpc/configgrpc_test.go
  exporter/otlpexporter/config_test.go
  exporter/otlpexporter/factory.go
  exporter/otlpexporter/factory_test.go
  exporter/otlpexporter/otlp.go
  exporter/otlpexporter/otlp_test.go
Labels: ready-to-merge, Skip Contrib Tests

#6988 Revert "Fix: Force usage of case-sensitive keys in configurations"
  .chloggen/case-sensitive-configuration.yaml
  confmap/confmap.go
  exporter/loggingexporter/config_test.go
  exporter/loggingexporter/testdata/config_loglevel_typo.yaml
Labels: Skip Changelog

#6964 Add connectors to otelcol config
  otelcol/config.go
  otelcol/configprovider.go
  otelcol/unmarshaler.go
Labels: Skip Changelog, area:connector

#6764 Extract service.pipelines interface
  service/graph.go
  service/host.go
  service/pipelines.go
  service/pipelines_test.go
Labels: Skip Changelog, area:connector

#6895 Add component node types
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  go.mod
  go.sum
  service/nodes.go
Labels: Skip Changelog, area:connector

#6962 Continue to disallow directly implementing Factories, but allow it for component.Factory
  component/component.go
  component/component_test.go
  connector/connector.go
  exporter/exporter.go
  extension/extension.go
  processor/processor.go
  receiver/receiver.go
Labels: Skip Changelog

#7001 Add connector validation to otelcol
  otelcol/collector.go
  otelcol/config.go
  otelcol/config_test.go
  otelcol/otelcoltest/config_test.go
  otelcol/otelcoltest/testdata/config.yaml
Labels: Skip Changelog, area:connector

#7010 Merge otelcol test config structs
  otelcol/config_test.go
Labels: Skip Changelog

#6960 add github action to automate the release parts of the process
  .github/workflows/prepare-release.yml
  .github/workflows/scripts/release-check-blockers.sh
  .github/workflows/scripts/release-check-build-status.sh
  .github/workflows/scripts/release-create-tracking-issue.sh
  .github/workflows/scripts/release-prepare-release.sh
  Makefile
  docs/release.md
Labels: Skip Changelog

#6772 Use generics for sharedcomponents, removes casting increases type safetiness
  connector/forwardconnector/forward.go
  internal/sharedcomponent/sharedcomponent.go
  internal/sharedcomponent/sharedcomponent_test.go
  receiver/otlpreceiver/factory.go
Labels: Skip Changelog

#7014 Update otelcoltest to validate num connectors
  otelcol/otelcoltest/config_test.go
Labels: Skip Changelog

#7016 Add implementation of pipelineGraph StartAll and ShutdownAll
  service/graph.go
  service/graph_test.go
Labels: Skip Changelog

#7020 Group imports in builder templates
  cmd/builder/internal/builder/templates/components_test.go.tmpl
  cmd/builder/internal/builder/templates/main.go.tmpl
  cmd/builder/internal/builder/templates/main_windows.go.tmpl
Labels: Skip Changelog

#7013 Remove unnecessary interface in service/nodes.go
  service/graph_test.go
  service/nodes.go
Labels: Skip Changelog, area:connector

#7027 Increase components test in the builder generated code
  cmd/builder/internal/builder/templates/components_test.go.tmpl
  cmd/otelcorecol/components_test.go
Labels: Skip Changelog

#7035 Add connectors readme
  connector/README.md
Labels: Skip Changelog

#7023 Add entry point to build graph-based pipelines
  internal/sharedgate/sharedgate.go
  otelcol/config.go
  otelcol/config_test.go
  otelcol/otelcoltest/config_test.go
  service/graph.go
  service/service.go
Labels: Skip Changelog, area:connector

#7032 Document ability to use config providers inside config
  service/README.md
Labels: Skip Changelog

#7081 [pdata] Do not wrap orig fields when it's not required
  pdata/internal/cmd/pdatagen/internal/base_fields.go
  pdata/internal/cmd/pdatagen/internal/base_slices.go
  pdata/internal/cmd/pdatagen/internal/base_structs.go
  pdata/internal/cmd/pdatagen/internal/files.go
  pdata/internal/cmd/pdatagen/internal/pcommon_structs.go
  pdata/internal/cmd/pdatagen/internal/plogotlp_structs.go
  pdata/internal/cmd/pdatagen/internal/pmetricotlp_structs.go
  pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
  pdata/internal/cmd/pdatagen/internal/ptraceotlp_structs.go
  pdata/internal/generated_wrapper_common.go
  pdata/internal/generated_wrapper_logs.go
  pdata/internal/generated_wrapper_logs_otlp.go
  pdata/internal/generated_wrapper_metrics.go
  pdata/internal/generated_wrapper_metrics_otlp.go
  pdata/internal/generated_wrapper_traces.go
  pdata/internal/generated_wrapper_traces_otlp.go
  pdata/internal/wrapper_common.go
  pdata/pcommon/common.go
  pdata/pcommon/common_test.go
  pdata/pcommon/generated_common.go
  pdata/pcommon/generated_common_test.go
  pdata/pcommon/generated_resource.go
  pdata/plog/generated_logs.go
  pdata/plog/generated_logs_test.go
  pdata/plog/logs_test.go
  pdata/plog/plogotlp/generated_logs_otlp.go
  pdata/plog/plogotlp/generated_logs_otlp_test.go
  pdata/plog/plogotlp/response.go
  pdata/pmetric/generated_metrics.go
  pdata/pmetric/generated_metrics_test.go
  pdata/pmetric/metrics_test.go
  pdata/pmetric/pmetricotlp/generated_metrics_otlp.go
  pdata/pmetric/pmetricotlp/generated_metrics_otlp_test.go
  pdata/pmetric/pmetricotlp/response.go
  pdata/ptrace/generated_traces.go
  pdata/ptrace/generated_traces_test.go
  pdata/ptrace/ptraceotlp/generated_traces_otlp.go
  pdata/ptrace/ptraceotlp/generated_traces_otlp_test.go
  pdata/ptrace/ptraceotlp/response.go
  pdata/ptrace/traces_test.go
Labels: Skip Changelog

#6870 Add shellcheck GitHub Actions workflow
  .github/workflows/scripts/dependabot-pr.sh
  .github/workflows/scripts/set_release_tag.sh
  .github/workflows/scripts/verify-dist-files-exist.sh
  .github/workflows/shellcheck.yml
  cmd/builder/test/test.sh
  internal/buildscripts/compare-apidiff.sh
  internal/buildscripts/gen-apidiff.sh
Labels: Skip Changelog
