Repository open-telemetry/opentelemetry-collector, pull requests merged in 2023-09, with the labels that each got.

#8348 Improve configauth docs
  config/configauth/README.md
  config/configgrpc/README.md
  config/confighttp/README.md
  receiver/otlpreceiver/README.md
Labels: Skip Changelog

#8274 [confighttp] Add option to disable HTTP keep-alives
  .chloggen/disable_keep_alives.yaml
  config/confighttp/README.md
  config/confighttp/confighttp.go
  config/confighttp/confighttp_test.go
Labels: ready-to-merge

#8299 [chore] update otel go 1.17
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  component/go.mod
  component/go.sum
  config/configauth/go.mod
  config/configauth/go.sum
  config/configgrpc/go.mod
  config/configgrpc/go.sum
  config/confighttp/go.mod
  config/confighttp/go.sum
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  connector/go.mod
  connector/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/auth/go.mod
  extension/auth/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/go.mod
  extension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  obsreport/obsreport_exporter.go
  obsreport/obsreport_processor.go
  obsreport/obsreport_receiver.go
  obsreport/obsreport_scraper.go
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/batchprocessor/metrics.go
  processor/batchprocessor/metrics_test.go
  processor/go.mod
  processor/go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/go.mod
  receiver/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
  service/internal/proctelemetry/config.go
  service/internal/proctelemetry/process_telemetry.go
Labels: Skip Changelog

#8499 rename exporterhelper obsreport method
  .chloggen/codeboten_obsreport-dep.yaml
  exporter/exporterhelper/common.go
  exporter/exporterhelper/obsexporter.go
  exporter/exporterhelper/obsexporter_test.go
  exporter/exporterhelper/obsreport.go
  exporter/exporterhelper/obsreport_test.go
  obsreport/obsreport_exporter.go
  obsreport/obsreporttest/obsreporttest_test.go
Labels: Skip Changelog

#8506 [chore] fix deprecation version
  obsreport/obsreport_exporter.go
  obsreport/obsreport_processor.go
  obsreport/obsreport_receiver.go
  obsreport/obsreport_scraper.go
  obsreport/obsreporttest/obsreporttest.go
Labels: release:blocker

#8508 remove NewCreateSettings funcs
  .chloggen/codeboten_deprecate-obsreporttest.yaml
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/obsexporter_test.go
  exporter/exporterhelper/obsreport_test.go
  exporter/exporterhelper/queue_sender_test.go
  exporter/exporterhelper/traces_test.go
  exporter/exportertest/nop_exporter.go
  obsreport/obsreporttest/obsreporttest.go
  obsreport/obsreporttest/obsreporttest_test.go
  processor/processorhelper/obsreport_test.go
  processor/processortest/nop_processor.go
  receiver/receiverhelper/obsreport_test.go
  receiver/receivertest/nop_receiver.go
  receiver/scraperhelper/obsreport_test.go
  receiver/scraperhelper/scrapercontroller_test.go
Labels: Skip Changelog

#8224 Doc update to introduce Tiered Platform Support Model
  docs/platform-support.md
Labels: Skip Changelog

#8525 [docs/release] Specify platform tier for bugfix releases
  docs/release.md
Labels: Skip Changelog

#8554 [docs] Simplify troubleshooting doc
  docs/troubleshooting.md
Labels: area:documentation, Skip Changelog
