Repository open-telemetry/opentelemetry-collector, pull requests merged in 2023-02, with the labels that each got.

#7092 [chore] [pdata] Move constants to separate files
  pdata/plog/logs.go
  pdata/plog/logs_test.go
  pdata/plog/severity_number.go
  pdata/plog/severity_number_test.go
  pdata/pmetric/aggregation_temporality.go
  pdata/pmetric/aggregation_temporality_test.go
  pdata/pmetric/exemplar_value_type.go
  pdata/pmetric/exemplar_value_type_test.go
  pdata/pmetric/metric_type.go
  pdata/pmetric/metric_type_test.go
  pdata/pmetric/metrics.go
  pdata/pmetric/metrics_test.go
  pdata/pmetric/number_data_point_value_type.go
  pdata/pmetric/number_data_point_value_type_test.go
  pdata/ptrace/span_kind.go
  pdata/ptrace/span_kind_test.go
  pdata/ptrace/status_code.go
  pdata/ptrace/status_code_test.go
  pdata/ptrace/traces.go
  pdata/ptrace/traces_test.go
Labels: Skip Contrib Tests

#7093 Rename pipelineSettings fields with Builder
  service/pipelines.go
  service/pipelines_test.go
  service/service.go
Labels: Skip Changelog, Skip Contrib Tests

#7096 Simplify forward connector by removing sharedcomponent
  connector/forwardconnector/forward.go
Labels: Skip Changelog, Skip Contrib Tests

#7091 [pdata] Deprecate [Metrics|Logs|Traces].MoveTo methods
  .chloggen/pdata-deprecate-moveto.yaml
  pdata/plog/logs.go
  pdata/pmetric/metrics.go
  pdata/ptrace/traces.go
Labels: Skip Contrib Tests

#7028 Remove deprecated pcommon.Map.Sort
  .chloggen/rmsort.yaml
  pdata/pcommon/map.go
  pdata/pcommon/map_test.go
Labels: Skip Contrib Tests

#6886 Instrument proctelemetry.ProcessMetrics
  .chloggen/proctelemetry-processmetrics.yaml
  service/internal/proctelemetry/process_telemetry.go
  service/internal/proctelemetry/process_telemetry_test.go
  service/service.go
  service/service_test.go
Labels: Skip Contrib Tests

#7045 Add full component graph build
  connector/connector.go
  connector/connector_test.go
  service/graph.go
  service/graph_test.go
  service/internal/testcomponents/example_processor.go
  service/nodes.go
  service/pipelines.go
  service/pipelines_test.go
Labels: Skip Changelog, area:connector

#7108 Add graph-based GetExporters
  service/graph.go
Labels: Skip Changelog

#7110 Disambiguate component ID in 'connectortest' package
  connector/connectortest/connector.go
  connector/connectortest/connector_test.go
Labels: Skip Changelog

#7113 Added guidelines for getter and setter Method.
  CONTRIBUTING.md
Labels: Skip Changelog

#7109 Add graph-based implemenation of HandleZPages
  service/graph.go
  service/pipelines.go
  service/service_test.go
  service/zpages.go
Labels: Skip Changelog

#7127 Connectors comment typo
  service/graph.go
Labels: Skip Changelog, Skip Contrib Tests

#7128 Update forward connector readme
  connector/forwardconnector/README.md
Labels: Skip Changelog, Skip Contrib Tests

#7142 Revert "[memorylimiter] Fix cgroups parsing"
  .chloggen/fix-memory-limiter.yaml
  internal/cgroups/cgroups.go
  internal/cgroups/testdata/proc/cgroups/mountinfo
Labels: Skip Changelog

#7148 Fix API to be compatible with flagset, missed the comment initially
  .chloggen/addvisit.yaml
  featuregate/registry.go
  featuregate/registry_test.go
  service/zpages.go
Labels: Skip Changelog, Skip Contrib Tests

#7149 Bump otel-go to latest
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  component/go.mod
  component/go.sum
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
Labels: dependencies, Skip Contrib Tests

#7154 Bump otel-go/contrib to latest
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
Labels: dependencies, Skip Contrib Tests

#7151 remove go 1.18 support, bump minimum to go 1.19 and add testing for 1.20
  .chloggen/go1-20.yaml
  .github/workflows/build-and-test.yml
  Makefile.Common
  cmd/builder/go.mod
  cmd/builder/internal/builder/main.go
  cmd/builder/internal/builder/templates/go.mod.tmpl
  cmd/otelcorecol/go.mod
  component/go.mod
  confmap/go.mod
  connector/forwardconnector/go.mod
  consumer/go.mod
  exporter/loggingexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/ballastextension/go.mod
  extension/zpagesextension/go.mod
  featuregate/go.mod
  go.mod
  internal/tools/go.mod
  pdata/go.mod
  processor/batchprocessor/go.mod
  processor/memorylimiterprocessor/go.mod
  receiver/otlpreceiver/go.mod
  semconv/go.mod
Labels: Skip Contrib Tests

#7166 [chore] Move an abandoned .chloggen entry to CHANGELOG.md
  .chloggen/msg_add-issue-link-deprecation.yml
  CHANGELOG.md
Labels: Skip Contrib Tests

#7197 [chore] Fix typo in exporterhelper godoc
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/traces.go
  exporter/exportertest/nop_exporter.go
  service/graph_test.go
Labels: Skip Changelog

#7210 Ensure workflows use Go >=1.19.6
  .github/workflows/api-compatibility.yml
  .github/workflows/build-and-test-windows.yaml
  .github/workflows/build-and-test.yml
  .github/workflows/builder-integration-test.yaml
  .github/workflows/builder-release.yaml
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contrib-tests.yml
  .github/workflows/create-dependabot-pr.yml
  .github/workflows/prepare-release.yml
Labels: Skip Changelog

#7212 Update release.md
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests

#7216 Use http constants to replace numbers as parameters
  config/confighttp/compression_test.go
  config/confighttp/confighttp_test.go
  obsreport/obsreporttest/otelprometheuschecker.go
  processor/batchprocessor/metrics_test.go
  service/internal/proctelemetry/process_telemetry_test.go
  service/telemetry_test.go
Labels: Skip Changelog

#7206 Improve error message when cycle is detected in component graph
  service/graph.go
  service/graph_test.go
Labels: Skip Changelog

#7270 Fix example in connectors README
  connector/README.md
Labels: Skip Changelog

#7269 Remove zpagesPipeline interface
  service/graph.go
  service/pipelines.go
  service/zpages.go
Labels: Skip Changelog
