Repository open-telemetry/opentelemetry-collector, pull requests merged in 2023-06, with the labels that each got.

#7802 [docs] fix code reference in configtls readme
  config/configtls/README.md
Labels: Skip Changelog

#7807 Propose @astencel-sumo as triager
  README.md
Labels: Skip Changelog

#7516 Add receiver/consumer contract test helper
  receiver/receivertest/contract_checker.go
  receiver/receivertest/contract_checker_test.go
Labels: Skip Changelog

#7815 Fix: Correct spelling of transformation in docs/processing.md.
  docs/processing.md
Labels: Skip Changelog

#7810 [doc] update documentation
  extension/experimental/storage/doc.go
Labels: Skip Changelog

#7873 [ci] Specify 7 as arm version for arm build in CI
  .github/workflows/build-and-test.yml
Labels: Skip Changelog

#7893 [service] Ensure test service eventually connects to telemetry port on restart
  service/service_test.go
Labels: Skip Changelog

#7944 Merge `main` into `v0.80.0` prep PR
  Makefile
  cmd/otelcorecol/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
Labels: Skip Changelog, Skip Contrib Tests

#7679 add auto-generated configuration code
  .github/workflows/perf.yml
  .gitignore
  Makefile
  Makefile.Common
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
  service/telemetry/generated_config.go
Labels: Skip Changelog

#7542 [cmd/builder] Add option to skip generating sources
  .chloggen/builder-skip-generate.yaml
  cmd/builder/README.md
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/builder/main.go
  cmd/builder/internal/builder/main_test.go
  cmd/builder/internal/command.go
  cmd/builder/internal/command_test.go
Labels: Stale

#7911 fix in github.com/mitchellh/mapstructure for slices mapping issue
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  component/go.mod
  component/go.sum
  config/configauth/go.mod
  config/configauth/go.sum
  config/configgrpc/go.mod
  config/configgrpc/go.sum
  config/confighttp/go.mod
  config/confighttp/go.sum
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  connector/go.mod
  connector/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/auth/go.mod
  extension/auth/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/go.mod
  extension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/go.mod
  processor/go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/go.mod
  receiver/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
Labels: Skip Changelog

#7953 Revert "[scraper helper] Include support for timeout"
  .chloggen/msg_introduce-timeout-scrape.yaml
  receiver/scraperhelper/scrapercontroller.go
  receiver/scraperhelper/settings.go
  receiver/scraperhelper/settings_test.go
Labels: Skip Changelog

#7994 Swap release managers for v0.81.0 and v0.82.0
  docs/release.md
Labels: Skip Changelog

#7997 Update koanf to v2
  cmd/builder/go.mod
  cmd/builder/go.sum
  cmd/builder/internal/builder/config_test.go
  cmd/builder/internal/command.go
  cmd/builder/internal/config/default.go
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  component/go.mod
  component/go.sum
  config/configauth/go.mod
  config/configauth/go.sum
  config/configgrpc/go.mod
  config/configgrpc/go.sum
  config/confighttp/go.mod
  config/confighttp/go.sum
  confmap/confmap.go
  confmap/go.mod
  confmap/go.sum
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  connector/go.mod
  connector/go.sum
  consumer/go.mod
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/auth/go.mod
  extension/auth/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/go.mod
  extension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/go.mod
  processor/go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/go.mod
  receiver/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
Labels: Skip Changelog
