Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-03, with the labels that each got.

#9409 [chore] validate version format to prepare-release workflow
  .github/workflows/prepare-release.yml
Labels: ready-to-merge, Skip Changelog

#9689 Add a workflow to test otelcorecol as a Windows service
  .github/workflows/build-and-test-windows.yaml
Labels: Skip Changelog

#9444 [docs][chore] warning for using localhost in security-best-practices
  docs/security-best-practices.md
Labels: Stale

#9472 [component] Change component.Type underlying type to a struct
  .chloggen/mx-psi_switch-to-type.yaml
  component/config.go
  component/config_test.go
  config/confighttp/confighttp_test.go
Labels: release:required-for-ga

#9722 [exporter/otlphttp] enable lifecycle tests
  exporter/otlphttpexporter/generated_component_test.go
  exporter/otlphttpexporter/metadata.yaml
Labels: Skip Changelog

#9669 use generated meter
  processor/batchprocessor/metrics.go
Labels: Skip Changelog

#9735 [exporter/otlp] enable lifecycle test
  exporter/otlpexporter/generated_component_test.go
  exporter/otlpexporter/metadata.yaml
Labels: Skip Changelog

#9385 [confignet] Change `Transport` from `string` to `TransportType`
  .chloggen/confignet-transport-type.yaml
  config/configgrpc/configgrpc.go
  config/configgrpc/configgrpc_test.go
  config/confignet/confignet.go
  config/confignet/confignet_test.go
  receiver/otlpreceiver/config_test.go
  receiver/otlpreceiver/factory.go
  receiver/otlpreceiver/factory_test.go
  receiver/otlpreceiver/otlp_test.go
Labels: release:required-for-ga

#9782 [chore][status] Remove deprecated functions `ReportComponentStatus` and `ReportComponentOkIfStarting`
  service/internal/status/status.go
Labels: Skip Changelog

#9792 [CONTRIBUTING.md] Update golang version
  CONTRIBUTING.md
Labels: Skip Changelog

#9671 [confignet] added NewDefaultFunctions
  .chloggen/confignet-add-newdefault-func.yaml
  config/confignet/confignet.go
  config/confignet/confignet_test.go
Labels: ready-to-merge

#9762 Nicer error message when passing an empty configuration file
  otelcol/config.go
  otelcol/config_test.go
Labels: Skip Changelog

#9796 [client] Remove experimental comment from `Metadata`
  client/client.go
Labels: Skip Changelog

#9786 [configtls] Removed deprecated structs
  .chloggen/configtls-remove-deprecated.yaml
  .chloggen/configtls-remove-deprecated2.yaml
  config/configgrpc/configgrpc_test.go
  config/confighttp/confighttp_test.go
  config/configtls/configtls.go
  config/configtls/configtls_test.go
  exporter/otlpexporter/config_test.go
  exporter/otlpexporter/factory_test.go
  exporter/otlphttpexporter/config_test.go
  exporter/otlphttpexporter/factory_test.go
  receiver/otlpreceiver/config_test.go
  receiver/otlpreceiver/otlp_test.go
Labels: ready-to-merge, Skip Contrib Tests

#9738 [exporterhelper] Add default batching for OTLP data type
  .chloggen/batch-exporter-helper.yaml
  exporter/exporterhelper/batch_sender.go
  exporter/exporterhelper/batch_sender_test.go
  exporter/exporterhelper/common.go
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/logs_batch.go
  exporter/exporterhelper/logs_batch_test.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/metrics_batch.go
  exporter/exporterhelper/metrics_batch_test.go
  exporter/exporterhelper/traces.go
  exporter/exporterhelper/traces_batch.go
  exporter/exporterhelper/traces_batch_test.go
Labels: Skip Changelog
