Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-09, with the labels that each got.

#10981 [confmap/provider/envprovider] Mark module as stable
  .chloggen/mx-psi_envprovider-1.0.yaml
  versions.yaml
Labels: release:blocker

#10984 [confmap/provider/fileprovider] Mark as stable
  .chloggen/mx-psi_fileprovider-1.0.yaml
  versions.yaml
Labels: release:blocker

#11044 [extensiontest] Remove StatusWatcher helpers
  .chloggen/mx-psi_move-extensionstatus.yaml
  config/configauth/go.mod
  exporter/go.mod
  extension/auth/go.mod
  extension/experimental/storage/go.mod
  extension/extensioncapabilities/go.mod
  extension/extensiontest/statuswatcher_extension.go
  extension/extensiontest/statuswatcher_extension_test.go
  extension/go.mod
  extension/memorylimiterextension/go.mod
  otelcol/collector_test.go
Labels: release:blocker

#11050 [exporter/logging] Add warning to logging exporter
  exporter/loggingexporter/factory.go
Labels: Skip Changelog

#11041 [exporter] [chore] Initialize batchSender and queueSender after configuration
  exporter/exporterhelper/common.go
Labels: Skip Changelog

#11074 Fix documentation for max_request_body_size
  config/confighttp/README.md
  receiver/otlpreceiver/config.md
Labels: Skip Changelog

#11055 Revert "[configtelemetry] Mark module as stable"
  .chloggen/mx-psi_configtelemetry-1.0.yaml
  versions.yaml
Labels: Skip Changelog, release:blocker

#11021 [chore]: enable len and empty rules from testifylint
  .golangci.yml
  Makefile
  Makefile.Common
  cmd/builder/internal/builder/config_test.go
  connector/connectorprofiles/profiles_router_test.go
  connector/forwardconnector/forward_test.go
  connector/logs_router_test.go
  connector/metrics_router_test.go
  connector/traces_router_test.go
  consumer/consumertest/sink_test.go
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/traces_test.go
  exporter/otlpexporter/otlp_test.go
  internal/e2e/status_test.go
  internal/sharedcomponent/sharedcomponent_test.go
  internal/testutil/testutil.go
  internal/testutil/testutil_test.go
  internal/tools/go.mod
  internal/tools/tools.go
  otelcol/buffered_core_test.go
  otelcol/collector_core_test.go
  otelcol/otelcoltest/nop_factories_test.go
  pdata/pcommon/map_test.go
  pdata/pcommon/slice_test.go
  pdata/plog/pb_test.go
  pdata/pmetric/pb_test.go
  pdata/ptrace/pb_test.go
  processor/batchprocessor/batch_processor_test.go
  receiver/otlpreceiver/otlp_test.go
  receiver/receiverhelper/obsreport_test.go
  receiver/receivertest/contract_checker.go
  service/internal/graph/graph_test.go
  service/internal/proctelemetry/process_telemetry_linux_test.go
  service/internal/proctelemetry/process_telemetry_test.go
  service/internal/testcomponents/example_exporter_test.go
  service/internal/testcomponents/example_router_test.go
Labels: ci-cd, Skip Contrib Tests

#11090 [chore] bump go version
  .github/workflows/api-compatibility.yml
  .github/workflows/build-and-test-arm.yml
  .github/workflows/build-and-test-windows.yaml
  .github/workflows/build-and-test.yml
  .github/workflows/builder-integration-test.yaml
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contrib-tests.yml
  .github/workflows/perf.yml
  .github/workflows/prepare-release.yml
  .github/workflows/tidy-dependencies.yml
  cmd/otelcorecol/go.mod
  internal/tools/go.mod
Labels: ci-cd, Skip Contrib Tests

#11097 Add replace statements for builder profiler artifacts
  cmd/builder/test/core.builder.yaml
Labels: Skip Changelog, Skip Contrib Tests

#11100 Add replace statements for contrib tests
  Makefile
Labels: Skip Changelog, Skip Contrib Tests

#10907 Support default values and erorrs for env var expansion
  .chloggen/envprovider-default-value.yaml
  confmap/provider/envprovider/provider.go
  confmap/provider/envprovider/provider_test.go
Labels: Stale

#11115 Revert "[confignet] Mark as stable"
  .chloggen/confignet-mark-stable.yaml
  versions.yaml
Labels: Skip Changelog, Skip Contrib Tests

#11120 [chore]: enable error-nil and nil-compare rules from testifylint
  .golangci.yml
  Makefile.Common
  component/componentstatus/status_test.go
  config/configtls/configtls_test.go
  confmap/resolver_test.go
  exporter/exporterhelper/batch_sender_test.go
  exporter/exporterhelper/common_test.go
  exporter/exporterhelper/logs_batch_test.go
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics_batch_test.go
  exporter/exporterhelper/traces_batch_test.go
  exporter/otlpexporter/factory_test.go
  exporter/otlphttpexporter/factory_test.go
  exporter/otlphttpexporter/otlp_test.go
  pdata/pcommon/value_test.go
  processor/processorhelper/logs_test.go
  processor/processorhelper/metrics_test.go
  processor/processorhelper/traces_test.go
Labels: ci-cd

#11123 [builder]: Fix version for providers in the default config
  .chloggen/fixdefaultcfg.yaml
  cmd/builder/internal/config/default.yaml
Labels: bug

#11127 [chore] Cleanup builder-integration-test
  cmd/builder/test/core.builder.yaml
Labels: Skip Changelog

#11124 [chore] Remove release issue template, automatically created by the automation
  .github/ISSUE_TEMPLATE/release.md
Labels: Skip Changelog, Skip Contrib Tests

#11128 [chore]: enable compares and negative-positive rules from testifylint
  .golangci.yml
  Makefile.Common
  exporter/exporterhelper/retry_sender_test.go
  internal/fanoutconsumer/logs_test.go
  internal/fanoutconsumer/metrics_test.go
  internal/fanoutconsumer/profiles_test.go
  internal/fanoutconsumer/traces_test.go
  internal/iruntime/mem_info_test.go
  internal/iruntime/total_memory_linux_test.go
Labels: ci-cd, Skip Contrib Tests

#11132 [exporterhelper] Rename Timeout/QueueSettings to Config
  .chloggen/6767-exporterhelper-rename-config.yaml
  exporter/debugexporter/factory.go
  exporter/exporterhelper/batch_sender_test.go
  exporter/exporterhelper/common.go
  exporter/exporterhelper/common_test.go
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/queue_sender.go
  exporter/exporterhelper/queue_sender_test.go
  exporter/exporterhelper/retry_sender_test.go
  exporter/exporterhelper/timeout_sender.go
  exporter/exporterhelper/timeout_sender_test.go
  exporter/exporterhelper/traces_test.go
  exporter/exporterqueue/config.go
  exporter/internal/common/factory.go
  exporter/otlpexporter/cfg-schema.yaml
  exporter/otlpexporter/config.go
  exporter/otlpexporter/config_test.go
  exporter/otlpexporter/factory.go
  exporter/otlpexporter/factory_test.go
  exporter/otlphttpexporter/config.go
  exporter/otlphttpexporter/config_test.go
  exporter/otlphttpexporter/factory.go
  exporter/otlphttpexporter/otlp_test.go
  internal/e2e/consume_contract_test.go
Labels: ready-to-merge

#11138 Update release schedule
  docs/release.md
Labels: ready-to-merge, Skip Changelog, Skip Contrib Tests

#11148 Remove obsreportconfig package, reduce dependencies
  cmd/mdatagen/go.mod
  exporter/debugexporter/go.mod
  exporter/debugexporter/go.sum
  exporter/exporterhelper/internal/obsmetrics.go
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/obsexporter.go
  exporter/exporterhelper/obsexporter_test.go
  exporter/exporterhelper/queue_sender.go
  exporter/exporterhelper/queue_sender_test.go
  exporter/exporterhelper/retry_sender.go
  exporter/exporterhelper/traces_test.go
  exporter/exporterprofiles/go.mod
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/nopexporter/go.mod
  internal/obsreportconfig/obsmetrics/obs_processor.go
  internal/obsreportconfig/obsmetrics/obs_scraper.go
  internal/obsreportconfig/obsmetrics/obsmetrics.go
  internal/obsreportconfig/obsreportconfig.go
  internal/obsreportconfig/package_test.go
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/batchprocessor/metrics.go
  processor/go.mod
  processor/go.sum
  processor/internal/obsmetrics.go
  processor/processorhelper/obsreport.go
  processor/processorhelper/processor.go
  processor/processorprofiles/go.mod
  receiver/go.mod
  receiver/go.sum
  receiver/internal/obsmetrics.go
  receiver/nopreceiver/go.mod
  receiver/receiverhelper/obsreport.go
  receiver/receiverhelper/obsreport_test.go
  receiver/receiverprofiles/go.mod
  receiver/scraperhelper/obsreport.go
  receiver/scraperhelper/obsreport_test.go
  service/service.go
Labels: Skip Changelog

#11157 [confmap] Do not leak expanded values on Sub
  .chloggen/mx-psi_fix-sub-config.yaml
  confmap/confmap.go
  confmap/confmap_test.go
Labels: release:blocker

#11165 [Chore] assert.Positive comply with testifylint
  internal/iruntime/total_memory_other_test.go
Labels: ci-cd

#11051 otelcol: fix windows event log core placement
  .chloggen/fix_windows_service_event_log_core.yaml
  otelcol/collector_windows.go
  otelcol/collector_windows_service_test.go
  otelcol/testdata/otelcol-log-to-file.yaml
Labels: os:windows

#11169 [mdatagen] Fix metric tests on boolean attributes
  .chloggen/fix-mdatagen-metrics-bool-attr.yaml
  cmd/mdatagen/internal/samplereceiver/documentation.md
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics.go
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics_test.go
  cmd/mdatagen/internal/samplereceiver/metadata.yaml
  cmd/mdatagen/loader_test.go
  cmd/mdatagen/templates/metrics_test.go.tmpl
Labels: Skip Changelog

#11149 [chore]: enable float-compare rule from testifylint
  .golangci.yml
  Makefile.Common
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics_test.go
  cmd/mdatagen/internal/templates/metrics_test.go.tmpl
  pdata/internal/cmd/pdatagen/internal/base_fields.go
  pdata/internal/cmd/pdatagen/internal/primitive_slice_structs.go
  pdata/internal/json/number_test.go
  pdata/pcommon/generated_float64slice_test.go
  pdata/pcommon/map_test.go
  pdata/pcommon/value_test.go
  pdata/pmetric/generated_exemplar_test.go
  pdata/pmetric/generated_exponentialhistogramdatapoint_test.go
  pdata/pmetric/generated_histogramdatapoint_test.go
  pdata/pmetric/generated_numberdatapoint_test.go
  pdata/pmetric/generated_summarydatapoint_test.go
  pdata/pmetric/generated_summarydatapointvalueatquantile_test.go
  pdata/pmetric/metrics_test.go
  service/telemetry/metrics_test.go
Labels: ci-cd

#11119 Add marshal calls to fuzzers
  pdata/plog/fuzz_test.go
  pdata/plog/plogotlp/fuzz_test.go
  pdata/pprofile/fuzz_test.go
  pdata/pprofile/pprofileotlp/fuzz_test.go
  pdata/ptrace/fuzz_test.go
  pdata/ptrace/ptraceotlp/fuzz_test.go
Labels: Skip Changelog

#9845 docs: update wildcard usage on cors
  config/confighttp/README.md
Labels: Skip Changelog

#11001 [chore][VERSIONING.md] Add long term support policy
  VERSIONING.md
Labels: Skip Changelog

#11246 Update pipeline and globalgate versions
  cmd/mdatagen/go.mod
  cmd/otelcorecol/go.mod
  component/componentprofiles/go.mod
  component/componentstatus/go.mod
  component/go.mod
  config/configauth/go.mod
  config/configgrpc/go.mod
  config/confighttp/go.mod
  connector/connectorprofiles/go.mod
  connector/forwardconnector/go.mod
  connector/go.mod
  exporter/debugexporter/go.mod
  exporter/exporterprofiles/go.mod
  exporter/go.mod
  exporter/loggingexporter/go.mod
  exporter/nopexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/auth/go.mod
  extension/experimental/storage/go.mod
  extension/extensioncapabilities/go.mod
  extension/go.mod
  extension/memorylimiterextension/go.mod
  extension/zpagesextension/go.mod
  go.mod
  internal/e2e/go.mod
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  pipeline/go.mod
  processor/batchprocessor/go.mod
  processor/go.mod
  processor/memorylimiterprocessor/go.mod
  processor/processorprofiles/go.mod
  receiver/go.mod
  receiver/nopreceiver/go.mod
  receiver/otlpreceiver/go.mod
  receiver/receiverprofiles/go.mod
  service/go.mod
Labels: Skip Changelog

#11247 Update pipeline and globalgate versions
  cmd/mdatagen/go.mod
  cmd/otelcorecol/go.mod
  component/componentprofiles/go.mod
  component/componentstatus/go.mod
  component/go.mod
  config/configauth/go.mod
  config/configgrpc/go.mod
  config/confighttp/go.mod
  connector/connectorprofiles/go.mod
  connector/forwardconnector/go.mod
  connector/go.mod
  exporter/debugexporter/go.mod
  exporter/exporterprofiles/go.mod
  exporter/go.mod
  exporter/loggingexporter/go.mod
  exporter/nopexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/auth/go.mod
  extension/experimental/storage/go.mod
  extension/extensioncapabilities/go.mod
  extension/go.mod
  extension/memorylimiterextension/go.mod
  extension/zpagesextension/go.mod
  go.mod
  internal/e2e/go.mod
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  pipeline/go.mod
  processor/batchprocessor/go.mod
  processor/go.mod
  processor/memorylimiterprocessor/go.mod
  processor/processorprofiles/go.mod
  receiver/go.mod
  receiver/nopreceiver/go.mod
  receiver/otlpreceiver/go.mod
  receiver/receiverprofiles/go.mod
  service/go.mod
Labels: Skip Changelog

#11235 Mark UseLocalHostAsDefaultHostfeatureGate as stable
  .chloggen/stable-localhost.yaml
  config/configgrpc/configgrpc_test.go
  config/configgrpc/go.mod
  config/configgrpc/go.sum
  config/confighttp/confighttp_test.go
  config/confighttp/go.mod
  config/confighttp/go.sum
  config/internal/go.mod
  config/internal/go.sum
  config/internal/warning.go
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  internal/globalgates/globalgates.go
  receiver/otlpreceiver/factory.go
  receiver/otlpreceiver/factory_test.go
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
  service/service.go
Labels: Skip Contrib Tests

#11249 [service] Start refactor of GetExporters
  .chloggen/rename-getexporters.yaml
  service/go.mod
  service/internal/graph/host.go
  service/service_test.go
Labels: release:blocker

#11223 Add mdatagen replace option to check-contrib target
  Makefile
Labels: Skip Changelog

#11273 [exporter/otlphttpexporter] Use NewDefaultClientConfig instead of manually creating struct
  exporter/otlphttpexporter/factory.go
Labels: Skip Changelog

#11254 [chore] Move back receiver definitions, make profile embed receiver
  receiver/internal/factory.go
  receiver/internal/logs.go
  receiver/internal/metrics.go
  receiver/internal/profiles.go
  receiver/internal/receiver.go
  receiver/internal/traces.go
  receiver/otlpreceiver/factory.go
  receiver/otlpreceiver/factory_test.go
  receiver/receiver.go
  receiver/receiverprofiles/go.mod
  receiver/receiverprofiles/profiles.go
  receiver/receiverprofiles/receiver_test.go
  receiver/receivertest/nop_receiver.go
  receiver/receivertest/nop_receiver_test.go
  service/internal/builders/receiver.go
  service/internal/builders/receiver_test.go
  service/internal/graph/graph_test.go
  service/internal/testcomponents/example_receiver.go
Labels: release:blocker

#11286 [chore] Move back processor definitions, make profile embed processor
  processor/internal/factory.go
  processor/internal/logs.go
  processor/internal/metrics.go
  processor/internal/processor.go
  processor/internal/profiles.go
  processor/internal/traces.go
  processor/processor.go
  processor/processorprofiles/go.mod
  processor/processorprofiles/processor.go
  processor/processorprofiles/processor_test.go
  processor/processortest/nop_processor.go
  processor/processortest/nop_processor_test.go
  service/internal/builders/processor.go
  service/internal/builders/processor_test.go
  service/internal/graph/graph_test.go
  service/internal/testcomponents/example_processor.go
Labels: release:blocker

#11291 [chore] otlpreceiver: README: markdown formatting fix
  receiver/otlpreceiver/README.md
Labels: Skip Changelog

#11309 Refactor batch processor export method
  processor/batchprocessor/batch_processor.go
  processor/batchprocessor/batch_processor_test.go
Labels: Skip Changelog
