Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-04, with the labels that each got.

#9797 Remove docs/design.md and linked images
  docs/design.md
  docs/images/design-collector-agent.png
  docs/images/design-collector-service.png
  docs/images/design-exporters.png
  docs/images/design-pipelines.png
  docs/images/design-processors.png
  docs/images/design-receivers.png
  docs/images/opentelemetry-service-deployment-models.png
  docs/images/zpages-example.png
Labels: Skip Changelog

#9756 updated README.md file in otlpreceiver
  receiver/otlpreceiver/README.md
Labels: Skip Changelog

#9838 [chore] Updated `unmarshalText` func
  config/configcompression/compressiontype.go
Labels: Skip Changelog

#9888 [chore] bump go to 1.21.9
  .github/workflows/build-and-test.yml
  .github/workflows/tidy-dependencies.yml
Labels: Skip Contrib Tests

#9893 [receiver/otlp] Refactor http error handling
  receiver/otlpreceiver/internal/errors/errors.go
  receiver/otlpreceiver/internal/errors/errors_test.go
  receiver/otlpreceiver/otlphttp.go
Labels: Skip Changelog

#9910 Move arm64 to platform support tier 2
  docs/platform-support.md
Labels: Skip Changelog, Skip Contrib Tests

#9257 [service] Validate pipeline type against component types
  .chloggen/validate-pipeline-types.yaml
  otelcol/collector.go
  otelcol/collector_test.go
  otelcol/command_components.go
  otelcol/factories_test.go
  otelcol/testdata/components-output.yaml
  otelcol/testdata/otelcol-invalid-receiver-type.yaml
  receiver/receivertest/nop_receiver.go
Labels: Stale

#9937 [chore] Cleanup changelog
  .chloggen/use-sync/atomic.yaml
  CHANGELOG-API.md
Labels: Skip Changelog, Skip Contrib Tests

#9884 [chore] [exporterhelper] Update stale batchSender comments
  exporter/exporterhelper/batch_sender.go
Labels: Skip Changelog

#9954 Promote @atoulme, @TylerHelmuth and @songy23 to approvers
  README.md
  docs/release.md
Labels: Skip Changelog

#9934 Update module go.opentelemetry.io/contrib/config to v0.5.0
  cmd/mdatagen/go.mod
  cmd/mdatagen/go.sum
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  config/configgrpc/go.mod
  config/configgrpc/go.sum
  config/confighttp/go.mod
  config/confighttp/go.sum
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  connector/go.mod
  connector/go.sum
  exporter/debugexporter/go.mod
  exporter/debugexporter/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/nopexporter/go.mod
  exporter/nopexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/memorylimiterextension/go.mod
  extension/memorylimiterextension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  internal/e2e/go.mod
  internal/e2e/go.sum
  otelcol/go.mod
  otelcol/go.sum
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/go.mod
  processor/go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/go.mod
  receiver/go.sum
  receiver/nopreceiver/go.mod
  receiver/nopreceiver/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
  service/go.mod
  service/go.sum
Labels: Skip Changelog

#9959 [mdatagen] generate goleak package test
  .chloggen/codeboten_mdatagen-goleak.yaml
  cmd/mdatagen/embeded_templates_test.go
  cmd/mdatagen/internal/samplereceiver/generated_package_test.go
  cmd/mdatagen/loader.go
  cmd/mdatagen/main.go
  cmd/mdatagen/main_test.go
  cmd/mdatagen/metadata-schema.yaml
  cmd/mdatagen/templates/package_test.go.tmpl
  cmd/mdatagen/testdata/with_goleak_ignores.yaml
  cmd/mdatagen/testdata/with_goleak_skip.yaml
  connector/forwardconnector/generated_package_test.go
  exporter/debugexporter/generated_package_test.go
  exporter/loggingexporter/generated_package_test.go
  exporter/nopexporter/generated_package_test.go
  exporter/nopexporter/go.mod
  exporter/otlpexporter/generated_package_test.go
  exporter/otlphttpexporter/generated_package_test.go
  extension/ballastextension/generated_package_test.go
  extension/memorylimiterextension/generated_package_test.go
  extension/memorylimiterextension/go.mod
  extension/zpagesextension/generated_package_test.go
  processor/batchprocessor/generated_package_test.go
  processor/memorylimiterprocessor/generated_package_test.go
  receiver/nopreceiver/generated_package_test.go
  receiver/nopreceiver/go.mod
  receiver/otlpreceiver/generated_package_test.go
Labels: Skip Changelog

#9850 Added default functions for configauth
  .chloggen/configauth-add-NewDefault-func.yaml
  config/configauth/configauth.go
  config/configauth/configauth_test.go
Labels: ready-to-merge

#9992 [chore] Double Windows unit tests timeout
  .github/workflows/build-and-test-windows.yaml
  Makefile.Common
Labels: ci-cd

#9985 Update go.opentelemetry.io/proto/otlp to v1.2.0
  Makefile
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  internal/e2e/go.mod
  internal/e2e/go.sum
  otelcol/go.mod
  otelcol/go.sum
  pdata/internal/data/protogen/metrics/v1/metrics.pb.go
  pdata/internal/data/protogen/trace/v1/trace.pb.go
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
  service/go.mod
  service/go.sum
Labels: dependencies, Skip Changelog

#10000 [cmd/builder] Improve TestVersioning
  cmd/builder/internal/builder/main_test.go
Labels: Skip Changelog

#9999 [cmd/builder] Remove undocumented strictness check
  .github/workflows/build-and-test-windows.yaml
  Makefile.Common
  cmd/builder/internal/builder/main.go
  cmd/builder/internal/builder/main_test.go
Labels: area:builder, Skip Changelog, release:blocker

#9997 [builder] only compare major and minor versions from gomod
  .chloggen/builder-strict-versioning.yaml
  cmd/builder/README.md
  cmd/builder/internal/builder/main.go
Labels: Skip Changelog

#9960 [mdatagen] Rename include/exclude config options
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_config.go
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics.go
  cmd/mdatagen/internal/samplereceiver/internal/metadata/testdata/config.yaml
  cmd/mdatagen/templates/config.go.tmpl
  cmd/mdatagen/templates/metrics.go.tmpl
  cmd/mdatagen/templates/testdata/config.yaml.tmpl
Labels: Skip Changelog

#10027 chore: fix function names in comment
  component/componenttest/otelprometheuschecker.go
  otelcol/collector.go
  receiver/otlpreceiver/otlp_test.go
  receiver/receivertest/contract_checker.go
Labels: Skip Changelog

#10037 [mdatagen] move telemetry into its own file
  cmd/mdatagen/embeded_templates_test.go
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_status.go
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry_test.go
  cmd/mdatagen/main.go
  cmd/mdatagen/main_test.go
  cmd/mdatagen/templates/status.go.tmpl
  cmd/mdatagen/templates/telemetry.go.tmpl
  cmd/mdatagen/templates/telemetry_test.go.tmpl
  connector/forwardconnector/internal/metadata/generated_status.go
  connector/forwardconnector/internal/metadata/generated_telemetry.go
  connector/forwardconnector/internal/metadata/generated_telemetry_test.go
  exporter/debugexporter/internal/metadata/generated_status.go
  exporter/debugexporter/internal/metadata/generated_telemetry.go
  exporter/debugexporter/internal/metadata/generated_telemetry_test.go
  exporter/loggingexporter/internal/metadata/generated_status.go
  exporter/loggingexporter/internal/metadata/generated_telemetry.go
  exporter/loggingexporter/internal/metadata/generated_telemetry_test.go
  exporter/nopexporter/internal/metadata/generated_status.go
  exporter/nopexporter/internal/metadata/generated_telemetry.go
  exporter/nopexporter/internal/metadata/generated_telemetry_test.go
  exporter/otlpexporter/internal/metadata/generated_status.go
  exporter/otlpexporter/internal/metadata/generated_telemetry.go
  exporter/otlpexporter/internal/metadata/generated_telemetry_test.go
  exporter/otlphttpexporter/internal/metadata/generated_status.go
  exporter/otlphttpexporter/internal/metadata/generated_telemetry.go
  exporter/otlphttpexporter/internal/metadata/generated_telemetry_test.go
  extension/ballastextension/internal/metadata/generated_status.go
  extension/ballastextension/internal/metadata/generated_telemetry.go
  extension/ballastextension/internal/metadata/generated_telemetry_test.go
  extension/memorylimiterextension/internal/metadata/generated_status.go
  extension/memorylimiterextension/internal/metadata/generated_telemetry.go
  extension/memorylimiterextension/internal/metadata/generated_telemetry_test.go
  extension/zpagesextension/internal/metadata/generated_status.go
  extension/zpagesextension/internal/metadata/generated_telemetry.go
  extension/zpagesextension/internal/metadata/generated_telemetry_test.go
  processor/batchprocessor/internal/metadata/generated_status.go
  processor/batchprocessor/internal/metadata/generated_telemetry.go
  processor/batchprocessor/internal/metadata/generated_telemetry_test.go
  processor/memorylimiterprocessor/internal/metadata/generated_status.go
  processor/memorylimiterprocessor/internal/metadata/generated_telemetry.go
  processor/memorylimiterprocessor/internal/metadata/generated_telemetry_test.go
  receiver/nopreceiver/internal/metadata/generated_status.go
  receiver/nopreceiver/internal/metadata/generated_telemetry.go
  receiver/nopreceiver/internal/metadata/generated_telemetry_test.go
  receiver/otlpreceiver/internal/metadata/generated_status.go
  receiver/otlpreceiver/internal/metadata/generated_telemetry.go
  receiver/otlpreceiver/internal/metadata/generated_telemetry_test.go
Labels: Skip Changelog

#10053 [chore] group contrib packages
  renovate.json
Labels: Skip Changelog

#9854 [docs/rfc] RFC about environment variables
  docs/rfcs/env-vars.md
Labels: Skip Changelog
