Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-01, with the labels that each got.

#9235 [config/configretry] Allow zero multiplier and arbitrary randomization factor
  .chloggen/addretrysetvalidation.yaml
  config/configretry/backoff.go
  config/configretry/backoff_test.go
Labels: Skip Changelog

#9267 Mark configopaque change as a breaking change
  .chloggen/configopaque_stringer.yaml
Labels: Skip Changelog

#9261 [chore][bug_report.md] Comment out header descriptions
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Skip Contrib Tests

#9284 Update processor README
  processor/README.md
Labels: Skip Changelog

#9271 [configopaque] Implement fmt.GoStringer interface for String
  .chloggen/configopaque_stringer.yaml
  config/configopaque/opaque.go
  config/configopaque/opaque_test.go
Labels: Skip Changelog

#9294 [docs/release] Swap Juraci and me for release duties
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests

#9301 [CONTRIBUTING.md] Proofread the contributing doc
  CONTRIBUTING.md
Labels: Skip Changelog

#9306 [exporter/debug] Update readme to state output is not guaranteed
  exporter/debugexporter/README.md
  exporter/debugexporter/metadata.yaml
Labels: Skip Changelog

#9311 Fixed indentation in YAML for deployment at otel-config.yaml
  examples/k8s/otel-config.yaml
Labels: Skip Changelog

#9320 [service] Refactor telemetry initialization
  service/internal/resource/config.go
  service/internal/resource/config_test.go
  service/service.go
  service/telemetry.go
  service/telemetry_test.go
Labels: Skip Changelog

#9302 [otelcol] Add unit test for implicit config use case
  otelcol/command_test.go
Labels: Skip Changelog

#9350 [docs] Add owner for darwin/amd64
  docs/platform-support.md
Labels: Skip Changelog

#9354 Bump prometheus exporter and b3 propagation
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  component/go.mod
  component/go.sum
  config/configauth/go.sum
  config/configgrpc/go.mod
  config/configgrpc/go.sum
  config/confighttp/go.mod
  config/confighttp/go.sum
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  connector/go.mod
  connector/go.sum
  exporter/debugexporter/go.mod
  exporter/debugexporter/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/auth/go.mod
  extension/auth/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/go.mod
  extension/go.sum
  extension/memorylimiterextension/go.mod
  extension/memorylimiterextension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  go.mod
  go.sum
  internal/e2e/go.mod
  internal/e2e/go.sum
  otelcol/go.mod
  otelcol/go.sum
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/go.mod
  processor/go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/go.mod
  receiver/go.sum
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
  service/go.mod
  service/go.sum
Labels: dependencies

#9358 Replace local dependencies for mdatagen, unblocks release action
  Makefile
  cmd/mdatagen/go.mod
  cmd/mdatagen/go.sum
Labels: Skip Changelog, Skip Contrib Tests

#9307 [receiver/otlp] Refactor error handling into helper
  receiver/otlpreceiver/internal/errors/errors.go
  receiver/otlpreceiver/internal/errors/errors_test.go
  receiver/otlpreceiver/internal/logs/otlp.go
  receiver/otlpreceiver/internal/metrics/otlp.go
  receiver/otlpreceiver/internal/trace/otlp.go
Labels: Skip Changelog

#9317 setup OSSF Scorecard workflow
  .github/workflows/api-compatibility.yml
  .github/workflows/build-and-test-windows.yaml
  .github/workflows/build-and-test.yml
  .github/workflows/builder-integration-test.yaml
  .github/workflows/builder-release.yaml
  .github/workflows/changelog.yml
  .github/workflows/check-links.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contrib-tests.yml
  .github/workflows/generate-semantic-conventions-pr.yaml
  .github/workflows/milestone-add-to-pr.yml
  .github/workflows/perf.yml
  .github/workflows/prepare-release.yml
  .github/workflows/scorecard.yml
  .github/workflows/shellcheck.yml
  .github/workflows/stale-pr.yaml
  .github/workflows/tidy-dependencies.yml
Labels: Skip Changelog, Skip Contrib Tests

#8622 [receiver/otlp, internal, featuregate] Add featuregate to switch to localhost defaults for server-like components
  .chloggen/mx-psi_featuregate-localhost-2.yaml
  .chloggen/mx-psi_featuregate-localhost.yaml
  config/internal/go.mod
  config/internal/go.sum
  config/internal/warning.go
  docs/security-best-practices.md
  featuregate/registry.go
  featuregate/registry_test.go
  internal/localhostgate/featuregate.go
  internal/localhostgate/featuregate_test.go
  receiver/otlpreceiver/README.md
  receiver/otlpreceiver/factory.go
  service/service.go
Labels: receiver/otlp

#9383 docs: add @astencel-sumo as platform owner for `linux/386`
  docs/platform-support.md
Labels: Skip Changelog

#9363 [confignet] Remove deprecated functions
  .chloggen/confignet-remove-deprecated-functions.yaml
  config/confignet/confignet.go
Labels: ready-to-merge

#9386 [confmap]remove stable featuregate
  cmd/mdatagen/go.mod
  cmd/mdatagen/go.sum
  component/go.mod
  component/go.sum
  config/configauth/go.mod
  config/configauth/go.sum
  confmap/go.mod
  confmap/go.sum
  confmap/resolver.go
  connector/forwardconnector/go.mod
  connector/forwardconnector/go.sum
  connector/go.mod
  connector/go.sum
  exporter/debugexporter/go.mod
  exporter/debugexporter/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  extension/auth/go.mod
  extension/auth/go.sum
  extension/ballastextension/go.mod
  extension/ballastextension/go.sum
  extension/go.mod
  extension/go.sum
  extension/memorylimiterextension/go.mod
  extension/memorylimiterextension/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  processor/batchprocessor/go.mod
  processor/batchprocessor/go.sum
  processor/go.mod
  processor/go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  receiver/go.mod
  receiver/go.sum
Labels: Skip Changelog

#9404 [confighttp] Deprecate HTTPClientSettings, use HTTPClientConfig instead
  .chloggen/httpclientsettings_httpclientconfig-breaking.yaml
  .chloggen/httpclientsettings_httpclientconfig.yaml
  config/confighttp/compression_test.go
  config/confighttp/confighttp.go
  config/confighttp/confighttp_test.go
  exporter/otlphttpexporter/config.go
  exporter/otlphttpexporter/config_test.go
  exporter/otlphttpexporter/factory.go
  exporter/otlphttpexporter/factory_test.go
  exporter/otlphttpexporter/otlp.go
  exporter/otlphttpexporter/otlp_test.go
  internal/e2e/otlphttp_test.go
Labels: Skip Contrib Tests

#9384 [service] Move TracerProvider initialization to service/telemetry package
  service/service.go
  service/telemetry.go
  service/telemetry/telemetry.go
Labels: Skip Changelog

#9433 [confighttp] move implementation checks to test files
  config/confighttp/clientinfohandler.go
  config/confighttp/clientinfohandler_test.go
Labels: Skip Changelog

#9432 [configtelemetry] move implementation checks to test files
  config/configtelemetry/configtelemetry.go
  config/configtelemetry/configtelemetry_test.go
Labels: Skip Changelog

#9449 Parallelizing contrib check
  .github/workflows/contrib-tests.yml
Labels: Skip Changelog
