Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-12, with the labels that each got.

#10543 [otelcol] Tell all loggers to encode timestamps in ISO8601.
  .chloggen/igorpeshansky-windows-logger-timestamps.yaml
  otelcol/collector_windows.go
  service/telemetry/logger.go
Labels: ready-to-merge

#11794 [chore] disable generate for now
  Makefile
Labels: Skip Changelog, release:blocker

#11738 [chore][docs/rfc] Add text regarding conversations
  docs/rfcs/README.md
Labels: rfc:final-comment-period

#11797 Fix merge queue CI
  .github/workflows/api-compatibility.yml
  .github/workflows/changelog.yml
Labels: Skip Changelog

#11793 Generate `replaces` automatically in builder-integration-test
  cmd/builder/test/core.builder.yaml
  cmd/builder/test/test.sh
Labels: Skip Changelog

#11810 Enable but skip `changelog` workflow in merge queue
  .github/workflows/changelog.yml
Labels: Skip Changelog, Skip Contrib Tests

#11836 [docs] Add guidelines for experimental modules naming
  docs/coding-guidelines.md
Labels: Skip Changelog

#11870 [chore] Skip TestDefaultBatcher_NoSplit_WithTimeout on Windows
  exporter/internal/queue/default_batcher_test.go
Labels: flaky test

#11849 [chore] Fix "Prepare Release" action
  .github/workflows/prepare-release.yml
  .github/workflows/scripts/release-prepare-release.sh
Labels: ready-to-merge, Skip Contrib Tests

#11884 [chore] fix xconsumer mod versions
  cmd/mdatagen/go.mod
  cmd/otelcorecol/go.mod
  connector/connectorprofiles/go.mod
  connector/connectortest/go.mod
  connector/forwardconnector/go.mod
  connector/go.mod
  consumer/consumertest/go.mod
  exporter/debugexporter/go.mod
  exporter/exporterhelper/exporterhelperprofiles/go.mod
  exporter/exporterprofiles/go.mod
  exporter/exportertest/go.mod
  exporter/go.mod
  exporter/nopexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  internal/e2e/go.mod
  internal/fanoutconsumer/go.mod
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  processor/batchprocessor/go.mod
  processor/go.mod
  processor/memorylimiterprocessor/go.mod
  processor/processorhelper/processorhelperprofiles/go.mod
  processor/processorprofiles/go.mod
  processor/processortest/go.mod
  receiver/go.mod
  receiver/nopreceiver/go.mod
  receiver/otlpreceiver/go.mod
  receiver/receiverprofiles/go.mod
  receiver/receivertest/go.mod
  receiver/xreceiver/go.mod
  service/go.mod
Labels: release:blocker

#11886 [chore] Do not exclude deprecated profiles modules
  versions.yaml
Labels: release:blocker

#11874 [chore]: enable gofumpt globally
  .golangci.yml
  Makefile.Common
  internal/tools/go.mod
  internal/tools/tools.go
Labels: ci-cd

#11888 Deprecate pipelineprofiles module in favor of xpipeline
  .chloggen/deprecate-pipelieneprofiles.yaml
  cmd/builder/internal/builder/main_test.go
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  connector/connectorprofiles/connector.go
  connector/connectorprofiles/connector_test.go
  connector/connectorprofiles/go.mod
  connector/connectorprofiles/profiles_router_test.go
  connector/connectortest/go.mod
  connector/forwardconnector/go.mod
  exporter/debugexporter/go.mod
  exporter/exporterhelper/exporterhelperprofiles/go.mod
  exporter/exporterhelper/exporterhelperprofiles/profiles.go
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  internal/e2e/go.mod
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  pipeline/pipelineprofiles/config.go
  pipeline/xpipeline/Makefile
  pipeline/xpipeline/config.go
  pipeline/xpipeline/go.mod
  pipeline/xpipeline/go.sum
  service/go.mod
  service/internal/builders/connector.go
  service/internal/builders/connector_test.go
  service/internal/graph/connector.go
  service/internal/graph/exporter.go
  service/internal/graph/graph.go
  service/internal/graph/graph_test.go
  service/internal/graph/processor.go
  service/internal/graph/receiver.go
  service/internal/graph/util_test.go
  service/pipelines/config.go
  service/pipelines/config_test.go
  service/service_test.go
  versions.yaml
Labels: release:blocker

#11893 [README] links caption
  README.md
  docs/security-best-practices.md
Labels: Skip Changelog

#11894 [chore] Update version of all new experimental modules to latest commit
  cmd/mdatagen/go.mod
  cmd/otelcorecol/go.mod
  connector/connectorprofiles/go.mod
  connector/connectortest/go.mod
  connector/forwardconnector/go.mod
  connector/go.mod
  connector/xconnector/go.mod
  consumer/consumererror/consumererrorprofiles/go.mod
  consumer/consumerprofiles/go.mod
  consumer/consumertest/go.mod
  exporter/debugexporter/go.mod
  exporter/exporterhelper/exporterhelperprofiles/go.mod
  exporter/exporterhelper/xexporterhelper/go.mod
  exporter/exporterprofiles/go.mod
  exporter/exportertest/go.mod
  exporter/go.mod
  exporter/nopexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  exporter/xexporter/go.mod
  internal/e2e/go.mod
  internal/fanoutconsumer/go.mod
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  processor/batchprocessor/go.mod
  processor/go.mod
  processor/memorylimiterprocessor/go.mod
  processor/processorhelper/processorhelperprofiles/go.mod
  processor/processorhelper/xprocessorhelper/go.mod
  processor/processorprofiles/go.mod
  processor/processortest/go.mod
  processor/xprocessor/go.mod
  receiver/go.mod
  receiver/nopreceiver/go.mod
  receiver/otlpreceiver/go.mod
  receiver/receiverprofiles/go.mod
  receiver/receivertest/go.mod
  receiver/xreceiver/go.mod
  service/go.mod
Labels: release:blocker, Skip Contrib Tests

#11897 [chore] Update versions of the new experimental modules
  cmd/mdatagen/go.mod
  cmd/otelcorecol/go.mod
  connector/connectorprofiles/go.mod
  connector/connectortest/go.mod
  connector/forwardconnector/go.mod
  connector/go.mod
  connector/xconnector/go.mod
  consumer/consumererror/consumererrorprofiles/go.mod
  consumer/consumerprofiles/go.mod
  consumer/consumertest/go.mod
  exporter/debugexporter/go.mod
  exporter/exporterhelper/exporterhelperprofiles/go.mod
  exporter/exporterhelper/xexporterhelper/go.mod
  exporter/exporterprofiles/go.mod
  exporter/exportertest/go.mod
  exporter/go.mod
  exporter/nopexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  exporter/xexporter/go.mod
  internal/e2e/go.mod
  internal/fanoutconsumer/go.mod
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  processor/batchprocessor/go.mod
  processor/go.mod
  processor/memorylimiterprocessor/go.mod
  processor/processorhelper/processorhelperprofiles/go.mod
  processor/processorhelper/xprocessorhelper/go.mod
  processor/processorprofiles/go.mod
  processor/processortest/go.mod
  processor/xprocessor/go.mod
  receiver/go.mod
  receiver/nopreceiver/go.mod
  receiver/otlpreceiver/go.mod
  receiver/receiverprofiles/go.mod
  receiver/receivertest/go.mod
  receiver/xreceiver/go.mod
  service/go.mod
Labels: Skip Contrib Tests

#11772 Define observability requirements for stable components
  docs/component-stability.md
Labels: discussion-needed, Skip Changelog, Skip Contrib Tests

#11908 [chore][release.md] mention release blockers
  docs/release.md
Labels: enhancement, Skip Changelog, release, Skip Contrib Tests, release:retro

#11909 [chore] put back replace and add new packages in builder yaml
  cmd/builder/test/core.builder.yaml
  cmd/builder/test/test.sh
Labels: Skip Changelog, release, release:blocker, Skip Contrib Tests

#10958 [service/internal] Allow components to transition from PermanentError to Stopping
  docs/component-status.md
  docs/img/component-status-state-diagram.png
  service/internal/graph/lifecycle_test.go
  service/internal/status/status.go
  service/internal/status/status_test.go
Labels: ready-to-merge, Skip Changelog

#11949 [chore] Update README.md to correctly reflect OTLP Protocol version
  README.md
Labels: Skip Contrib Tests

#11946 [chore] Use gotestsum wrapper for go tests
  Makefile.Common
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: ci-cd, Skip Contrib Tests

#11826 [interna/sharedcomponent] Use a ring buffer to restrict remembered status count
  .chloggen/fix-sharedcomponent-memory-issue.yaml
  internal/sharedcomponent/sharedcomponent.go
Labels: ready-to-merge

#11925 [chore]: clean up misspell configuration
  .golangci.yml
Labels: ci-cd, Skip Changelog, Skip Contrib Tests

#11968 [chore] missed one update
  internal/tools/go.mod
  internal/tools/go.sum
Labels: Skip Changelog, Skip Contrib Tests

#11970 [chore] call npm with ci instead of install
  .github/workflows/changelog.yml
  .github/workflows/check-links.yaml
Labels: Skip Changelog, Skip Contrib Tests

#11963 [chore] Create gotest-with-junit Makefile target
  .github/workflows/build-and-test.yml
  Makefile
  Makefile.Common
Labels: ci-cd, Skip Contrib Tests

#11938 [chore][release.md] checkout release branch to the correct commit & update release schedule
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests, release:retro

#11972 [chore] restrict permissions on workflow
  .github/workflows/milestone-add-to-pr.yml
Labels: ci-cd
