Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-08, with the labels that each got.

#10788 Make @pjanotti owner of windows/amd64
  docs/platform-support.md
Labels: Skip Changelog

#10817 Add missing CHANGELOG.md entry for v0.106.1
  CHANGELOG.md
Labels: Skip Changelog

#10790 add fuzz test for receiver
  receiver/otlpreceiver/fuzz_test.go
Labels: Skip Changelog

#10508 [confmap] Set confmap.unifyEnvVarExpansion feature gate to stable
  .chloggen/unify-env-var-gate-stable.yaml
  confmap/converter/expandconverter/expand_test.go
  confmap/converter/expandconverter/go.mod
  confmap/internal/e2e/expand_test.go
  confmap/internal/e2e/go.mod
  confmap/internal/e2e/testdata/expand-escaped-env.yaml
  confmap/internal/e2e/types_test.go
  confmap/resolver.go
  internal/globalgates/globalgates.go
  otelcol/command_test.go
  otelcol/command_validate_test.go
Labels: release:blocker

#10510 [confmap] Deprecate expandconverter
  .chloggen/deprecate-expandconverter-2.yaml
  .chloggen/deprecate-expandconverter-3.yaml
  .chloggen/deprecate-expandconverter.yaml
  cmd/builder/README.md
  cmd/builder/internal/builder/main_test.go
  cmd/builder/internal/builder/templates/go.mod.tmpl
  cmd/builder/internal/builder/templates/main.go.tmpl
  cmd/builder/test/core.builder.yaml
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/main.go
  confmap/converter/expandconverter/expand.go
  confmap/converter/expandconverter/expand_test.go
  confmap/converter/expandconverter/go.mod
  otelcol/otelcoltest/config.go
  otelcol/otelcoltest/go.mod
Labels: release:blocker

#10831 [chore] Skip a few flaky batch sender tests on Windows
  exporter/exporterhelper/batch_sender_test.go
Labels: Skip Changelog, Skip Contrib Tests, os:windows

#10676 [confighttp] Add `NewDefaultCORSConfig` function
  .chloggen/new_cors_default_config.yaml
  config/confighttp/confighttp.go
  config/confighttp/confighttp_test.go
Labels: ready-to-merge

#10595 [builder] fix the TestGenerateInvalidOutputPath
  cmd/builder/internal/builder/main_test.go
Labels: ready-to-merge, Skip Changelog

#10767 [cmd/builder] clarify mismatched versions in the warning message
  cmd/builder/internal/builder/main.go
Labels: Skip Changelog, Skip Contrib Tests

#10848 [mdatagen] move ScopeName to generated_status
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_status.go
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
  cmd/mdatagen/main_test.go
  cmd/mdatagen/templates/status.go.tmpl
  cmd/mdatagen/templates/telemetry.go.tmpl
  connector/forwardconnector/internal/metadata/generated_status.go
  exporter/debugexporter/internal/metadata/generated_status.go
  exporter/exporterhelper/internal/metadata/generated_telemetry.go
  exporter/loggingexporter/internal/metadata/generated_status.go
  exporter/nopexporter/internal/metadata/generated_status.go
  exporter/otlpexporter/internal/metadata/generated_status.go
  exporter/otlphttpexporter/internal/metadata/generated_status.go
  extension/ballastextension/internal/metadata/generated_status.go
  extension/memorylimiterextension/internal/metadata/generated_status.go
  extension/zpagesextension/internal/metadata/generated_status.go
  processor/batchprocessor/internal/metadata/generated_status.go
  processor/batchprocessor/internal/metadata/generated_telemetry.go
  processor/memorylimiterprocessor/internal/metadata/generated_status.go
  processor/processorhelper/internal/metadata/generated_telemetry.go
  receiver/nopreceiver/internal/metadata/generated_status.go
  receiver/otlpreceiver/internal/metadata/generated_status.go
  receiver/receiverhelper/internal/metadata/generated_telemetry.go
  receiver/scraperhelper/internal/metadata/generated_telemetry.go
  service/internal/metadata/generated_telemetry.go
Labels: Skip Changelog, Skip Contrib Tests

#10889 chore (deps): migrate rand to rand/v2
  .golangci.yml
  exporter/exportertest/mock_consumer.go
  receiver/receivertest/contract_checker.go
Labels: Skip Changelog

#10894 ballastextension: fix comment typo
  extension/ballastextension/factory.go
Labels: Skip Changelog

#10582 [chore] Clarify config removal in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready-to-merge

#10896 fix replace words in doc
  connector/README.md
Labels: Skip Changelog, Skip Contrib Tests

#10898 [chore] add status table to mdatagen
  cmd/mdatagen/README.md
Labels: Skip Contrib Tests

#10905 [chore] pin version for npm tooling
  .github/workflows/changelog.yml
  .github/workflows/check-links.yaml
  .gitignore
  package.json
Labels: ci-cd, Skip Contrib Tests

#10867 chore(builder): Update readme
  cmd/builder/README.md
Labels: ready-to-merge, Skip Changelog, Skip Contrib Tests

#10695 Document collector's internal telemetry
  docs/observability.md
Labels: collector-telemetry, Skip Changelog, Skip Contrib Tests

#10495 [component] Make InstanceID immutable
  .chloggen/immutable-instance-id.yaml
  component/componentstatus/instance.go
  component/componentstatus/instance_test.go
  internal/e2e/status_test.go
  otelcol/collector_test.go
  service/extensions/extensions.go
  service/internal/graph/graph.go
  service/internal/graph/graph_test.go
Labels: Skip Contrib Tests

#10413 [component] Component status reporting rfc
  docs/rfcs/component-status-reporting.md
Labels: ready-to-merge, Skip Changelog

#10951 remove unnecessary level
  exporter/exporterhelper/obsexporter.go
  receiver/receiverhelper/obsreport.go
  receiver/scraperhelper/obsreport.go
Labels: Skip Changelog

#10920 [confmap] Mark module as stable
  .chloggen/mx-psi_confmap-1.0.yaml
  confmap/confmap_test.go
  versions.yaml
Labels: release:blocker

#10966 [confmaptest] Add a test on empty slice to nil
  confmap/confmaptest/configtest_test.go
  confmap/confmaptest/testdata/empty-slice.yaml
Labels: Skip Changelog, Skip Contrib Tests

#10961 fix(renovate): add package rule for disabling toolchain updates
  renovate.json
Labels: ci-cd, Skip Changelog

#10773 [otelcol] Fix grpclogger to capture correct caller location
  otelcol/internal/grpclog/logger.go
  otelcol/internal/grpclog/logger_test.go
Labels: Skip Changelog

#10717 [chore] delete unused method on nopHost
  component/componenttest/nop_host.go
Labels: on hold

#10993 [chore]: enable bool-compare rule from testifylint
  .golangci.yml
  config/confighttp/confighttp_test.go
  exporter/otlphttpexporter/factory_test.go
  internal/cgroups/cgroups_test.go
  pdata/pcommon/value_test.go
  processor/batchprocessor/splitmetrics_test.go
Labels: ci-cd

#11017 [component] Remove incorrect comment on Factory interface
  component/component.go
Labels: Skip Changelog

#11016 [extension/zpages] document unsupported none level
  extension/zpagesextension/README.md
  extension/zpagesextension/metadata.yaml
Labels: Skip Changelog, Skip Contrib Tests

#11002 [configtelemetry] Mark module as stable
  .chloggen/mx-psi_configtelemetry-1.0.yaml
  versions.yaml
Labels: release:blocker
