Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-07, with the labels that each got.

#10450 [otlpexporter] support validation for dns:// and dns:///
  .chloggen/codeboten_remove-additional-slash.yaml
  exporter/otlpexporter/config.go
  exporter/otlpexporter/config_test.go
Labels: ready-to-merge

#10441 [chore] Fix comments and clarify docs on `config/configtls`
  config/configtls/README.md
  config/configtls/configtls.go
Labels: area:config

#10415 [service] add internal factory method for meter provider
  service/telemetry/internal/factory.go
Labels: Stale, Skip Changelog

#10486 [mdatagen] bugfix: fix generated package test when skipping goleak, because os package import is forgotten
  cmd/mdatagen/templates/package_test.go.tmpl
Labels: Skip Changelog

#10560 [confmap] Fix bug where expand didn't honor escaping
  .chloggen/confmap-fix-escape-bug.yaml
  confmap/expand.go
  confmap/expand_test.go
  confmap/resolver.go
  confmap/testdata/expand-escaped-env.yaml
Labels: release:blocker

#10554 Promote confmap.strictlyTypedInput feature gate to beta
  .chloggen/mx-psi_enable-strict-types.yaml
  confmap/expand_test.go
  confmap/internal/e2e/types_test.go
  exporter/otlpexporter/testdata/config.yaml
  exporter/otlphttpexporter/testdata/config.yaml
  internal/featuregates/featuregates.go
  otelcol/unmarshaler_test.go
Labels: release:blocker

#10540 [chore] use macos-14 for arm testing
  .github/workflows/build-and-test-arm.yml
  docs/platform-support.md
Labels: arm64, Run ARM

#10611 [chore] reenable arm testing
  .github/workflows/build-and-test-arm.yml
Labels: Run ARM

#10616 [chore] update arm workflow to run both macos and linux
  .github/workflows/build-and-test-arm.yml
  docs/platform-support.md
Labels: Run ARM

#10530 Move receiver into an internal package, in preparation for profiles
  receiver/builder.go
  receiver/internal/factory.go
  receiver/internal/logs.go
  receiver/internal/metrics.go
  receiver/internal/receiver.go
  receiver/internal/traces.go
  receiver/receiver.go
Labels: Skip Changelog

#10527 Move exporter into an internal package, in preparation for profiles
  exporter/builder.go
  exporter/exporter.go
  exporter/internal/exporter.go
  exporter/internal/factory.go
  exporter/internal/logs.go
  exporter/internal/metrics.go
  exporter/internal/traces.go
Labels: Skip Changelog

#10526 Move processor into an internal package, in preparation for profiles
  processor/builder.go
  processor/internal/factory.go
  processor/internal/logs.go
  processor/internal/metrics.go
  processor/internal/processor.go
  processor/internal/traces.go
  processor/processor.go
Labels: Skip Changelog

#10440 Improve logging of component start errors
  service/extensions/extensions.go
  service/internal/graph/graph.go
Labels: Skip Changelog

#10562 [chore] Improve docs for server-like receivers in kubernetes and docker
  docs/security-best-practices.md
Labels: Skip Changelog

#10685 [confighttp, configgrpc] Remove experimental note on IncludeMetadata
  .chloggen/experimental_include_metadata.yaml
  config/configgrpc/configgrpc.go
  config/confighttp/confighttp.go
Labels: needs-review-from-stability-wg

#10716 [confmap] Fix expansion of escaped environment variables
  .chloggen/fix-env-var-double-escaping.yaml
  confmap/converter/expandconverter/expand.go
  confmap/expand_test.go
  confmap/internal/e2e/expand_test.go
  confmap/internal/e2e/go.mod
  confmap/internal/e2e/testdata/expand-escaped-env.yaml
  confmap/resolver.go
  confmap/testdata/expand-escaped-env.yaml
Labels: release:blocker

#10618 [confmap] Store original string in confmap.Conf
  .chloggen/mx-psi_string-value-for-string-fields.yaml
  confmap/confmap.go
  confmap/confmap_test.go
  confmap/expand.go
  confmap/internal/e2e/fuzz_test.go
  confmap/internal/e2e/types_test.go
  confmap/provider.go
  confmap/provider_test.go
  confmap/resolver.go
  docs/rfcs/env-vars.md
Labels: release:blocker

#10697 Add fuzz tests for unmarshaling routines
  pdata/plog/fuzz_test.go
  pdata/plog/plogotlp/fuzz_test.go
  pdata/pmetric/fuzz_test.go
  pdata/pmetric/pmetricotlp/fuzz_test.go
  pdata/ptrace/fuzz_test.go
  pdata/ptrace/ptraceotlp/fuzz_test.go
Labels: Skip Changelog

#10686 [confighttp] delete `ClientConfig.CustomRoundTripper`
  .chloggen/delete_custom_roundtripper.yaml
  config/confighttp/confighttp.go
Labels: ready-to-merge

#9805 [client] add new module `go.opentelemetry.io/collector/client`
  .chloggen/client_module.yaml
  Makefile
  client/Makefile
  client/go.mod
  client/go.sum
  cmd/builder/internal/builder/main_test.go
  cmd/builder/test/core.builder.yaml
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  config/configgrpc/go.mod
  config/confighttp/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/zpagesextension/go.mod
  internal/e2e/go.mod
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  processor/batchprocessor/go.mod
  receiver/otlpreceiver/go.mod
  service/go.mod
  versions.yaml
Labels: release:blocker

#10709 Deprecate component.Host.GetFactory
  .chloggen/component-deprecate-GetFactory.yaml
  component/componenttest/nop_host_test.go
  component/host.go
Labels: release:blocker

#10739 [chore] fix typo in release.md
  docs/release.md
Labels: Skip Changelog

#10757 Merge release/v0.106.x to main (with fixing merge conflicts)
  client/go.mod
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/config/default.yaml
  cmd/builder/test/core.builder.yaml
  cmd/mdatagen/go.mod
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/components.go
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/main.go
  component/componentprofiles/go.mod
  component/go.mod
  config/configauth/go.mod
  config/configgrpc/go.mod
  config/confighttp/go.mod
  config/internal/go.mod
  confmap/converter/expandconverter/go.mod
  confmap/go.mod
  confmap/internal/e2e/go.mod
  confmap/provider/envprovider/go.mod
  confmap/provider/fileprovider/go.mod
  confmap/provider/httpprovider/go.mod
  confmap/provider/httpsprovider/go.mod
  confmap/provider/yamlprovider/go.mod
  connector/forwardconnector/go.mod
  connector/go.mod
  consumer/consumerprofiles/go.mod
  consumer/consumertest/go.mod
  consumer/go.mod
  exporter/debugexporter/go.mod
  exporter/exporterprofiles/go.mod
  exporter/go.mod
  exporter/loggingexporter/go.mod
  exporter/nopexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/auth/go.mod
  extension/ballastextension/go.mod
  extension/go.mod
  extension/memorylimiterextension/go.mod
  extension/zpagesextension/go.mod
  filter/go.mod
  go.mod
  internal/e2e/go.mod
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  pdata/testdata/go.mod
  processor/batchprocessor/go.mod
  processor/go.mod
  processor/memorylimiterprocessor/go.mod
  processor/processorprofiles/go.mod
  receiver/go.mod
  receiver/nopreceiver/go.mod
  receiver/otlpreceiver/go.mod
  service/go.mod
  versions.yaml
Labels: Skip Changelog

#10643 [chore] Explicitly note that service and otelcol are not part of 1.0
  docs/ga-roadmap.md
Labels: needs-review-from-stability-wg

#10760 minor grammar and spelling improvements to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Skip Changelog
