Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-06, with the labels that each got.

#10254 Document TLS option Watch client CA
  config/configtls/README.md
Labels: ready-to-merge, Skip Changelog

#9880 Updated public methods in configauth
  .chloggen/configauth-add-context-to-public-funcs.yaml
  config/configauth/configauth.go
  config/configauth/configauth_test.go
  config/configgrpc/configgrpc.go
  config/configgrpc/configgrpc_test.go
  config/confighttp/confighttp.go
Labels: ready-to-merge

#10314 [mdatagen] make meter a struct member of telemetryBuilder
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
  cmd/mdatagen/templates/telemetry.go.tmpl
  exporter/exporterhelper/internal/metadata/generated_telemetry.go
  processor/batchprocessor/internal/metadata/generated_telemetry.go
  processor/processorhelper/internal/metadata/generated_telemetry.go
  receiver/receiverhelper/internal/metadata/generated_telemetry.go
  receiver/scraperhelper/internal/metadata/generated_telemetry.go
Labels: Skip Changelog

#10250 [exporter/debug] disable sampling by default
  .chloggen/debug-exporter-disable-sampling.yaml
  exporter/debugexporter/README.md
  exporter/debugexporter/factory.go
Labels: exporter/debug

#10318 [exporterhelper] move queue metrics to mdatagen
  exporter/exporterhelper/common.go
  exporter/exporterhelper/documentation.md
  exporter/exporterhelper/internal/metadata/generated_telemetry.go
  exporter/exporterhelper/metadata.yaml
  exporter/exporterhelper/obsexporter.go
  exporter/exporterhelper/queue_sender.go
  exporter/exporterhelper/queue_sender_test.go
Labels: Skip Changelog

#10380 [confmap] Write up note about null maps
  confmap/README.md
  docs/troubleshooting.md
Labels: Skip Changelog

#10395 [pdata] Change mode for generated files
  pdata/internal/cmd/pdatagen/internal/packages.go
Labels: Skip Changelog

#10398 [chore] link release managers
  docs/release.md
Labels: Skip Contrib Tests

#10403 [confmap] remove bool logic from expandURI
  confmap/expand.go
Labels: Skip Changelog

#10416 [chore] more CreateSettings renames
  service/telemetry/internal/factory.go
  service/telemetry/telemetry.go
Labels: Skip Changelog

#10428 Add goreleaser check and attempt update
  .github/workflows/check-goreleaser.yaml
  cmd/builder/.goreleaser.yml
Labels: Skip Changelog, Skip Contrib Tests

#10429 Change builder release trigger to module tag
  .github/workflows/builder-release.yaml
Labels: Skip Changelog, Skip Contrib Tests

#10431 Update release instructions
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests

#10439 Docs - Update contrib release step 1
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests

#10422 [component] Status Reporting Documentation
  component/telemetry.go
  docs/component-status.md
  docs/img/component-status-event-generation.png
  docs/img/component-status-runtime-states.png
  docs/img/component-status-state-diagram.png
Labels: Skip Changelog

#10225 [exporter/debug] format log records as one-liners in `normal` verbosity
  .chloggen/debug-exporter-normal-verbosity-logs.yaml
  exporter/debugexporter/README.md
  exporter/debugexporter/exporter.go
  exporter/debugexporter/internal/normal/logs.go
  exporter/debugexporter/internal/normal/logs_test.go
Labels: Stale, exporter/debug

#10280 [exporter/debug] format spans as one-liners in `normal` verbosity
  .chloggen/debug-exporter-normal-verbosity-traces.yaml
  exporter/debugexporter/README.md
  exporter/debugexporter/exporter.go
  exporter/debugexporter/internal/normal/common.go
  exporter/debugexporter/internal/normal/logs.go
  exporter/debugexporter/internal/normal/traces.go
  exporter/debugexporter/internal/normal/traces_test.go
Labels: exporter/debug

#10462 [exporter/debug] format metric data points as one-liners in `normal` verbosity
  .chloggen/debug-exporter-normal-verbosity-logs.yaml
  .chloggen/debug-exporter-normal-verbosity.yaml
  exporter/debugexporter/README.md
  exporter/debugexporter/exporter.go
  exporter/debugexporter/internal/normal/metrics.go
  exporter/debugexporter/internal/normal/metrics_test.go
Labels: Skip Changelog

#10227 [exporter/debug] add option `use_internal_logger`
  .chloggen/debug-exporter-use-internal-logger.yaml
  exporter/debugexporter/README.md
  exporter/debugexporter/config.go
  exporter/debugexporter/exporter_test.go
  exporter/debugexporter/factory.go
  exporter/debugexporter/testdata/config_verbosity.yaml
Labels: exporter/debug

#10454 [docs] Clean up internal observability docs
  README.md
  docs/monitoring.md
  docs/observability.md
  docs/troubleshooting.md
  docs/vision.md
  exporter/debugexporter/README.md
Labels: Skip Changelog

#10375 RFC: Experimental profiling
  docs/rfcs/experimental-profiling.md
Labels: Skip Changelog
