Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-10, with the labels that each got.

#11314 (batchprocessor): Multi/single-shard consistent start method and field names
  processor/batchprocessor/batch_processor.go
Labels: Skip Changelog

#11253 [component] Remove deprecated DataType
  .chloggen/pipeline-continue-refactor.yaml
  component/component.go
  component/config.go
  component/go.mod
  config/configauth/go.mod
  config/configgrpc/go.mod
  config/confighttp/go.mod
  extension/auth/go.mod
  extension/experimental/storage/go.mod
  extension/extensioncapabilities/go.mod
  extension/go.mod
  extension/memorylimiterextension/go.mod
  service/pipelines/config_test.go
Labels: release:blocker

#11326 Fix false fuzzer crash
  receiver/otlpreceiver/fuzz_test.go
Labels: Skip Changelog, Skip Contrib Tests

#11037 [exporter/logging] Remove logging exporter
  .chloggen/remove-logging-exporter.yaml
  Makefile
  cmd/builder/internal/config/default.yaml
  cmd/builder/test/core.builder.yaml
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/components.go
  cmd/otelcorecol/go.mod
  component/config_test.go
  connector/forwardconnector/README.md
  exporter/debugexporter/README.md
  exporter/debugexporter/config.go
  exporter/debugexporter/exporter.go
  exporter/loggingexporter/Makefile
  exporter/loggingexporter/README.md
  exporter/loggingexporter/config.go
  exporter/loggingexporter/config_test.go
  exporter/loggingexporter/doc.go
  exporter/loggingexporter/factory.go
  exporter/loggingexporter/factory_test.go
  exporter/loggingexporter/generated_component_test.go
  exporter/loggingexporter/generated_package_test.go
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/go.sum
  exporter/loggingexporter/internal/metadata/generated_status.go
  exporter/loggingexporter/metadata.yaml
  exporter/loggingexporter/testdata/config_loglevel.yaml
  exporter/loggingexporter/testdata/config_loglevel_typo.yaml
  exporter/loggingexporter/testdata/config_verbosity.yaml
  exporter/loggingexporter/testdata/invalid_verbosity_loglevel.yaml
  exporter/loggingexporter/testdata/loglevel_info.yaml
  otelcol/internal/configunmarshaler/configs.go
  otelcol/internal/configunmarshaler/configs_test.go
  versions.yaml
Labels: release:blocker

#11349 Fix data race condition, concurrent writes to the err variable, causes Undefined Behavior
  .chloggen/fix-ub-proc-helper.yaml
  processor/processorhelper/logs.go
  processor/processorhelper/logs_test.go
  processor/processorhelper/metrics.go
  processor/processorhelper/metrics_test.go
  processor/processorhelper/traces.go
  processor/processorhelper/traces_test.go
Labels: release:blocker

#11338 [exporter] internal/persistent_queue::OnProcessingFinished is changed to a class function instead of a callback
  exporter/internal/queue/bounded_memory_queue.go
  exporter/internal/queue/persistent_queue.go
  exporter/internal/queue/persistent_queue_test.go
  exporter/internal/queue/queue.go
Labels: Skip Changelog

#11378 Update README.md
  README.md
Labels: Skip Changelog

#11388 fix version init
  cmd/builder/internal/version.go
Labels: ready-to-merge, Skip Changelog, Skip Contrib Tests

#11376 Issue #11307- Deprecate and remove processorhelper.NewUnhealthyProcessorCreateSettings
  .chloggen/processortest-deprecated-removed-func.yaml
  processor/processortest/unhealthy_processor.go
Labels: Skip Contrib Tests

#11365 Remove extra allocation when record metrics
  exporter/exporterhelper/internal/obsexporter.go
  processor/batchprocessor/metrics.go
  processor/memorylimiterprocessor/obsreport.go
  processor/processorhelper/obsreport.go
  receiver/receiverhelper/obsreport.go
  receiver/scraperhelper/obsreport.go
Labels: Skip Changelog

#11333 [chore][graph] Remove connectorNode's separate baseConsumer
  service/internal/graph/connector.go
  service/internal/graph/consumer.go
  service/internal/graph/graph_test.go
  service/internal/graph/util_test.go
Labels: ready-to-merge

#11348 Fix typos
  cmd/builder/internal/command.go
  cmd/mdatagen/internal/command.go
  cmd/mdatagen/internal/embedded_templates.go
  cmd/mdatagen/internal/embedded_templates_test.go
  cmd/mdatagen/internal/templates/documentation.md.tmpl
  config/configgrpc/configgrpc.go
  config/configtls/configtls_test.go
  confmap/confmap.go
  confmap/provider/httpprovider/README.md
  confmap/provider/httpsprovider/README.md
  confmap/resolver_test.go
  docs/rfcs/component-status-reporting.md
  exporter/exportertest/mock_consumer_test.go
  internal/fanoutconsumer/logs.go
  internal/fanoutconsumer/metrics.go
  internal/fanoutconsumer/profiles.go
  internal/fanoutconsumer/traces.go
  internal/globalgates/globalgates.go
  internal/memorylimiter/memorylimiter_test.go
  otelcol/collector_test.go
  pdata/internal/json/enum.go
  pdata/pprofile/profileid.go
  processor/batchprocessor/batch_processor.go
  semconv/v1.10.0/generated_resource.go
  semconv/v1.11.0/generated_resource.go
  semconv/v1.12.0/generated_resource.go
  semconv/v1.13.0/generated_resource.go
  semconv/v1.16.0/generated_resource.go
  semconv/v1.17.0/generated_resource.go
  semconv/v1.18.0/generated_resource.go
  semconv/v1.21.0/generated_resource.go
  semconv/v1.22.0/generated_resource.go
  semconv/v1.25.0/generated_attribute_group.go
  semconv/v1.26.0/generated_attribute_group.go
  semconv/v1.27.0/generated_attribute_group.go
  semconv/v1.5.0/generated_resource.go
  semconv/v1.6.1/generated_resource.go
  semconv/v1.7.0/generated_resource.go
  semconv/v1.8.0/generated_resource.go
  semconv/v1.9.0/generated_resource.go
  service/extensions/extensions_test.go
  service/extensions/graph.go
  service/internal/graph/receiver.go
  service/telemetry/config.go
  service/telemetry/internal/otelinit/config_test.go
Labels: Skip Changelog

#11352 Improve coverage of mdatagen
  cmd/mdatagen/internal/command.go
  cmd/mdatagen/internal/command_test.go
  cmd/mdatagen/internal/testdata/basic_connector.yaml
  cmd/mdatagen/internal/testdata/basic_receiver.yaml
  cmd/mdatagen/internal/testdata/readme_with_status_codeowners.md
Labels: Skip Changelog

#10941 [service/internal] Remove Ready from status.Reporter
  service/extensions/extensions_test.go
  service/internal/graph/lifecycle_test.go
  service/internal/status/status.go
  service/internal/status/status_test.go
  service/internal/status/statustest/statustest_test.go
  service/service.go
Labels: ready-to-merge, Skip Changelog

#11396 [exporter] exporter queue Read()
  exporter/internal/queue/bounded_memory_queue.go
  exporter/internal/queue/bounded_memory_queue_test.go
  exporter/internal/queue/consumers.go
  exporter/internal/queue/persistent_queue.go
  exporter/internal/queue/persistent_queue_test.go
  exporter/internal/queue/queue.go
  exporter/internal/queue/queue_test.go
Labels: Skip Changelog

#11472 chore: minor code cleanup
  service/service.go
  service/telemetry/attributes.go
Labels: Skip Changelog, Skip Contrib Tests

#11473 [chore] gprc -> grpc typos
  exporter/otlpexporter/doc.go
  service/telemetry/metrics_test.go
Labels: Skip Contrib Tests

#11416 [docs/rfc] Define RFC merge process
  docs/rfcs/README.md
Labels: Skip Changelog, Skip Contrib Tests

#11498 [chore][.github/ISSUE_TEMPLATE] Update link to coding guidelines
  .github/ISSUE_TEMPLATE/stabilization.md
Labels: Skip Changelog

#11539 [chore] Use NopTelemetrySettings instead of mock providers
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry_test.go
  cmd/mdatagen/internal/templates/telemetry_test.go.tmpl
  exporter/exporterhelper/internal/metadata/generated_telemetry_test.go
  processor/batchprocessor/internal/metadata/generated_telemetry_test.go
  processor/memorylimiterprocessor/internal/metadata/generated_telemetry_test.go
  processor/processorhelper/internal/metadata/generated_telemetry_test.go
  receiver/receiverhelper/internal/metadata/generated_telemetry_test.go
  receiver/scraperhelper/internal/metadata/generated_telemetry_test.go
  service/internal/metadata/generated_telemetry_test.go
  service/service.go
Labels: Skip Changelog

#11532 [exporterqueue] Bare minimum frame of queue batcher + unit test.
  exporter/internal/queue/batcher.go
  exporter/internal/queue/disabled_batcher.go
  exporter/internal/queue/disabled_batcher_test.go
  exporter/internal/queue/fake_request.go
Labels: Skip Changelog

#11540 [exporterqueue] Limited worker pool support for queue batcher
  exporter/internal/queue/batcher.go
  exporter/internal/queue/disabled_batcher.go
  exporter/internal/queue/disabled_batcher_test.go
Labels: Skip Changelog

#11549 [chore][docs] Reflect current practices about configuration structs in coding guidelines
  docs/coding-guidelines.md
Labels: Skip Changelog, Skip Contrib Tests

#11572 [chore][docs] Move configuration changes guidelines to component stability doc
  docs/coding-guidelines.md
  docs/component-stability.md
Labels: Skip Changelog, Skip Contrib Tests

#11546 [exporterqueue] Default Batcher that reads from the queue, batches and exports
  exporter/internal/queue/batcher.go
  exporter/internal/queue/default_batcher.go
  exporter/internal/queue/default_batcher_test.go
  exporter/internal/queue/disabled_batcher_test.go
  exporter/internal/queue/fake_request.go
Labels: Skip Changelog
