Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-11, with the labels that each got.

#11583 [docs] Fix link in scraping-receivers.md
  docs/scraping-receivers.md
Labels: ready-to-merge, Skip Changelog, Skip Contrib Tests

#11559 [chore] Add issue template for RFC votes
  .github/ISSUE_TEMPLATE/vote.md
Labels: Skip Changelog, Skip Contrib Tests

#11596 Apply default values before we unmarshal the config, allows not using pointers
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/builder/main.go
  cmd/builder/internal/builder/main_test.go
  cmd/builder/internal/command.go
  cmd/builder/internal/command_test.go
Labels: Skip Changelog

#11605 [chore] fix: pin markdown-link-check to v3.12.2
  package.json
Labels: Skip Contrib Tests

#11604 [chore] add the missing replace in core.builder.yaml
  cmd/builder/test/core.builder.yaml
Labels: ready-to-merge, Skip Changelog, Skip Contrib Tests

#11599 [chore]: enable perfsprint linter
  .golangci.yml
  cmd/mdatagen/internal/metadata.go
  component/componenttest/otelchecker.go
  component/identifiable.go
  config/confighttp/compression_test.go
  config/confighttp/compressor_test.go
  config/confighttp/confighttp_test.go
  config/configopaque/opaque_test.go
  config/configtls/clientcasfilereloader.go
  config/configtls/clientcasfilereloader_test.go
  config/configtls/configtls.go
  confmap/confmap.go
  connector/internal/router.go
  connector/logs_router.go
  exporter/debugexporter/internal/normal/metrics.go
  exporter/exporterhelper/internal/base_exporter.go
  exporter/internal/queue/persistent_queue_test.go
  exporter/otlphttpexporter/otlp_test.go
  featuregate/registry.go
  internal/e2e/otlphttp_test.go
  internal/testutil/testutil.go
  otelcol/buffered_core.go
  pdata/pcommon/value.go
  pipeline/internal/globalsignal/signal.go
  processor/batchprocessor/batch_processor_test.go
  receiver/otlpreceiver/internal/errors/errors_test.go
  service/service_test.go
  service/telemetry/config.go
  service/telemetry/internal/otelinit/config.go
Labels: ready-to-merge, ci-cd

#11580 [chore] [exporterqueue] Add splitting to the experimental pull-based batcher
  exporter/internal/queue/batcher.go
  exporter/internal/queue/default_batcher.go
  exporter/internal/queue/default_batcher_test.go
  exporter/internal/queue/fake_request.go
Labels: Skip Changelog

#11557 [chore][docs] Add code owners policy
  CONTRIBUTING.md
Labels: Skip Changelog, Skip Contrib Tests

#11620 [chore] Simplify test only code in exporterhelper
  exporter/exporterhelper/exporterhelperprofiles/profiles_test.go
  exporter/exporterhelper/internal/request.go
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/traces_test.go
Labels: Skip Contrib Tests

#11621 [chore] Move test code under _test
  exporter/internal/queue/fake_request_test.go
  exporter/internal/queue/mock_storage.go
  exporter/internal/queue/persistent_queue_test.go
Labels: Skip Contrib Tests

#11667 [mdatagen]: require.Emptyf on config diff
  cmd/mdatagen/internal/sampleprocessor/internal/metadata/generated_config_test.go
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_config_test.go
  cmd/mdatagen/internal/templates/config_test.go.tmpl
Labels: Skip Changelog

#11668 [chore] Use pseudo-versions to require `componenttest`
  cmd/mdatagen/go.mod
  cmd/otelcorecol/go.mod
  config/configgrpc/go.mod
  config/confighttp/go.mod
  connector/connectortest/go.mod
  connector/forwardconnector/go.mod
  exporter/debugexporter/go.mod
  exporter/exporterhelper/exporterhelperprofiles/go.mod
  exporter/exportertest/go.mod
  exporter/go.mod
  exporter/nopexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/auth/go.mod
  extension/go.mod
  extension/memorylimiterextension/go.mod
  extension/zpagesextension/go.mod
  internal/e2e/go.mod
  internal/sharedcomponent/go.mod
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  processor/batchprocessor/go.mod
  processor/go.mod
  processor/memorylimiterprocessor/go.mod
  processor/processorhelper/processorhelperprofiles/go.mod
  processor/processortest/go.mod
  receiver/go.mod
  receiver/nopreceiver/go.mod
  receiver/otlpreceiver/go.mod
  receiver/receivertest/go.mod
  service/go.mod
Labels: Skip Changelog

#11657 Add a new scraper package to replace scraperhelper
  scraper/Makefile
  scraper/README.md
  scraper/doc.go
  scraper/factory.go
  scraper/factory_test.go
  scraper/generated_package_test.go
  scraper/go.mod
  scraper/go.sum
  scraper/metadata.yaml
  scraper/metrics.go
  scraper/metrics_test.go
  scraper/scraper.go
  versions.yaml
Labels: Skip Changelog

#11650 Fix small comments in exporter helper
  exporter/internal/queue/bounded_memory_queue.go
  exporter/internal/queue/queue.go
  exporter/internal/request.go
Labels: Skip Changelog, Skip Contrib Tests

#11676 [chore] Run `make genotelcorecol` to fix "build-and-test / checks"
  .github/workflows/api-compatibility.yml
  .github/workflows/build-and-test-windows.yaml
  .github/workflows/build-and-test.yml
  .github/workflows/builder-integration-test.yaml
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contrib-tests.yml
  .github/workflows/perf.yml
  .github/workflows/prepare-release.yml
  .github/workflows/tidy-dependencies.yml
  cmd/otelcorecol/go.mod
Labels: Skip Changelog, Skip Contrib Tests

#11683 [chore] Generate `replace` directives automatically in `check-contrib`
  Makefile
Labels: ci-cd

#11686 fix confignet README (dialer timeout)
  .chloggen/confignet-readme.yaml
  config/confignet/README.md
Labels: Skip Changelog, Skip Contrib Tests, contribfest

#11651 Make sure flagValue.String() can be called even when flagValue is created by reflect.New
  .chloggen/feature-gate-help-cmd-option.yaml
  featuregate/flag.go
  featuregate/flag_test.go
Labels: ready-to-merge, Skip Contrib Tests

#11482 [chore][VERSIONING.md] Document approach to optional experimental interfaces
  VERSIONING.md
Labels: Skip Contrib Tests

#11719 [chore] pin markdown-link-check
  package.json
Labels: ready-to-merge

#11723 [chore] Update meeting times
  README.md
Labels: ready-to-merge

#11724 [chore] Use pseudo-versions to require `authtest`
  config/configgrpc/go.mod
  config/confighttp/go.mod
Labels: ready-to-merge

#11730 [chore] Add @jade-guiton-dd as a triager
  README.md
Labels: Skip Changelog, Skip Contrib Tests

#11721 [exporter] Feature gate for queue batcher
  exporter/debugexporter/go.mod
  exporter/debugexporter/go.sum
  exporter/exporterhelper/exporterhelperprofiles/go.mod
  exporter/exporterhelper/exporterhelperprofiles/go.sum
  exporter/exporterhelper/internal/base_exporter.go
  exporter/exporterhelper/internal/base_exporter_test.go
  exporter/exporterhelper/internal/batch_sender_test.go
  exporter/exporterhelper/internal/queue_sender_test.go
  exporter/exporterhelper/internal/retry_sender_test.go
  exporter/exporterhelper/internal/test_util.go
  exporter/exporterprofiles/go.mod
  exporter/exportertest/go.mod
  exporter/exportertest/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/nopexporter/go.mod
  exporter/nopexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
Labels: ready-to-merge, Skip Changelog

#11406 RFC - Pipeline Component Telemetry
  docs/rfcs/component-universal-telemetry.md
Labels: Skip Changelog, Skip Contrib Tests, rfc:final-comment-period
