Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-02, with the labels that each got.

#9447 Add enumeration expectations
  CONTRIBUTING.md
Labels: Skip Changelog

#9442 [configopaque, confmap] Change yaml test by confmap test
  config/configopaque/go.mod
  config/configopaque/go.sum
  config/configopaque/opaque_test.go
  config/configtls/go.mod
  config/configtls/go.sum
  confmap/go.mod
  confmap/go.sum
Labels: Skip Changelog

#9450 [chore] Update groups
  .github/workflows/contrib-tests.yml
Labels: ready-to-merge

#9402 [configgrpc] Deprecate GRPCClientSettings, use ClientConfig instead
  .chloggen/grpcclientsettings_grpcclientconfig-otlpreceiver.yaml
  .chloggen/grpcclientsettings_grpcclientconfig.yaml
  config/configgrpc/configgrpc.go
  config/configgrpc/configgrpc_test.go
  exporter/otlpexporter/config.go
  exporter/otlpexporter/config_test.go
  exporter/otlpexporter/factory.go
  exporter/otlpexporter/factory_test.go
  exporter/otlpexporter/otlp.go
  exporter/otlpexporter/otlp_test.go
  internal/e2e/consume_contract_test.go
Labels: Skip Contrib Tests

#9453 [chore] Update httpconfig API to not include HTTP prefix
  .chloggen/httpclientsettings_httpclientconfig-breaking.yaml
  .chloggen/httpclientsettings_httpclientconfig.yaml
  .chloggen/httpserversettings_httpserverconfig-otlpreceiver.yaml
  .chloggen/httpserversettings_httpserverconfig.yaml
  config/confighttp/compression_test.go
  config/confighttp/confighttp.go
  config/confighttp/confighttp_test.go
  exporter/otlphttpexporter/config.go
  exporter/otlphttpexporter/config_test.go
  exporter/otlphttpexporter/factory.go
  exporter/otlphttpexporter/factory_test.go
  exporter/otlphttpexporter/otlp.go
  exporter/otlphttpexporter/otlp_test.go
  internal/e2e/otlphttp_test.go
  receiver/otlpreceiver/config.go
  receiver/otlpreceiver/config_test.go
  receiver/otlpreceiver/factory.go
  receiver/otlpreceiver/factory_test.go
  receiver/otlpreceiver/otlp.go
  receiver/otlpreceiver/otlp_test.go
Labels: release:blocker, Skip Contrib Tests

#9217 [chore][config/configgrpc] Enable goleak check
  config/configgrpc/configgrpc_test.go
  config/configgrpc/go.mod
  config/configgrpc/go.sum
  config/configgrpc/package_test.go
Labels: Stale

#9466 [builder] Close files immediately after writing is complete
  cmd/builder/internal/builder/main.go
  cmd/builder/internal/builder/main_test.go
Labels: Skip Changelog

#9518 add go 1.22 to tests
  .github/workflows/build-and-test.yml
Labels: Skip Changelog

#9489 [configretry] validate max_elapsed_time
  .chloggen/check_max_elapsed_time.yaml
  config/configretry/backoff.go
  config/configretry/backoff_test.go
Labels: release:required-for-ga

#9503 [confmap] Remove deprecated `confmap.WithErrorUnused`
  .chloggen/remove_withErrorUnused.yaml
  cmd/mdatagen/internal/metadata/generated_config.go
  cmd/mdatagen/loader.go
  cmd/mdatagen/metricdata.go
  cmd/mdatagen/templates/config.go.tmpl
  confmap/confmap.go
  confmap/confmap_test.go
Labels: release:required-for-ga

#9512 [config/configrpc] Deprecate SanitizedEndpoint, ToListener and ToListenerContext
  .chloggen/mx-psi_deprecate-configgrpc.yaml
  config/configgrpc/configgrpc.go
Labels: release:required-for-ga

#9506 [component] Remove host.ReportFatalError
  .chloggen/remove_ReportFatalError.yaml
  component/componenttest/nop_host.go
  component/componenttest/nop_host_test.go
  component/host.go
  service/host.go
Labels: release:required-for-ga

#9523 [otlpexporter] Validate the configuration explicitly
  exporter/otlpexporter/config.go
  exporter/otlpexporter/config_test.go
  exporter/otlpexporter/factory.go
  exporter/otlpexporter/factory_test.go
  exporter/otlpexporter/otlp.go
  exporter/otlpexporter/testdata/invalid_configs.yaml
Labels: Skip Changelog

#9566 Update security-best-practices.md
  docs/security-best-practices.md
Labels: Skip Changelog

#9529 [confignet] Rename NetAddr and TCPAddr to follow conventions
  .chloggen/mx-psi_confignet.yaml
  config/configgrpc/configgrpc.go
  config/configgrpc/configgrpc_test.go
  config/confignet/confignet.go
  config/confignet/confignet_test.go
  extension/zpagesextension/config.go
  extension/zpagesextension/config_test.go
  extension/zpagesextension/factory.go
  extension/zpagesextension/factory_test.go
  extension/zpagesextension/zpagesextension_test.go
  receiver/otlpreceiver/config_test.go
  receiver/otlpreceiver/factory.go
  receiver/otlpreceiver/factory_test.go
  receiver/otlpreceiver/otlp_test.go
  service/service_test.go
Labels: release:required-for-ga

#9603 [chore] [exporterhelper] Remove duplicated code between exporter helpers
  exporter/exporterhelper/common.go
  exporter/exporterhelper/common_test.go
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/queue_sender_test.go
  exporter/exporterhelper/retry_sender_test.go
  exporter/exporterhelper/traces.go
Labels: Skip Changelog

#9614 [confignet] Remove deprecated structs
  .chloggen/confignet-remove-deprecated-structs.yaml
  config/confignet/confignet.go
Labels: release:required-for-ga

#9552 [mdatagen] Add flag to indicate seeking new code owners
  cmd/mdatagen/main_test.go
  cmd/mdatagen/statusdata.go
  cmd/mdatagen/templates/readme.md.tmpl
  cmd/mdatagen/testdata/readme_with_status_codeowners_and_seeking_new.md
Labels: Skip Changelog

#9630 add openssf badge to read me
  README.md
Labels: Skip Changelog

#9495 [configtls] Rename config structs for consistency
  .chloggen/rename_configtls_structs.yaml
  config/configgrpc/configgrpc.go
  config/configgrpc/configgrpc_test.go
  config/confighttp/confighttp.go
  config/confighttp/confighttp_test.go
  config/configtls/configtls.go
  config/configtls/configtls_test.go
  exporter/otlpexporter/config_test.go
  exporter/otlpexporter/factory_test.go
  exporter/otlpexporter/otlp_test.go
  exporter/otlphttpexporter/config_test.go
  exporter/otlphttpexporter/factory_test.go
  internal/e2e/consume_contract_test.go
  receiver/otlpreceiver/config_test.go
  receiver/otlpreceiver/otlp_test.go
Labels: release:required-for-ga, ready-to-merge

#9142 [configtls] add include_system_ca_certs_pool
  .chloggen/UseSystemCACerts.yaml
  config/configtls/README.md
  config/configtls/configtls.go
  config/configtls/configtls_test.go
Labels: Stale
