Repository open-telemetry/opentelemetry-collector, pull requests merged in 2024-05, with the labels that each got.

#10029 Documentation improvements - Comments in key functions
  confmap/confmap.go
  confmap/resolver.go
  otelcol/collector.go
  otelcol/command.go
  service/internal/graph/graph.go
  service/service.go
Labels: Skip Changelog

#10078 Revert pipeline type validation
  .chloggen/revert-validate-pipeline-types.yaml
  otelcol/collector.go
  otelcol/collector_test.go
Labels: release:blocker

#10066 [otelcol] rfc for how to log during startup
  docs/rfcs/logging-before-config-resolution.md
Labels: Skip Changelog

#10120 Move Aneurysm9 to emeritus status
  README.md
  docs/release.md
Labels: Skip Changelog

#10130 [mdatagen] use main as package for cmd types
  cmd/mdatagen/generated_package_test.go
  cmd/mdatagen/main.go
  cmd/mdatagen/metadata.yaml
  cmd/mdatagen/templates/package_test.go.tmpl
Labels: Skip Changelog

#10129 [mdatagen] only generate telemetry as needed
  cmd/mdatagen/main.go
  connector/forwardconnector/go.mod
  connector/forwardconnector/internal/metadata/generated_telemetry.go
  connector/forwardconnector/internal/metadata/generated_telemetry_test.go
  exporter/debugexporter/go.mod
  exporter/debugexporter/internal/metadata/generated_telemetry.go
  exporter/debugexporter/internal/metadata/generated_telemetry_test.go
  exporter/loggingexporter/go.mod
  exporter/loggingexporter/internal/metadata/generated_telemetry.go
  exporter/loggingexporter/internal/metadata/generated_telemetry_test.go
  exporter/nopexporter/go.mod
  exporter/nopexporter/internal/metadata/generated_telemetry.go
  exporter/nopexporter/internal/metadata/generated_telemetry_test.go
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/internal/metadata/generated_telemetry.go
  exporter/otlpexporter/internal/metadata/generated_telemetry_test.go
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/internal/metadata/generated_telemetry.go
  exporter/otlphttpexporter/internal/metadata/generated_telemetry_test.go
  extension/ballastextension/go.mod
  extension/ballastextension/internal/metadata/generated_telemetry.go
  extension/ballastextension/internal/metadata/generated_telemetry_test.go
  extension/memorylimiterextension/go.mod
  extension/memorylimiterextension/internal/metadata/generated_telemetry.go
  extension/memorylimiterextension/internal/metadata/generated_telemetry_test.go
  extension/zpagesextension/go.mod
  extension/zpagesextension/internal/metadata/generated_telemetry.go
  extension/zpagesextension/internal/metadata/generated_telemetry_test.go
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/internal/metadata/generated_telemetry.go
  processor/memorylimiterprocessor/internal/metadata/generated_telemetry_test.go
  receiver/nopreceiver/go.mod
  receiver/nopreceiver/internal/metadata/generated_telemetry.go
  receiver/nopreceiver/internal/metadata/generated_telemetry_test.go
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/internal/metadata/generated_telemetry.go
  receiver/otlpreceiver/internal/metadata/generated_telemetry_test.go
Labels: Skip Changelog

#10127 ExporterHelper tests - switch to DataType instead of Type
  exporter/exporterhelper/batch_sender_test.go
  exporter/exporterhelper/common_test.go
  exporter/exporterhelper/queue_sender_test.go
  exporter/exporterhelper/retry_sender_test.go
Labels: Skip Changelog

#10128 MemoryLimiterProcessor - switch to MustNewID instead of zero value ID
  processor/memorylimiterprocessor/memorylimiter_test.go
Labels: Skip Changelog

#10135 [confmap] Add logger to ConverterSettings
  .chloggen/confmap-converter-logger.yaml
  confmap/converter.go
  confmap/converter/expandconverter/expand.go
  confmap/converter/expandconverter/expand_test.go
  confmap/resolver.go
  confmap/resolver_test.go
  otelcol/collector.go
Labels: ready-to-merge

#10149 Add origin field name option to base fields
  pdata/internal/cmd/pdatagen/internal/base_fields.go
Labels: Skip Changelog

#10155 Upgrade proto and generate profiles
  Makefile
  pdata/internal/data/protogen/collector/profiles/v1experimental/profiles_service.pb.go
  pdata/internal/data/protogen/profiles/v1experimental/pprofextended.pb.go
  pdata/internal/data/protogen/profiles/v1experimental/profiles.pb.go
  proto_patch.sed
Labels: Skip Changelog

#10167 Upgrade the used otlp version in readme
  README.md
Labels: Skip Changelog

#10159 [mdatagen] add support for async instruments
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry_test.go
  cmd/mdatagen/internal/samplereceiver/metadata.yaml
  cmd/mdatagen/loader_test.go
  cmd/mdatagen/metricdata.go
  cmd/mdatagen/metricdata_test.go
  cmd/mdatagen/templates/telemetry.go.tmpl
  cmd/mdatagen/templates/telemetry_test.go.tmpl
  exporter/exporterhelper/internal/metadata/generated_telemetry.go
  exporter/exporterhelper/internal/metadata/generated_telemetry_test.go
  processor/batchprocessor/internal/metadata/generated_telemetry.go
  processor/batchprocessor/internal/metadata/generated_telemetry_test.go
  processor/processorhelper/internal/metadata/generated_telemetry.go
  processor/processorhelper/internal/metadata/generated_telemetry_test.go
  receiver/receiverhelper/internal/metadata/generated_telemetry.go
  receiver/receiverhelper/internal/metadata/generated_telemetry_test.go
  receiver/scraperhelper/internal/metadata/generated_telemetry.go
  receiver/scraperhelper/internal/metadata/generated_telemetry_test.go
Labels: Skip Changelog

#10068 Documentation improvements - Internal Architecture Doc + Package level comments
  CONTRIBUTING.md
  component/component.go
  docs/internal-architecture.md
  otelcol/collector.go
  service/internal/graph/graph.go
Labels: Skip Changelog

#10178 [chore] Remove unused package test file from otelcorecol
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/package_test.go
Labels: Skip Changelog, Skip Contrib Tests

#10206 [mdatagen] Add basic telemetry test
  cmd/mdatagen/main_test.go
  cmd/mdatagen/metadata-schema.yaml
  cmd/mdatagen/testdata/invalid_telemetry_missing_value_type_for_histogram.yaml
  cmd/mdatagen/testdata/with_telemetry.yaml
Labels: Skip Changelog

#10210 [chore] disable gosec checks that cause performance issues
  .golangci.yml
Labels: Skip Contrib Tests

#10165 [chore] follow codeql recommendation
  Makefile.Common
  cmd/builder/go.mod
  cmd/mdatagen/go.mod
  cmd/otelcorecol/go.mod
  component/go.mod
  config/configauth/go.mod
  config/configcompression/go.mod
  config/configgrpc/go.mod
  config/confighttp/go.mod
  config/confignet/go.mod
  config/configopaque/go.mod
  config/configretry/go.mod
  config/configtelemetry/go.mod
  config/configtls/go.mod
  config/internal/go.mod
  confmap/converter/expandconverter/go.mod
  confmap/go.mod
  confmap/provider/envprovider/go.mod
  confmap/provider/fileprovider/go.mod
  confmap/provider/httpprovider/go.mod
  confmap/provider/httpsprovider/go.mod
  confmap/provider/yamlprovider/go.mod
  connector/forwardconnector/go.mod
  connector/go.mod
  consumer/go.mod
  exporter/debugexporter/go.mod
  exporter/go.mod
  exporter/loggingexporter/go.mod
  exporter/nopexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/auth/go.mod
  extension/ballastextension/go.mod
  extension/go.mod
  extension/memorylimiterextension/go.mod
  extension/zpagesextension/go.mod
  featuregate/go.mod
  filter/go.mod
  go.mod
  internal/e2e/go.mod
  internal/tools/go.mod
  otelcol/go.mod
  pdata/go.mod
  pdata/testdata/go.mod
  processor/batchprocessor/go.mod
  processor/go.mod
  processor/memorylimiterprocessor/go.mod
  receiver/go.mod
  receiver/nopreceiver/go.mod
  receiver/otlpreceiver/go.mod
  semconv/go.mod
  service/go.mod
Labels: Skip Contrib Tests

#10233 [batchprocessor] use mdatagen for async metric
  processor/batchprocessor/batch_processor_test.go
  processor/batchprocessor/documentation.md
  processor/batchprocessor/go.mod
  processor/batchprocessor/internal/metadata/generated_telemetry.go
  processor/batchprocessor/metadata.yaml
  processor/batchprocessor/metrics.go
Labels: Skip Changelog

#10246 [confmap] Add new tests
  confmap/expand_test.go
Labels: Skip Changelog

#8990 [docs] add documentation regarding verify images signatures
  .chloggen/doc-verify-images.yaml
  README.md
Labels: Stale, Skip Changelog

#10235 [processorhelper] use mdatagen level and noop meter
  processor/processorhelper/obsreport.go
  processor/processorhelper/obsreport_test.go
Labels: Skip Changelog
