Repository open-telemetry/opentelemetry-collector, pull requests merged in 2025-03, with the labels that each got.

#12464 [mdatagen] Add deprecation date and migration note fields for deprecated components
  .chloggen/mdatagen_deprecation_fields.yaml
  cmd/mdatagen/internal/command_test.go
  cmd/mdatagen/internal/loader_test.go
  cmd/mdatagen/internal/metadata_test.go
  cmd/mdatagen/internal/samplereceiver/README.md
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_status.go
  cmd/mdatagen/internal/samplereceiver/metadata.yaml
  cmd/mdatagen/internal/status.go
  cmd/mdatagen/internal/templates/readme.md.tmpl
  cmd/mdatagen/internal/testdata/deprecation_info_invalid_date.yaml
  cmd/mdatagen/internal/testdata/no_deprecation_date_info.yaml
  cmd/mdatagen/internal/testdata/no_deprecation_info.yaml
  cmd/mdatagen/internal/testdata/no_deprecation_migration_info.yaml
  cmd/mdatagen/internal/testdata/readme_with_multiple_signals_and_deprecation.md
  cmd/mdatagen/metadata-schema.yaml
  docs/component-stability.md
Labels: cmd/mdatagen

#12567 [extensionauthtest] Remove extensionauthtest.MockClient
  .chloggen/mx-psi_seal-them-all.yaml
  config/configgrpc/configgrpc_test.go
  config/configgrpc/go.mod
  config/confighttp/confighttp_test.go
  exporter/otlpexporter/go.mod
  extension/extensionauth/extensionauthtest/error_client.go
  extension/extensionauth/extensionauthtest/error_client_test.go
  extension/extensionauth/extensionauthtest/go.mod
  extension/extensionauth/extensionauthtest/mock_clientauth.go
  extension/extensionauth/extensionauthtest/mock_clientauth_test.go
Labels: exporter/otlp

#12575 [chore] bump otel-go deps
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  config/configgrpc/go.mod
  config/configgrpc/go.sum
  config/confighttp/go.mod
  config/confighttp/go.sum
  config/confighttp/xconfighttp/go.mod
  config/confighttp/xconfighttp/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  extension/zpagesextension/go.mod
  extension/zpagesextension/go.sum
  internal/e2e/go.mod
  internal/e2e/go.sum
  otelcol/config_test.go
  otelcol/go.mod
  otelcol/go.sum
  otelcol/otelcoltest/go.mod
  otelcol/otelcoltest/go.sum
  otelcol/testdata/otelcol-invalid-yaml.yaml
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/go.sum
  service/attributes.go
  service/attributes_test.go
  service/config_test.go
  service/go.mod
  service/go.sum
  service/hostcapabilities/go.mod
  service/hostcapabilities/go.sum
  service/internal/promtest/server_util.go
  service/service.go
  service/service_test.go
  service/telemetry/config.go
  service/telemetry/config_test.go
  service/telemetry/factory.go
  service/telemetry/factory_test.go
  service/telemetry/internal/migration/v0.2.0.go
  service/telemetry/internal/migration/v0.2.0_test.go
  service/telemetry/internal/migration/v0.3.0.go
  service/telemetry/logger_test.go
  service/telemetry/metrics_test.go
  service/telemetry/tracer_test.go
Labels: Skip Contrib Tests

#12569 Update whitespace for list formatting
  docs/scraping-receivers.md
Labels: Skip Changelog

#12577 [chore] remove unintended file addition
  otelcol/testdata/otelcol-invalid-yaml.yaml
Labels: Skip Changelog, Skip Contrib Tests

#12579 [chore] update receiverhelper to main
  cmd/otelcorecol/go.mod
  internal/e2e/go.mod
  receiver/otlpreceiver/go.mod
  scraper/scraperhelper/go.mod
Labels: Skip Contrib Tests

#11837 [service] Include component id/type in start error
  .chloggen/improve_start_component_error.yaml
  service/internal/graph/graph.go
  service/internal/graph/lifecycle_test.go
Labels: ready-to-merge, Skip Contrib Tests

#11964 [extension/zpages] Add an option to enable expvar
  .chloggen/zpagesextension-add-expvar.yaml
  extension/zpagesextension/README.md
  extension/zpagesextension/config.go
  extension/zpagesextension/zpagesextension.go
  extension/zpagesextension/zpagesextension_test.go
Labels: ready-to-merge, Skip Contrib Tests, extension/zpages

#12581 [chore] Remove dead code from receiver internal
  receiver/internal/obsmetrics.go
Labels: Skip Contrib Tests

#12584 [chore] update min version in tidy
  Makefile.Common
  cmd/builder/internal/builder/main.go
Labels: Skip Contrib Tests, release:risky-change

#12576 [chore] replace deprecated tenv with usetesting
  .golangci.yml
  config/configgrpc/configgrpc_test.go
  config/configtls/clientcasfilereloader_test.go
  config/configtls/configtls_test.go
  confmap/internal/e2e/fuzz_test.go
  confmap/provider/internal/configurablehttpprovider/provider_test.go
  confmap/resolver_test.go
Labels: Skip Contrib Tests

#12597 [chore] bump go version
  .github/workflows/api-compatibility.yml
  .github/workflows/build-and-test-arm.yml
  .github/workflows/build-and-test-windows.yaml
  .github/workflows/build-and-test.yml
  .github/workflows/builder-integration-test.yaml
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contrib-tests.yml
  .github/workflows/perf.yml
  .github/workflows/prepare-release.yml
  .github/workflows/tidy-dependencies.yml
  cmd/otelcorecol/go.mod
Labels: release:risky-change

#12550 Bytes based batching for metrics
  exporter/exporterhelper/internal/sizer/logs_sizer.go
  exporter/exporterhelper/internal/sizer/logs_sizer_test.go
  exporter/exporterhelper/internal/sizer/metrics_sizer.go
  exporter/exporterhelper/internal/sizer/metrics_sizer_test.go
  exporter/exporterhelper/internal/sizer/proto_delta_sizer.go
  exporter/exporterhelper/internal/sizer/proto_delta_sizer_test.go
  exporter/exporterhelper/logs_batch_test.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/metrics_batch.go
  exporter/exporterhelper/metrics_batch_test.go
  pdata/pmetric/pb.go
Labels: Skip Changelog

#12616 [chore] Reduce port contention in service tests
  service/service_test.go
Labels: Skip Contrib Tests

#12610 [chore] Reorganize documentation regarding consumer errors for receiver
  consumer/consumererror/doc.go
  receiver/doc.go
Labels: Skip Contrib Tests

#12608 Switch the pprofile.AddAttribute to use pcommon.Value rather than raw data
  pdata/pprofile/attributes.go
  pdata/pprofile/attributes_test.go
Labels: Skip Changelog

#12403 [chore] Support connector in metrics.go.tmpl NewMetricsBuilder
  .chloggen/fix_cmd_mdata-gen-metrics.yml
  cmd/mdatagen/README.md
  cmd/mdatagen/go.mod
  cmd/mdatagen/internal/sampleconnector/doc.go
  cmd/mdatagen/internal/sampleconnector/documentation.md
  cmd/mdatagen/internal/sampleconnector/factory.go
  cmd/mdatagen/internal/sampleconnector/generated_component_test.go
  cmd/mdatagen/internal/sampleconnector/generated_package_test.go
  cmd/mdatagen/internal/sampleconnector/internal/metadata/generated_config.go
  cmd/mdatagen/internal/sampleconnector/internal/metadata/generated_config_test.go
  cmd/mdatagen/internal/sampleconnector/internal/metadata/generated_metrics.go
  cmd/mdatagen/internal/sampleconnector/internal/metadata/generated_metrics_test.go
  cmd/mdatagen/internal/sampleconnector/internal/metadata/generated_resource.go
  cmd/mdatagen/internal/sampleconnector/internal/metadata/generated_resource_test.go
  cmd/mdatagen/internal/sampleconnector/internal/metadata/generated_status.go
  cmd/mdatagen/internal/sampleconnector/internal/metadata/testdata/config.yaml
  cmd/mdatagen/internal/sampleconnector/metadata.yaml
  cmd/mdatagen/internal/sampleconnector/metrics_test.go
  cmd/mdatagen/internal/templates/metrics.go.tmpl
  cmd/mdatagen/internal/templates/metrics_test.go.tmpl
Labels: cmd/mdatagen

#12348 [mdatagen] delete generated_status.go in case it is not required
  .chloggen/delete_old_status.yaml
  cmd/mdatagen/internal/command.go
  cmd/mdatagen/internal/command_test.go
  cmd/mdatagen/internal/testdata/basic_pkg.yaml
Labels: Stale, cmd/mdatagen

#11989 Update module github.com/cenkalti/backoff/v4 to v5
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  config/configretry/backoff.go
  config/configretry/go.mod
  config/configretry/go.sum
  exporter/debugexporter/go.mod
  exporter/debugexporter/go.sum
  exporter/exporterhelper/internal/retry_sender.go
  exporter/exporterhelper/xexporterhelper/go.mod
  exporter/exporterhelper/xexporterhelper/go.sum
  exporter/exportertest/go.mod
  exporter/exportertest/go.sum
  exporter/go.mod
  exporter/go.sum
  exporter/nopexporter/go.sum
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
  exporter/otlphttpexporter/go.mod
  exporter/otlphttpexporter/go.sum
  internal/e2e/go.mod
  internal/e2e/go.sum
  otelcol/go.sum
  otelcol/otelcoltest/go.sum
  service/go.sum
Labels: dependencies

#12519 Bytes based batching for traces
  exporter/exporterhelper/internal/sizer/traces_sizer.go
  exporter/exporterhelper/internal/sizer/traces_sizer_test.go
  exporter/exporterhelper/logs_batch_test.go
  exporter/exporterhelper/traces.go
  exporter/exporterhelper/traces_batch.go
  exporter/exporterhelper/traces_batch_test.go
  pdata/ptrace/pb.go
Labels: Skip Changelog

#12640 [mdatagen] Add supportsSignal func
  .chloggen/add-supports-signal-func.yaml
  cmd/mdatagen/internal/command.go
  cmd/mdatagen/internal/metadata.go
Labels: cmd/mdatagen

#12613 [service] Allow running the Collector without any pipelines
  .chloggen/allow-no-pipelines.yaml
  otelcol/config.go
  otelcol/config_test.go
  service/pipelines/config.go
  service/pipelines/config_test.go
Labels: ready-to-merge, Skip Contrib Tests

#12648 [chore] Remove deprecation notice for `(pcommon.Map).Range`
  pdata/pcommon/map.go
Labels: release:retro

#12674 Revert "fix(deps): update module github.com/shirou/gopsutil/v4 to v4.25.2 (#12654)"
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  extension/memorylimiterextension/go.mod
  extension/memorylimiterextension/go.sum
  internal/e2e/go.mod
  internal/e2e/go.sum
  internal/memorylimiter/go.mod
  internal/memorylimiter/go.sum
  otelcol/go.mod
  otelcol/go.sum
  otelcol/otelcoltest/go.mod
  otelcol/otelcoltest/go.sum
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/go.sum
  service/go.mod
  service/go.sum
Labels: Skip Changelog

#12673 Revert "fix(deps): update module github.com/prometheus/common to v0.63.0 (#12656)"
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  internal/e2e/go.mod
  internal/e2e/go.sum
  otelcol/go.mod
  otelcol/go.sum
  otelcol/otelcoltest/go.mod
  otelcol/otelcoltest/go.sum
  service/go.mod
  service/go.sum
Labels: Skip Changelog

#12660 Define the final stable config for QueueBatch component
  exporter/exporterhelper/internal/queuebatch/config.go
Labels: Skip Changelog, Skip Contrib Tests

#12671 [chore] Added spell check
  .github/workflows/spell-check.yaml
  .github/workflows/utils/cspell.json
  CHANGELOG-API.md
  CHANGELOG.md
  docs/component-status.md
  exporter/README.md
Labels: ci-cd, Skip Changelog, Skip Contrib Tests

#12696 [chore] Allow to configure available sizers in the queuebatch Settings
  exporter/exporterhelper/internal/base_exporter.go
  exporter/exporterhelper/internal/obs_queue.go
  exporter/exporterhelper/internal/obs_queue_test.go
  exporter/exporterhelper/internal/queue_sender.go
  exporter/exporterhelper/internal/queue_sender_test.go
  exporter/exporterhelper/internal/queuebatch/disabled_batcher_test.go
  exporter/exporterhelper/internal/queuebatch/disabled_queue.go
  exporter/exporterhelper/internal/queuebatch/memory_queue.go
  exporter/exporterhelper/internal/queuebatch/persistent_queue.go
  exporter/exporterhelper/internal/queuebatch/persistent_queue_test.go
  exporter/exporterhelper/internal/queuebatch/queue.go
  exporter/exporterhelper/internal/queuebatch/queue_batch.go
  exporter/exporterhelper/internal/queuebatch/sizer.go
  exporter/exporterhelper/internal/queuebatch/sizer_test.go
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/request.go
  exporter/exporterhelper/traces.go
  exporter/exporterhelper/xexporterhelper/profiles.go
Labels: Skip Changelog

#12639 [chore] Fix ARM unit test
  config/configgrpc/configgrpc_test.go
Labels: Run ARM

#12718 Avoid using go embedded messages in Config
  .chloggen/avoid-embedings-in-conifg.yaml
  exporter/otlpexporter/config.go
  exporter/otlpexporter/config_test.go
  exporter/otlpexporter/factory_test.go
  exporter/otlphttpexporter/config.go
  exporter/otlphttpexporter/factory.go
  exporter/otlphttpexporter/factory_test.go
  exporter/otlphttpexporter/otlp.go
  internal/e2e/otlphttp_test.go
  receiver/otlpreceiver/config.go
  receiver/otlpreceiver/config_test.go
  receiver/otlpreceiver/factory.go
  receiver/otlpreceiver/factory_test.go
  receiver/otlpreceiver/otlp.go
  receiver/otlpreceiver/otlp_test.go
Labels: exporter/otlp, receiver/otlp, exporter/otlphttp

#12733 [chore] Auto-populate versions during release preparation
  .github/workflows/prepare-release.yml
  docs/release.md
Labels: release:risky-change

#12741 [chore]: Add benchmark.txt to gitignore
  .gitignore
Labels: ready-to-merge, Skip Contrib Tests

#12737 [chore] trigger changelog CI check on PR title edit
  .github/workflows/changelog.yml
Labels: ready-to-merge, Skip Contrib Tests

#12716 [chore][ping-codeowners-on-new-issue] Ping even if owner filed
  .github/workflows/scripts/ping-codeowners-on-new-issue.sh
Labels: ready-to-merge, ci-cd, Skip Contrib Tests

#12750 [chore] update tests to use Empty
  component/component_test.go
  exporter/otlphttpexporter/factory_test.go
  internal/memorylimiter/cgroups/mountpoint_test.go
  pdata/pcommon/spanid_test.go
  pdata/pcommon/trace_state_test.go
  pdata/pcommon/traceid_test.go
  pdata/pcommon/value_test.go
  pdata/pmetric/aggregation_temporality_test.go
  pdata/pmetric/exemplar_value_type_test.go
  pdata/pmetric/metric_type_test.go
  pdata/pmetric/number_data_point_value_type_test.go
  pdata/pprofile/aggregation_temporality_test.go
  pdata/pprofile/profileid_test.go
Labels: ci-cd, Skip Changelog, Skip Contrib Tests

#12697 [processor] Mark module as 1.x
  .chloggen/mx-psi_processor-1.0.yaml
  versions.yaml
Labels: release:blocker

#12757 [builder] Remove deprecated OtelColVersion, already an error if used
  cmd/builder/internal/builder/config.go
  cmd/builder/internal/builder/config_test.go
Labels: Skip Changelog, Skip Contrib Tests

#12755 [chore] Use T for generics instead of K, consistent with rest of the repo
  exporter/exporterhelper/internal/queue_sender.go
  exporter/exporterhelper/internal/queuebatch/batcher.go
  exporter/exporterhelper/internal/queuebatch/default_batcher.go
  exporter/exporterhelper/internal/queuebatch/disabled_batcher.go
  exporter/exporterhelper/internal/queuebatch/queue_batch.go
  exporter/exporterhelper/internal/sender/sender.go
  exporter/exporterhelper/internal/sendertest/sendertest.go
  exporter/exporterhelper/internal/timeout_sender.go
  exporter/exporterhelper/request.go
Labels: Skip Contrib Tests

#12761 [chore] unexport test structs
  confmap/confmap_test.go
  confmap/internal/e2e/fuzz_test.go
  confmap/internal/e2e/types_test.go
  confmap/resolver_test.go
Labels: Skip Contrib Tests

#12756 Mark telemetry.disableAddressFieldForInternalTelemetry as beta, usage of deprecated address are ignored
  .chloggen/disableAddressFieldForInternalTelemetry.yaml
  service/telemetry/config.go
Labels: release:blocker, Skip Contrib Tests

#12770 [chore] Update exporter helper config documentation
  exporter/exporterhelper/README.md
Labels: Skip Contrib Tests
