Repository open-telemetry/opentelemetry-collector, pull requests merged in 2025-02, with the labels that each got.

#12246 Revert "[exporter][queuebatcher] set feature gate UsePullingBasedExporterQueueBatcher to beta"
  .chloggen/set-new-queue-batching-to-beta.yaml
  exporter/exporterhelper/internal/base_exporter.go
  exporter/exporterhelper/internal/batch_sender_test.go
Labels: Skip Changelog, release:blocker

#12257 Fix MergeSplit issue that ignores the initial message size
  .chloggen/fix-traces-split.yaml
  exporter/exporterhelper/logs_batch.go
  exporter/exporterhelper/logs_batch_test.go
  exporter/exporterhelper/metrics_batch.go
  exporter/exporterhelper/metrics_batch_test.go
  exporter/exporterhelper/traces_batch.go
  exporter/exporterhelper/traces_batch_test.go
  exporter/exporterhelper/xexporterhelper/profiles_batch.go
  exporter/exporterhelper/xexporterhelper/profiles_batch_test.go
Labels: release:blocker

#12261 Add AIX/ppc64 to CI builds
  .github/workflows/build-and-test.yml
Labels: Skip Changelog

#12273 Update jpkroehling's affiliation
  README.md
Labels: Skip Changelog

#12189 [component] Remove TelemetrySettings.MetricsLevel
  .chloggen/mx-psi_remove-metricslevel.yaml
  cmd/mdatagen/go.mod
  component/componentstatus/go.mod
  component/componenttest/go.mod
  component/componenttest/nop_telemetry.go
  component/componenttest/nop_telemetry_test.go
  component/componenttest/telemetry.go
  component/componenttest/telemetry_test.go
  component/go.mod
  component/telemetry.go
  config/configauth/go.mod
  config/configgrpc/go.mod
  config/confighttp/go.mod
  config/confighttp/xconfighttp/go.mod
  connector/connectortest/go.mod
  connector/forwardconnector/go.mod
  connector/go.mod
  connector/xconnector/go.mod
  exporter/exporterhelper/xexporterhelper/go.mod
  exporter/exportertest/go.mod
  exporter/go.mod
  exporter/nopexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  exporter/xexporter/go.mod
  extension/auth/authtest/go.mod
  extension/auth/go.mod
  extension/extensioncapabilities/go.mod
  extension/extensiontest/go.mod
  extension/go.mod
  extension/memorylimiterextension/go.mod
  extension/xextension/go.mod
  extension/zpagesextension/go.mod
  internal/memorylimiter/go.mod
  internal/sharedcomponent/go.mod
  processor/batchprocessor/go.mod
  processor/go.mod
  processor/memorylimiterprocessor/go.mod
  processor/processorhelper/xprocessorhelper/go.mod
  processor/processortest/go.mod
  processor/xprocessor/go.mod
  receiver/go.mod
  receiver/nopreceiver/go.mod
  receiver/otlpreceiver/go.mod
  receiver/receivertest/go.mod
  receiver/xreceiver/go.mod
  scraper/go.mod
  scraper/scraperhelper/go.mod
  scraper/scrapertest/go.mod
  service/service.go
Labels: release:blocker

#12309 [editorial] Add headings to configauth/README.md
  config/configauth/README.md
Labels: Skip Changelog

#12306 [chore] update go-build-tools
  .github/ALLOWLIST
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/other.yaml
  internal/tools/go.mod
  internal/tools/go.sum
Labels: ci-cd

#12331 [chore] Update codeowners according to releases-approvers RFC
  .github/CODEOWNERS
Labels: Skip Changelog, Skip Contrib Tests

#12333 [chore] Remove resolved TODO about span name prefix
  config/confighttp/confighttp.go
Labels: Skip Contrib Tests

#12337 [service] update changelog to identify a breaking change
  CHANGELOG.md
Labels: Skip Changelog, Skip Contrib Tests

#12364 [chore] Update exporterhelper README.md
  exporter/exporterhelper/README.md
Labels: Skip Changelog, Skip Contrib Tests

#12355 [receiver/otlp, exporter/otlp] Use NewDefaultConfig
  exporter/otlpexporter/factory.go
  receiver/otlpreceiver/config_test.go
  receiver/otlpreceiver/factory.go
  receiver/otlpreceiver/go.mod
Labels: Skip Changelog

#12334 [chore] Move LoggerWithout temporarily to internal package
  .chloggen/component-logger-api.yaml
  cmd/builder/internal/builder/main_test.go
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  component/componentattribute/go.mod
  component/componentattribute/go.sum
  component/telemetry.go
  internal/e2e/go.mod
  internal/telemetry/Makefile
  internal/telemetry/componentattribute/attribute.go
  internal/telemetry/componentattribute/logger.go
  internal/telemetry/componentattribute/logger_test.go
  internal/telemetry/go.mod
  internal/telemetry/go.sum
  internal/telemetry/telemetry.go
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  processor/memorylimiterprocessor/factory.go
  processor/memorylimiterprocessor/factory_test.go
  processor/memorylimiterprocessor/go.mod
  receiver/otlpreceiver/factory_test.go
  receiver/otlpreceiver/go.mod
  receiver/otlpreceiver/otlp.go
  service/extensions/extensions.go
  service/go.mod
  service/internal/attribute/attribute.go
  service/internal/attribute/attribute_test.go
  service/internal/graph/connector.go
  service/internal/graph/exporter.go
  service/internal/graph/processor.go
  service/internal/graph/receiver.go
  versions.yaml
Labels: Skip Changelog, release:blocker

#12374 [chore] remove unused variable
  .github/workflows/check-links.yaml
Labels: ci-cd, Skip Contrib Tests

#12373 [chore] Add fmt step to mdatagen-test
  Makefile
Labels: ci-cd, Skip Contrib Tests

#12366 Fix otlphttpexporter parsing logic for Retry-After
  .chloggen/fix-otlp-http-exp.yaml
  exporter/otlphttpexporter/otlp.go
  exporter/otlphttpexporter/otlp_test.go
Labels: exporter/otlphttp

#12220 Make MakeFactoryMap generic and move to otelcol
  .chloggen/generic-makefactorymap.yaml
  cmd/builder/internal/builder/templates/components.go.tmpl
  cmd/otelcorecol/components.go
  connector/connector.go
  exporter/exporter.go
  extension/extension.go
  internal/e2e/go.mod
  internal/e2e/go.sum
  otelcol/factories.go
  otelcol/factories_test.go
  otelcol/otelcoltest/go.mod
  otelcol/otelcoltest/nop_factories.go
  processor/processor.go
  receiver/receiver.go
  scraper/factory.go
  service/go.mod
  service/go.sum
  service/internal/builders/builders.go
  service/internal/builders/builders_test/connector_test.go
  service/internal/builders/builders_test/exporter_test.go
  service/internal/builders/builders_test/extension_test.go
  service/internal/builders/builders_test/processor_test.go
  service/internal/builders/builders_test/receiver_test.go
  service/internal/builders/connector.go
  service/internal/builders/exporter.go
  service/internal/builders/extension.go
  service/internal/builders/processor.go
  service/internal/builders/receiver.go
Labels: release:blocker

#12367 Fix OTLP http receiver to correctly set Retry-After
  .chloggen/fix-http-receiver.yaml
  exporter/otlpexporter/otlp.go
  exporter/otlphttpexporter/otlp.go
  go.mod
  internal/statusutil/helper.go
  internal/statusutil/helper_test.go
  receiver/otlpreceiver/otlphttp.go
  receiver/otlpreceiver/otlphttp_test.go
Labels: exporter/otlp, receiver/otlp, exporter/otlphttp

#12274 [chore][docs] Add guidance regarding breaking changes
  docs/coding-guidelines.md
Labels: Skip Contrib Tests

#12391 [chore] Use pseudoversion for internal/telemetry
  cmd/otelcorecol/go.mod
  internal/e2e/go.mod
  otelcol/go.mod
  otelcol/otelcoltest/go.mod
  processor/memorylimiterprocessor/go.mod
  receiver/otlpreceiver/go.mod
  service/go.mod
Labels: Skip Contrib Tests

#12388 [docs] Fix links `syslist.go`
  docs/observability.md
  docs/platform-support.md
Labels: Skip Changelog

#12408 [chore] More pseudoversions bumps
  cmd/otelcorecol/go.mod
  exporter/debugexporter/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  internal/e2e/go.mod
Labels: exporter/otlp, exporter/otlphttp, exporter/debug

#12423 [exporter/otlp] update stability level
  .chloggen/codeboten_fix-logs-stability.yaml
  exporter/otlpexporter/README.md
  exporter/otlpexporter/internal/metadata/generated_status.go
  exporter/otlpexporter/metadata.yaml
  exporter/otlphttpexporter/README.md
  exporter/otlphttpexporter/internal/metadata/generated_status.go
  exporter/otlphttpexporter/metadata.yaml
Labels: exporter/otlp, exporter/otlphttp

#12323 [confighttp] Remove pointers from integer fields
  .chloggen/confighttp-remove-pointers.yaml
  config/confighttp/confighttp.go
  config/confighttp/confighttp_test.go
  exporter/otlphttpexporter/config_test.go
Labels: Skip Contrib Tests

#12441 [chore] Update release schedule
  docs/release.md
Labels: Skip Contrib Tests

#12445 [chore] Promote Chao Weng to triager
  README.md
Labels: Skip Changelog, Skip Contrib Tests

#12456 [mdatagen] fix missing resource attributes import in metrics template
  .chloggen/mdatagen-fix.yaml
  cmd/mdatagen/internal/templates/metrics.go.tmpl
Labels: cmd/mdatagen

#12460 [chore] [mdatagen] Use ScopeName variable instead of actual value
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_metrics.go
  cmd/mdatagen/internal/samplescraper/internal/metadata/generated_metrics.go
  cmd/mdatagen/internal/templates/metrics.go.tmpl
Labels: cmd/mdatagen

#12450 Add support to configure min GC intervals for soft and hard limits
  .chloggen/add-support-for-gc.yaml
  extension/memorylimiterextension/factory.go
  extension/memorylimiterextension/memorylimiter_test.go
  internal/memorylimiter/config.go
  internal/memorylimiter/config_test.go
  internal/memorylimiter/go.mod
  internal/memorylimiter/go.sum
  internal/memorylimiter/memorylimiter.go
  internal/memorylimiter/memorylimiter_test.go
  processor/memorylimiterprocessor/factory.go
Labels: processor/memorylimiter, extension/memorylimiter

#12180 [confmap] Add error hint when invalid YAML was passed
  .chloggen/mx-psi_error-map.yaml
  confmap/provider.go
  confmap/provider_test.go
  otelcol/collector_test.go
Labels: Stale

#12479 [chore] Add naming guidance for modules prefix
  docs/coding-guidelines.md
Labels: Skip Contrib Tests

#12486 Start using the new SizeConfig
  .chloggen/finishsize.yaml
  .chloggen/finishsize_breaking.yaml
  .chloggen/finishsize_deprecation.yaml
  exporter/exporterbatcher/config.go
  exporter/exporterbatcher/config_test.go
  exporter/exporterbatcher/sizer_type.go
  exporter/exporterbatcher/sizer_type_test.go
  exporter/exporterhelper/internal/base_exporter.go
  exporter/exporterhelper/internal/batcher/default_batcher.go
  exporter/exporterhelper/internal/batcher/default_batcher_test.go
  exporter/exporterhelper/internal/queue_sender_test.go
  exporter/exporterhelper/internal/request/request.go
  exporter/exporterhelper/internal/requesttest/fake_request.go
  exporter/exporterhelper/internal/retry_sender_test.go
  exporter/exporterhelper/logs_batch.go
  exporter/exporterhelper/logs_batch_test.go
  exporter/exporterhelper/metrics_batch.go
  exporter/exporterhelper/metrics_batch_test.go
  exporter/exporterhelper/traces_batch.go
  exporter/exporterhelper/traces_batch_test.go
  exporter/exporterhelper/xexporterhelper/go.mod
  exporter/exporterhelper/xexporterhelper/profiles_batch.go
  exporter/exporterhelper/xexporterhelper/profiles_batch_test.go
  exporter/exportertest/go.mod
  exporter/otlpexporter/config_test.go
  exporter/otlpexporter/testdata/config.yaml
Labels: Skip Contrib Tests

#12467 [mdatagen] Add Converter and Provider support
  .chloggen/add-confmap-to-mdatagen.yaml
  cmd/mdatagen/internal/command.go
  cmd/mdatagen/internal/command_test.go
  cmd/mdatagen/internal/status.go
  cmd/mdatagen/internal/templates/readme.md.tmpl
  cmd/mdatagen/internal/testdata/readme_with_status_converter.md
  cmd/mdatagen/internal/testdata/readme_with_status_provider.md
  cmd/mdatagen/metadata-schema.yaml
Labels: cmd/mdatagen

#12499 [envprovider] Add README file
  confmap/provider/envprovider/README.md
  confmap/provider/envprovider/generated_package_test.go
  confmap/provider/envprovider/metadata.yaml
  confmap/provider/envprovider/provider.go
Labels: Skip Changelog, Skip Contrib Tests

#12481 [configauth] Add `omitempty` tags to fields
  .chloggen/configauth-omitempty.yaml
  config/configauth/configauth.go
  internal/e2e/configauth_test.go
  internal/e2e/go.mod
Labels: Skip Contrib Tests

#12497 [chore][mdatagen] Remove telemetry::level from schema file
  cmd/mdatagen/metadata-schema.yaml
Labels: cmd/mdatagen

#12299 [exporter][batching] Serialized bytes based batching for logs
  exporter/exporterbatcher/sizer_type.go
  exporter/exporterhelper/internal/sizer/logs_sizer.go
  exporter/exporterhelper/internal/sizer/logs_sizer_test.go
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/logs_batch.go
  exporter/exporterhelper/logs_batch_test.go
  pdata/plog/pb.go
Labels: Skip Changelog

#12498 Update metadata schema with new fields without enforcing them
  .chloggen/update_metadata_schema.yaml
  cmd/mdatagen/internal/status.go
  cmd/mdatagen/metadata-schema.yaml
Labels: Skip Contrib Tests, cmd/mdatagen

#12381 [connector,exporter,processor,receiver] Error out on mismatched type
  .chloggen/mx-psi_type-mismatch.yaml
  connector/connector.go
  connector/connector_test.go
  connector/internal/factory.go
  exporter/exporter.go
  exporter/exporter_test.go
  exporter/exportertest/contract_checker.go
  exporter/internal/experr/err.go
  exporter/xexporter/exporter.go
  exporter/xexporter/exporter_test.go
  processor/batchprocessor/batch_processor_test.go
  processor/internal/err.go
  processor/processor.go
  processor/processor_test.go
  processor/processortest/shutdown_verifier.go
  processor/processortest/unhealthy_processor_test.go
  processor/xprocessor/processor.go
  processor/xprocessor/processor_test.go
  receiver/internal/err.go
  receiver/otlpreceiver/otlp_test.go
  receiver/receiver.go
  receiver/receiver_test.go
  receiver/receivertest/contract_checker.go
  receiver/xreceiver/profiles.go
  receiver/xreceiver/receiver_test.go
Labels: receiver/otlp, processor/batch

#12504 [chore][envprovider] Fix OTel doc link
  confmap/provider/envprovider/provider.go
Labels: Skip Contrib Tests

#12454 [processor/memorylimiter] Add profiles support to memorylimiter processor
  .chloggen/iblancasa-memorylimiterprocessor-add-support-profiles.yaml
  cmd/builder/internal/builder/main_test.go
  cmd/otelcorecol/builder-config.yaml
  cmd/otelcorecol/go.mod
  processor/memorylimiterprocessor/README.md
  processor/memorylimiterprocessor/factory.go
  processor/memorylimiterprocessor/factory_test.go
  processor/memorylimiterprocessor/go.mod
  processor/memorylimiterprocessor/internal/metadata/generated_status.go
  processor/memorylimiterprocessor/memorylimiter.go
  processor/memorylimiterprocessor/memorylimiter_test.go
  processor/memorylimiterprocessor/metadata.yaml
Labels: ready-to-merge, processor/memorylimiter

#12480 [extension/extensionauth] Deprecate methods on Func types
  .chloggen/mx-psi_deprecate-func-methods.yaml
  extension/extensionauth/client.go
  extension/extensionauth/server.go
Labels: release:blocker

#12511 [chore][extensionauth] Return error on NewClient and NewServer constructors
  config/configauth/configauth_test.go
  config/configgrpc/configgrpc_test.go
  config/confighttp/confighttp_test.go
  extension/auth/client.go
  extension/auth/server.go
  extension/extensionauth/client.go
  extension/extensionauth/client_test.go
  extension/extensionauth/server.go
  extension/extensionauth/server_test.go
Labels: release:blocker

#12521 [chore] pin extensionauth and extensionauthtest to published version
  cmd/otelcorecol/go.mod
  config/configauth/go.mod
  config/configgrpc/go.mod
  config/confighttp/go.mod
  config/confighttp/xconfighttp/go.mod
  exporter/otlpexporter/go.mod
  exporter/otlphttpexporter/go.mod
  extension/auth/authtest/go.mod
  extension/auth/go.mod
  extension/extensionauth/extensionauthtest/go.mod
  extension/zpagesextension/go.mod
  internal/e2e/go.mod
  receiver/otlpreceiver/go.mod
  service/go.mod
Labels: release:blocker

#12522 [chore] Small comments fix in exporterhelper/sizer
  exporter/exporterhelper/internal/sizer/logs_sizer.go
Labels: Skip Contrib Tests

#12435 [docs] add guidance around what a collector/distro is
  docs/README.md
Labels: Skip Changelog, Skip Contrib Tests

#12523 [cmd/mdatagen] fix #12298 unit tests failures
  .chloggen/fix-12298.yaml
  cmd/mdatagen/internal/templates/component_test.go.tmpl
  cmd/mdatagen/internal/templates/telemetrytest.go.tmpl
  cmd/mdatagen/internal/templates/telemetrytest_test.go.tmpl
Labels: Skip Contrib Tests, cmd/mdatagen

#12509 Remove exporterqueue.Factory and simplify exportehelper.WithQueueRequest
  .chloggen/break-exporterqueue-factory.yaml
  .chloggen/new-queue-factory.yaml
  exporter/exporterhelper/common.go
  exporter/exporterhelper/internal/base_exporter.go
  exporter/exporterhelper/internal/base_exporter_test.go
  exporter/exporterhelper/internal/batcher/disabled_batcher_test.go
  exporter/exporterhelper/internal/obs_queue.go
  exporter/exporterhelper/internal/obs_queue_test.go
  exporter/exporterhelper/internal/queue_sender.go
  exporter/exporterhelper/internal/queue_sender_test.go
  exporter/exporterhelper/internal/retry_sender_test.go
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/queue_sender.go
  exporter/exporterhelper/traces.go
  exporter/exporterhelper/xexporterhelper/profiles.go
  exporter/exporterqueue/config.go
  exporter/exporterqueue/persistent_queue.go
  exporter/exporterqueue/persistent_queue_test.go
  exporter/exporterqueue/queue.go
Labels: Skip Contrib Tests
