Repository open-telemetry/opentelemetry-collector, pull requests merged in 2025-07, with the labels that each got.

#13317 Update release procedure document
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests

#13318 promote dmathieu to approver
  README.md
  docs/release.md
Labels: Skip Changelog

#13262 Add both bytes and items sizes to the persistent metadata
  .chloggen/persistent-metadata-sizes.yaml
  .chloggen/persistent-metadata.yaml
  exporter/exporterhelper/internal/base_exporter.go
  exporter/exporterhelper/internal/base_exporter_test.go
  exporter/exporterhelper/internal/queue/async_queue_test.go
  exporter/exporterhelper/internal/queue/memory_queue.go
  exporter/exporterhelper/internal/queue/memory_queue_test.go
  exporter/exporterhelper/internal/queue/meta.pb.go
  exporter/exporterhelper/internal/queue/meta.proto
  exporter/exporterhelper/internal/queue/persistent_queue.go
  exporter/exporterhelper/internal/queue/persistent_queue_test.go
  exporter/exporterhelper/internal/queue/queue.go
  exporter/exporterhelper/internal/queue/sizer_conversion.go
  exporter/exporterhelper/internal/queue/sizer_conversion_test.go
  exporter/exporterhelper/internal/queue_sender.go
  exporter/exporterhelper/internal/queue_sender_test.go
  exporter/exporterhelper/internal/queuebatch/disabled_batcher_test.go
  exporter/exporterhelper/internal/queuebatch/partition_batcher_test.go
  exporter/exporterhelper/internal/queuebatch/queue_batch.go
  exporter/exporterhelper/internal/queuebatch/queue_batch_test.go
  exporter/exporterhelper/internal/requesttest/request.go
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/request.go
  exporter/exporterhelper/traces.go
  exporter/exporterhelper/xexporterhelper/profiles.go
Labels: Skip Changelog

#13339 [otlpexporter] Remove deprecated batcher config from OTLP, use queuebatch
  .chloggen/rm-otlp-old-batcher.yaml
  exporter/otlpexporter/config.go
  exporter/otlpexporter/factory.go
  exporter/otlpexporter/otlp.go
Labels: exporter/otlp

#13346 Swap 7/14 and 7/28 releases with mx-psi
  docs/release.md
Labels: Skip Changelog, Skip Contrib Tests

#13347 [chore] Update release troubleshooting guidelines
  docs/release.md
Labels: Skip Contrib Tests

#13260 Update Pipeline Component Telemetry RFC
  docs/rfcs/component-universal-telemetry.md
Labels: Skip Changelog, Skip Contrib Tests, rfc:final-comment-period

#13364 [chore] convert configgrpc.KeepaliveServerConfig.ServerParameters and…
  .chloggen/13252-configgrpc-keepalive-configoptional.yaml
  config/configgrpc/configgrpc.go
  config/configgrpc/configgrpc_test.go
  receiver/otlpreceiver/config_test.go
Labels: ready-to-merge, receiver/otlp

#13401 [chore] add cspell check file pattern for .chloggen
  .github/workflows/spell-check.yaml
  .github/workflows/utils/cspell.json
Labels: ci-cd, Skip Changelog, Skip Contrib Tests

#13404 [chore] Fix actionlint tool installation process
  .github/workflows/lint-workflow-files.yml
  Makefile
  Makefile.Common
Labels: ci-cd, Skip Contrib Tests, release:risky-change

#13400 collector builder should require go 1.23 as go.opentelemetry.io v1.36.0 requires go 1.23
  cmd/builder/internal/builder/templates/go.mod.tmpl
Labels: ready-to-merge, Skip Changelog, Skip Contrib Tests

#13405 [chore] build otelcorecol with grpcnotrace to remove one usage of text/templates
  Makefile
Labels: release:risky-change

#12982 Avoid the exporter for being stuck when telemetry data is bigger than batch.max_size
  .chloggen/12893.yaml
  exporter/exporterhelper/internal/queuebatch/batcher.go
  exporter/exporterhelper/internal/queuebatch/multi_batcher.go
  exporter/exporterhelper/internal/queuebatch/multi_batcher_test.go
  exporter/exporterhelper/internal/queuebatch/partition_batcher.go
  exporter/exporterhelper/internal/queuebatch/partition_batcher_test.go
  exporter/exporterhelper/internal/queuebatch/queue_batch.go
  exporter/exporterhelper/logs_batch.go
  exporter/exporterhelper/logs_batch_test.go
  exporter/exporterhelper/metrics_batch.go
  exporter/exporterhelper/metrics_batch_test.go
  exporter/exporterhelper/traces_batch.go
  exporter/exporterhelper/traces_batch_test.go
Labels: ready-to-merge

#13244 Add testable examples to pdata module
  pdata/plog/doc_test.go
  pdata/pmetric/doc_test.go
  pdata/ptrace/doc_test.go
Labels: ready-to-merge, Skip Changelog

#13414 Fallback to content type in error handler
  .chloggen/13414-otlp-receiver-error-handler.yaml
  receiver/otlpreceiver/otlp_test.go
  receiver/otlpreceiver/otlphttp.go
Labels: ready-to-merge, receiver/otlp

#13448 Bump golang version to latest patch release
  .github/workflows/api-compatibility.yml
  .github/workflows/build-and-test-arm.yml
  .github/workflows/build-and-test-windows.yaml
  .github/workflows/build-and-test.yml
  .github/workflows/builder-integration-test.yaml
  .github/workflows/builder-snapshot.yaml
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contrib-tests.yml
  .github/workflows/lint-workflow-files.yml
  .github/workflows/perf.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release-branch.yml
  .github/workflows/tidy-dependencies.yml
  cmd/otelcorecol/go.mod
Labels: dependencies, release:risky-change

#13463 [chore][docs] Remove release process for contrib and replace with link
  docs/release.md
Labels: Skip Contrib Tests

#13464 [chore][docs] Remove release process for 'releases' and replace with link
  docs/release.md
Labels: Skip Contrib Tests

#13484 [chore] Refactor pdatagen field generators into separate files
  internal/cmd/pdatagen/internal/base_fields.go
  internal/cmd/pdatagen/internal/base_struct.go
  internal/cmd/pdatagen/internal/field.go
  internal/cmd/pdatagen/internal/message_field.go
  internal/cmd/pdatagen/internal/one_of_field.go
  internal/cmd/pdatagen/internal/one_of_message_value.go
  internal/cmd/pdatagen/internal/one_of_primitive_value.go
  internal/cmd/pdatagen/internal/optional_primitive_field.go
  internal/cmd/pdatagen/internal/pcommon_package.go
  internal/cmd/pdatagen/internal/plog_package.go
  internal/cmd/pdatagen/internal/plogotlp_package.go
  internal/cmd/pdatagen/internal/pmetric_package.go
  internal/cmd/pdatagen/internal/pmetricotlp_package.go
  internal/cmd/pdatagen/internal/pprofile_package.go
  internal/cmd/pdatagen/internal/pprofileotlp_package.go
  internal/cmd/pdatagen/internal/primitive_field.go
  internal/cmd/pdatagen/internal/primitive_slice_field.go
  internal/cmd/pdatagen/internal/ptrace_package.go
  internal/cmd/pdatagen/internal/ptraceotlp_package.go
  internal/cmd/pdatagen/internal/slice_field.go
  internal/cmd/pdatagen/internal/templates.go
  internal/cmd/pdatagen/internal/templates/message.go.tmpl
  internal/cmd/pdatagen/internal/templates/slice.go.tmpl
  internal/cmd/pdatagen/internal/typed_field.go
  internal/cmd/pdatagen/internal/xpdata_entity_package.go
  pdata/pcommon/generated_instrumentationscope.go
  pdata/pcommon/generated_resource.go
  pdata/xpdata/entity/generated_entityref.go
Labels: Skip Contrib Tests

#13469 Add missing import for 'metadata' through mdatagen
  .chloggen/13069-mdatagen-import.yaml
  cmd/mdatagen/internal/loader.go
  cmd/mdatagen/internal/loader_test.go
  cmd/mdatagen/internal/metadata.go
  cmd/mdatagen/internal/templates/telemetrytest_test.go.tmpl
Labels: cmd/mdatagen

#13494 Remove all usages of jsonpb from pdata
  pdata/internal/json/json.go
  pdata/plog/plogotlp/request.go
  pdata/plog/plogotlp/request_test.go
  pdata/plog/plogotlp/response.go
  pdata/plog/plogotlp/response_test.go
  pdata/pmetric/pmetricotlp/request.go
  pdata/pmetric/pmetricotlp/response.go
  pdata/pmetric/pmetricotlp/response_test.go
  pdata/pprofile/pprofileotlp/request.go
  pdata/pprofile/pprofileotlp/request_test.go
  pdata/pprofile/pprofileotlp/response.go
  pdata/pprofile/pprofileotlp/response_test.go
  pdata/ptrace/ptraceotlp/request.go
  pdata/ptrace/ptraceotlp/request_test.go
  pdata/ptrace/ptraceotlp/response.go
  pdata/ptrace/ptraceotlp/response_test.go
Labels: Skip Changelog

#13499 [chore] Ensure that Inf is converted as Infinity
  pdata/internal/json/iterator_test.go
  pdata/internal/json/stream.go
  pdata/internal/json/stream_test.go
Labels: release:blocker

#13430 docs: add testable examples for component.ID and component.Type Closes Issue #13146
  component/identifiable_example_test.go
Labels: Skip Changelog

#13511 [chore] prevent unkeyed literal initialization
  receiver/otlpreceiver/config.go
Labels: receiver/otlp

#13516 Fix merge queue check
  .github/workflows/check-merge-freeze.yml
Labels: Skip Changelog

#13426 [confighttp] - Expose an option to set ForceAttemptHttp2 setting
  .chloggen/http2.yaml
  config/confighttp/README.md
  config/confighttp/confighttp.go
  config/confighttp/confighttp_test.go
  exporter/otlphttpexporter/config_test.go
  internal/e2e/confighttp_test.go
Labels: ready-to-merge, exporter/otlphttp
