Repository open-telemetry/opentelemetry-collector, pull requests merged in 2025-08, with the labels that each got.

#13548 Update supported service extensions in extension/README.md
  extension/README.md
Labels: Skip Changelog, Skip Contrib Tests

#13549 [chore] service/telemetry: remove deprecated feature gate check
  service/telemetry/tracer.go
Labels: Skip Changelog

#13550 [chore] Update renovate.json
  renovate.json
Labels: ci-cd, Skip Changelog, Skip Contrib Tests

#13649 Add featuregate to protect enabling the proto custom marshaling logic
  .chloggen/use-new-protos.yaml
  client/go.mod
  client/go.sum
  consumer/consumererror/go.mod
  consumer/consumererror/go.sum
  consumer/consumererror/xconsumererror/go.mod
  consumer/consumererror/xconsumererror/go.sum
  consumer/consumertest/go.mod
  consumer/consumertest/go.sum
  consumer/go.mod
  consumer/go.sum
  consumer/xconsumer/go.mod
  consumer/xconsumer/go.sum
  internal/fanoutconsumer/go.mod
  internal/fanoutconsumer/go.sum
  pdata/go.mod
  pdata/go.sum
  pdata/internal/state.go
  pdata/plog/pb.go
  pdata/plog/plogotlp/request.go
  pdata/plog/plogotlp/response.go
  pdata/pmetric/pb.go
  pdata/pmetric/pmetricotlp/request.go
  pdata/pmetric/pmetricotlp/response.go
  pdata/pprofile/go.mod
  pdata/pprofile/go.sum
  pdata/pprofile/pb.go
  pdata/pprofile/pprofileotlp/request.go
  pdata/pprofile/pprofileotlp/response.go
  pdata/ptrace/pb.go
  pdata/ptrace/ptraceotlp/request.go
  pdata/ptrace/ptraceotlp/response.go
  pdata/testdata/go.mod
  pdata/testdata/go.sum
  pdata/xpdata/go.mod
  pdata/xpdata/go.sum
Labels: Skip Changelog

#13673 [configgrpc] Make TCP the default transport type
  .chloggen/configgrpc-transport.yaml
  config/configgrpc/README.md
  config/configgrpc/configgrpc.go
  config/configgrpc/configgrpc_test.go
  internal/e2e/configgrpc_test.go
  receiver/otlpreceiver/factory.go
Labels: receiver/otlp

#13600 [chore] use context.Background, not context.TODO
  config/configgrpc/wrappedstream_test.go
Labels: Skip Contrib Tests

#13656 Enable X25519MLKEM768 as per draft-ietf-tls-ecdhe-mlkem
  .chloggen/x25519mlkem768.yaml
  config/configtls/configtls.go
  config/configtls/configtls_test.go
Labels: ready-to-merge

#13584 [chore] refactor statustest, fold into status
  service/extensions/extensions.go
  service/internal/graph/graph_test.go
  service/internal/graph/lifecycle_test.go
  service/internal/status/nop.go
  service/internal/status/nop_test.go
Labels: Stale
