Repository open-telemetry/opentelemetry-collector, pull requests merged in 2025-05, with the labels that each got.

#12837 Implement a merge freeze when an "[chore] Update core dependencies" PR on opentelemetry-collector-contrib is present
  .github/workflows/scripts/check-merge-freeze.sh
Labels: ready-to-merge, ci-cd, Skip Changelog, Skip Contrib Tests

#12954 [chore] add checkapi to tools
  .checkapi.yaml
  .github/workflows/build-and-test.yml
  Makefile
  Makefile.Common
  component/build_info.go
  config/configmiddleware/configmiddleware.go
  config/configtls/tpm.go
  confmap/provider.go
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
  otelcol/config.go
  otelcol/configprovider.go
  receiver/receivertest/contract_checker.go
  service/config.go
Labels: release:risky-change

#12972 Do not run TPM test macos/darwin
  .chloggen/tpm-test-darwin.yaml
  config/configtls/tpm_test.go
Labels: Run ARM

#13015 Avoid allocating too much memory, sampling logic is not re-applied
  .chloggen/fix-13014.yaml
  internal/telemetry/componentattribute/logger_test.go
  internal/telemetry/componentattribute/logger_zap.go
  service/telemetry/logger.go
  service/telemetry/logger_test.go
Labels: release:blocker

#13049 fix typo
  docs/README.md
Labels: Skip Changelog

#13037 [mdatagen] Add events in generated documentation
  .chloggen/mdatagen-events-doc.yaml
  cmd/mdatagen/internal/command.go
  cmd/mdatagen/internal/command_test.go
  cmd/mdatagen/internal/samplereceiver/documentation.md
  cmd/mdatagen/internal/templates/documentation.md.tmpl
  cmd/mdatagen/internal/testdata/events/basic_event.yaml
Labels: cmd/mdatagen

#12958 Add documentation example for exporter package (#5675)
  exporter/example_test.go
  exporter/xexporter/go.sum
Labels: Skip Changelog

#13011 [exporter/debug] display resource and scope in `normal` verbosity
  .chloggen/add-resource-scope.yaml
  exporter/debugexporter/README.md
  exporter/debugexporter/internal/normal/common.go
  exporter/debugexporter/internal/normal/logs.go
  exporter/debugexporter/internal/normal/logs_test.go
  exporter/debugexporter/internal/normal/metrics.go
  exporter/debugexporter/internal/normal/metrics_test.go
  exporter/debugexporter/internal/normal/profiles.go
  exporter/debugexporter/internal/normal/profiles_test.go
  exporter/debugexporter/internal/normal/traces.go
  exporter/debugexporter/internal/normal/traces_test.go
Labels: exporter/debug

#13068 [mdatagen] Add context parameter to set traceID and spanID in generated events
  .chloggen/mdatagen-event-add-context.yaml
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_logs.go
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_logs_test.go
  cmd/mdatagen/internal/templates/logs.go.tmpl
  cmd/mdatagen/internal/templates/logs_test.go.tmpl
Labels: cmd/mdatagen

#13058 [cmd/mdatagen] Add definition of `events` to `metadata-schema.yaml`
  cmd/mdatagen/metadata-schema.yaml
Labels: Skip Changelog, cmd/mdatagen

#13057 Remove false positive cspell exceptions
  .github/workflows/utils/cspell.json
  CHANGELOG-API.md
  CHANGELOG.md
  exporter/exporterhelper/README.md
  receiver/otlpreceiver/config_test.go
  receiver/otlpreceiver/testdata/typo_default_proto_config.yaml
Labels: Skip Changelog

#13081 [service]: use configured logger whenever possible
  .chloggen/tyler.service-log-errors.yaml
  service/service.go
Labels: collector-telemetry

#13108 [componentattribute] Use otelzap.WithAttributes, remove LoggerProviderWithAttributes
  internal/telemetry/componentattribute/logger_provider.go
  internal/telemetry/componentattribute/logger_zap.go
Labels: Skip Changelog
