Repository open-telemetry/opentelemetry-collector, pull requests merged in 2025-09, with the labels that each got.

#13786 Revert "Update module github.com/prometheus/common to v0.66.0"
  cmd/otelcorecol/go.mod
  cmd/otelcorecol/go.sum
  internal/e2e/go.mod
  internal/e2e/go.sum
  internal/e2e/metric_stability_test.go
  otelcol/go.mod
  otelcol/go.sum
  otelcol/otelcoltest/go.mod
  otelcol/otelcoltest/go.sum
  service/go.mod
  service/go.sum
  service/service_test.go
  service/telemetry/otelconftelemetry/metrics_test.go
Labels: Skip Changelog

#13756 Add stability level info on generated metrics' documentation
  .chloggen/expose_stability_lvl.yaml
  cmd/mdatagen/internal/samplereceiver/documentation.md
  cmd/mdatagen/internal/samplescraper/documentation.md
  cmd/mdatagen/internal/samplescraper/metadata.yaml
  cmd/mdatagen/internal/templates/documentation.md.tmpl
  cmd/mdatagen/metadata-schema.yaml
  exporter/exporterhelper/documentation.md
  processor/memorylimiterprocessor/documentation.md
  processor/processorhelper/documentation.md
  receiver/receiverhelper/documentation.md
  scraper/scraperhelper/documentation.md
  service/documentation.md
Labels: cmd/mdatagen

#13825 Fix pprofile timestamp unix nano to be a fixed64
  .chloggen/profiles-otlp-1-8-0.yaml
  internal/cmd/pdatagen/internal/pdata/pprofile_package.go
  pdata/internal/generated_wrapper_profile.go
  pdata/internal/generated_wrapper_profile_test.go
  service/internal/graph/obs_test.go
Labels: Skip Changelog

#13839 fix pprofile protoIDs
  .chloggen/profiles-otlp-1-8-0.yaml
  internal/cmd/pdatagen/internal/pdata/pprofile_package.go
  pdata/internal/generated_wrapper_location.go
  pdata/internal/generated_wrapper_location_test.go
  pdata/internal/generated_wrapper_stack.go
  pdata/internal/generated_wrapper_stack_test.go
Labels: ready-to-merge, Skip Changelog

#13841 Use email to exclude otelbot from merge freeze
  .github/workflows/check-merge-freeze.yml
Labels: ci-cd, Skip Changelog, Skip Contrib Tests, release:retro

#13820 Add "debug merge queue" job
  .github/workflows/check-merge-freeze.yml
Labels: Skip Changelog, Skip Contrib Tests

#13844 feat: migrate to tools directive
  .gitignore
  Makefile
  Makefile.Common
  cmd/builder/test/test.sh
  internal/buildscripts/compare-apidiff.sh
  internal/buildscripts/gen-apidiff.sh
  internal/tools/empty.go
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: Skip Changelog
