Repository open-telemetry/opentelemetry-collector, pull requests merged in 2025-01, with the labels that each got.

#11997 [chore]: reenable default revive rules
  .golangci.yml
  client/doc_test.go
Labels: ci-cd

#12005 [chore] add release docs for artifact version bump script
  docs/release.md
Labels: release, Skip Contrib Tests

#12013 Add changelog for Request Merge removal
  .chloggen/rm-merge-request.yaml
Labels: release:blocker, Skip Contrib Tests

#11940 [chore] Unrevert automatic `replace` generation in builder-integration-test
  cmd/builder/test/core.builder.yaml
  cmd/builder/test/test.sh
Labels: release:blocker

#12034 [chore] [mdatagen] Fix generated telemetry tests
  cmd/mdatagen/internal/loader_test.go
  cmd/mdatagen/internal/samplereceiver/documentation.md
  cmd/mdatagen/internal/samplereceiver/internal/metadata/generated_telemetry.go
  cmd/mdatagen/internal/samplereceiver/internal/metadatatest/generated_telemetrytest_test.go
  cmd/mdatagen/internal/samplereceiver/metadata.yaml
  cmd/mdatagen/internal/templates/telemetrytest_test.go.tmpl
Labels: release:blocker

#12045 [chore] Fix check merge freeze job
  .github/workflows/check-merge-freeze.yml
Labels: release, Skip Contrib Tests, release:retro

#12041 [chore] update link checker to use lychee
  .github/lychee.toml
  .github/workflows/changelog.yml
  .github/workflows/check-links.yaml
  .github/workflows/check_links_config.json
  Makefile
  docs/rfcs/env-vars.md
Labels: github_actions, ci-cd

#12061 [chore]: enable early-return from revive
  .golangci.yml
  processor/memorylimiterprocessor/internal/mock_exporter.go
  service/extensions/graph.go
Labels: ci-cd

#12002 [docs] Remove end-user content from security README
  docs/security-best-practices.md
Labels: Skip Changelog

#12065 [chore] [processor/memory_limiter] docs: fix default value of `spike_limit_percentage`
  processor/memorylimiterprocessor/README.md
Labels: Skip Changelog, processor/memory_limiter

#12064 [chore] [processor/memory_limiter] docs: improve examples
  processor/memorylimiterprocessor/README.md
Labels: Skip Changelog, processor/memory_limiter

#12088 [chore] Move tests related to `component.Type`
  component/config_test.go
  component/identifiable.go
  component/identifiable_test.go
Labels: Skip Contrib Tests

#12090 Add blocking option to control queue behavior when full
  .chloggen/add-blocking-option.yaml
  exporter/exporterhelper/README.md
  exporter/exporterhelper/internal/base_exporter.go
  exporter/exporterhelper/internal/queue_sender.go
  exporter/exporterhelper/internal/queue_sender_test.go
  exporter/exporterqueue/config.go
  exporter/exporterqueue/queue.go
Labels: Skip Contrib Tests

#11981 [chore] Make three meeting rotation permanent
  README.md
Labels: Skip Changelog, Skip Contrib Tests

#11805 [confighttp] Add support for configuring compression levels
  .chloggen/compression-config-option2.yaml
  config/configcompression/compressiontype.go
  config/configcompression/compressiontype_test.go
  config/confighttp/README.md
  config/confighttp/compression.go
  config/confighttp/compression_test.go
  config/confighttp/compressor.go
  config/confighttp/confighttp.go
  exporter/otlpexporter/go.mod
  exporter/otlpexporter/go.sum
Labels: Skip Contrib Tests

#12086 Change metadata class type for scraperhelper, fix metrics tests
  scraper/scraperhelper/README.md
  scraper/scraperhelper/internal/metadatatest/generated_telemetrytest.go
  scraper/scraperhelper/metadata.yaml
  scraper/scraperhelper/obs_metrics_test.go
Labels: Skip Changelog

#12107 [chore] Revert the change in processortest setting creation
  .chloggen/revert-change-name.yaml
  processor/processortest/go.mod
  processor/processortest/nop_processor.go
Labels: ready-to-merge

#11871 [chore][docs/component-stability.md] Add documentation requirements for components based on their stability level
  docs/component-stability.md
Labels: Skip Contrib Tests

#11577 [chore] RFC: Collector releases approvers group
  docs/rfcs/release-approvers.md
Labels: Skip Changelog, Skip Contrib Tests, rfc:final-comment-period

#12175 [confmap]: add more expand tests
  confmap/internal/e2e/expand_test.go
  confmap/internal/e2e/testdata/expand-escaped-env.yaml
Labels: Skip Changelog, Skip Contrib Tests

#12165 Merge observability report sender for all signals, remove duplicate code
  .chloggen/merge-obs-report.yaml
  exporter/exporterhelper/internal/base_exporter.go
  exporter/exporterhelper/internal/obs_report.go
  exporter/exporterhelper/internal/obs_report_sender.go
  exporter/exporterhelper/internal/obs_report_test.go
  exporter/exporterhelper/internal/obsexporter.go
  exporter/exporterhelper/internal/obsmetrics.go
  exporter/exporterhelper/internal/queue_sender_test.go
  exporter/exporterhelper/logs.go
  exporter/exporterhelper/logs_test.go
  exporter/exporterhelper/metrics.go
  exporter/exporterhelper/metrics_test.go
  exporter/exporterhelper/obsreport_test.go
  exporter/exporterhelper/traces.go
  exporter/exporterhelper/traces_test.go
  exporter/exporterhelper/xexporterhelper/profiles.go
  exporter/exporterhelper/xexporterhelper/profiles_test.go
Labels: Skip Changelog, Skip Contrib Tests

#12159 [component] Deprecate TelemetrySettings.MetricsLevel
  .chloggen/mx-psi_metricslevel-detailed.yaml
  component/componenttest/nop_telemetry_test.go
  component/componenttest/telemetry.go
  component/componenttest/telemetry_test.go
  component/telemetry.go
  config/confighttp/confighttp_test.go
  config/confighttp/go.mod
Labels: release:blocker

#12197 Fix govulncheck related to crypto/x509
  .github/workflows/api-compatibility.yml
  .github/workflows/build-and-test-arm.yml
  .github/workflows/build-and-test-windows.yaml
  .github/workflows/build-and-test.yml
  .github/workflows/builder-integration-test.yaml
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contrib-tests.yml
  .github/workflows/perf.yml
  .github/workflows/prepare-release.yml
  .github/workflows/tidy-dependencies.yml
  cmd/otelcorecol/go.mod
Labels: Skip Changelog

#11956 Amend Pipeline Component Telemetry RFC to add a "rejected" outcome
  docs/rfcs/component-universal-telemetry.md
Labels: Skip Changelog, Skip Contrib Tests, rfc:final-comment-period

#12150 doc: add detail to confmap watcher
  confmap/README.md
  confmap/provider.go
  confmap/provider_test.go
Labels: Skip Changelog

#12190 [chore] Clarify allowed changes to struct field tags in VERSIONING.md
  VERSIONING.md
Labels: Skip Contrib Tests

#12216 [metadatatest] Generate NewSettings that accepts componenttest.Telemetry
  .chloggen/newsettings.yaml
  cmd/mdatagen/internal/samplereceiver/internal/metadatatest/generated_telemetrytest.go
  cmd/mdatagen/internal/samplereceiver/metrics_test.go
  cmd/mdatagen/internal/templates/telemetrytest.go.tmpl
  component/componenttest/obsreporttest.go
  component/componenttest/otelchecker.go
  component/componenttest/telemetry.go
  exporter/exporterhelper/internal/metadatatest/generated_telemetrytest.go
  processor/batchprocessor/batch_processor_test.go
  processor/batchprocessor/internal/metadatatest/generated_telemetrytest.go
  processor/memorylimiterprocessor/internal/metadatatest/generated_telemetrytest.go
  processor/memorylimiterprocessor/memorylimiter_test.go
  processor/processorhelper/internal/metadatatest/generated_telemetrytest.go
  processor/processorhelper/logs_test.go
  processor/processorhelper/metrics_test.go
  processor/processorhelper/traces_test.go
  receiver/receiverhelper/internal/metadatatest/generated_telemetrytest.go
  scraper/scraperhelper/controller_test.go
  scraper/scraperhelper/internal/metadatatest/generated_telemetrytest.go
  scraper/scraperhelper/obs_logs_test.go
  scraper/scraperhelper/obs_metrics_test.go
  service/internal/metadatatest/generated_telemetrytest.go
  service/internal/proctelemetry/process_telemetry_linux_test.go
  service/internal/proctelemetry/process_telemetry_test.go
Labels: Skip Contrib Tests

#12214 [component] Make component.Kind a struct
  .chloggen/mx-psi_component-kind-structify.yaml
  component/component.go
  component/component_test.go
  service/service_test.go
Labels: release:blocker

#12108 [component] Print path to error in `ValidateConfig`
  .chloggen/validateconfig-print-path.yaml
  component/config.go
  component/config_test.go
  component/go.mod
  otelcol/config_test.go
Labels: release:blocker
